
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

#include <glib-object.h>
#include <gst/va/va-prelude.h>

G_BEGIN_DECLS

/* enumerations from "gstva.h" */

GST_VA_API
GType gst_va_feature_get_type (void);
#define GST_TYPE_VA_FEATURE (gst_va_feature_get_type())

G_END_DECLS

/* Generated data ends here */

