
unit wayland_client_core;
interface

{
  Automatically converted by H2Pas 1.0.0 from wayland_client_core.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    wayland_client_core.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

Type
Pchar  = ^char;
Puint32_t  = ^uint32_t;
Pwl_argument  = ^wl_argument;
Pwl_display  = ^wl_display;
Pwl_event_queue  = ^wl_event_queue;
Pwl_interface  = ^wl_interface;
Pwl_proxy  = ^wl_proxy;
{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{
 * Copyright © 2008 Kristian Høgsberg
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice (including the
 * next paragraph) shall be included in all copies or substantial
 * portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
  }
{$ifndef WAYLAND_CLIENT_CORE_H}
{$define WAYLAND_CLIENT_CORE_H}
{$include <stdint.h>}
{$include "wayland-util.h"}
{$include "wayland-version.h"}
{ C++ extern C conditionnal removed }
{* \class wl_proxy
 *
 * \brief Represents a protocol object on the client side.
 *
 * A wl_proxy acts as a client side proxy to an object existing in the
 * compositor. The proxy is responsible for converting requests made by the
 * clients with \ref wl_proxy_marshal() into Wayland's wire format. Events
 * coming from the compositor are also handled by the proxy, which will in
 * turn call the handler set with \ref wl_proxy_add_listener().
 *
 * \note With the exception of function \ref wl_proxy_set_queue(), functions
 * accessing a wl_proxy are not normally used by client code. Clients
 * should normally use the higher level interface generated by the scanner to
 * interact with compositor objects.
 *
  }
type
  Pwl_proxy = ^Twl_proxy;
  Twl_proxy = record
      {undefined structure}
    end;

{* \class wl_display
 *
 * \brief Represents a connection to the compositor and acts as a proxy to
 * the wl_display singleton object.
 *
 * A wl_display object represents a client connection to a Wayland
 * compositor. It is created with either \ref wl_display_connect() or
 * \ref wl_display_connect_to_fd(). A connection is terminated using
 * \ref wl_display_disconnect().
 *
 * A wl_display is also used as the \ref wl_proxy for the wl_display
 * singleton object on the compositor side.
 *
 * A wl_display object handles all the data sent from and to the
 * compositor. When a \ref wl_proxy marshals a request, it will write its wire
 * representation to the display's write buffer. The data is sent to the
 * compositor when the client calls \ref wl_display_flush().
 *
 * Incoming data is handled in two steps: queueing and dispatching. In the
 * queue step, the data coming from the display fd is interpreted and
 * added to a queue. On the dispatch step, the handler for the incoming
 * event set by the client on the corresponding \ref wl_proxy is called.
 *
 * A wl_display has at least one event queue, called the <em>default
 * queue</em>. Clients can create additional event queues with \ref
 * wl_display_create_queue() and assign \ref wl_proxy's to it. Events
 * occurring in a particular proxy are always queued in its assigned queue.
 * A client can ensure that a certain assumption, such as holding a lock
 * or running from a given thread, is true when a proxy event handler is
 * called by assigning that proxy to an event queue and making sure that
 * this queue is only dispatched when the assumption holds.
 *
 * The default queue is dispatched by calling \ref wl_display_dispatch().
 * This will dispatch any events queued on the default queue and attempt
 * to read from the display fd if it's empty. Events read are then queued
 * on the appropriate queues according to the proxy assignment.
 *
 * A user created queue is dispatched with \ref wl_display_dispatch_queue().
 * This function behaves exactly the same as wl_display_dispatch()
 * but it dispatches given queue instead of the default queue.
 *
 * A real world example of event queue usage is Mesa's implementation of
 * eglSwapBuffers() for the Wayland platform. This function might need
 * to block until a frame callback is received, but dispatching the default
 * queue could cause an event handler on the client to start drawing
 * again. This problem is solved using another event queue, so that only
 * the events handled by the EGL code are dispatched during the block.
 *
 * This creates a problem where a thread dispatches a non-default
 * queue, reading all the data from the display fd. If the application
 * would call \em poll(2) after that it would block, even though there
 * might be events queued on the default queue. Those events should be
 * dispatched with \ref wl_display_dispatch_pending() or \ref
 * wl_display_dispatch_queue_pending() before flushing and blocking.
  }
  Pwl_display = ^Twl_display;
  Twl_display = record
      {undefined structure}
    end;

{* \class wl_event_queue
 *
 * \brief A queue for \ref wl_proxy object events.
 *
 * Event queues allows the events on a display to be handled in a thread-safe
 * manner. See \ref wl_display for details.
 *
  }
  Pwl_event_queue = ^Twl_event_queue;
  Twl_event_queue = record
      {undefined structure}
    end;

{* Destroy proxy after marshalling
 * @ingroup wl_proxy
  }

const
  WL_MARSHAL_FLAG_DESTROY = 1 shl 0;  

procedure wl_event_queue_destroy(queue:Pwl_event_queue);cdecl;external;
(* Const before type ignored *)
function wl_proxy_marshal_flags(proxy:Pwl_proxy; opcode:Tuint32_t; interface:Pwl_interface; version:Tuint32_t; flags:Tuint32_t; 
           args:array of const):Pwl_proxy;cdecl;external;
function wl_proxy_marshal_flags(proxy:Pwl_proxy; opcode:Tuint32_t; interface:Pwl_interface; version:Tuint32_t; flags:Tuint32_t):Pwl_proxy;cdecl;external;
(* Const before type ignored *)
function wl_proxy_marshal_array_flags(proxy:Pwl_proxy; opcode:Tuint32_t; interface:Pwl_interface; version:Tuint32_t; flags:Tuint32_t; 
           args:Pwl_argument):Pwl_proxy;cdecl;external;
procedure wl_proxy_marshal(p:Pwl_proxy; opcode:Tuint32_t; args:array of const);cdecl;external;
procedure wl_proxy_marshal(p:Pwl_proxy; opcode:Tuint32_t);cdecl;external;
procedure wl_proxy_marshal_array(p:Pwl_proxy; opcode:Tuint32_t; args:Pwl_argument);cdecl;external;
(* Const before type ignored *)
function wl_proxy_create(factory:Pwl_proxy; interface:Pwl_interface):Pwl_proxy;cdecl;external;
function wl_proxy_create_wrapper(proxy:pointer):pointer;cdecl;external;
procedure wl_proxy_wrapper_destroy(proxy_wrapper:pointer);cdecl;external;
(* Const before type ignored *)
function wl_proxy_marshal_constructor(proxy:Pwl_proxy; opcode:Tuint32_t; interface:Pwl_interface; args:array of const):Pwl_proxy;cdecl;external;
function wl_proxy_marshal_constructor(proxy:Pwl_proxy; opcode:Tuint32_t; interface:Pwl_interface):Pwl_proxy;cdecl;external;
(* Const before type ignored *)
function wl_proxy_marshal_constructor_versioned(proxy:Pwl_proxy; opcode:Tuint32_t; interface:Pwl_interface; version:Tuint32_t; args:array of const):Pwl_proxy;cdecl;external;
function wl_proxy_marshal_constructor_versioned(proxy:Pwl_proxy; opcode:Tuint32_t; interface:Pwl_interface; version:Tuint32_t):Pwl_proxy;cdecl;external;
(* Const before type ignored *)
function wl_proxy_marshal_array_constructor(proxy:Pwl_proxy; opcode:Tuint32_t; args:Pwl_argument; interface:Pwl_interface):Pwl_proxy;cdecl;external;
(* Const before type ignored *)
function wl_proxy_marshal_array_constructor_versioned(proxy:Pwl_proxy; opcode:Tuint32_t; args:Pwl_argument; interface:Pwl_interface; version:Tuint32_t):Pwl_proxy;cdecl;external;
procedure wl_proxy_destroy(proxy:Pwl_proxy);cdecl;external;
function wl_proxy_add_listener(proxy:Pwl_proxy; implementation:Pprocedure ; data:pointer):longint;cdecl;external;
(* Const before type ignored *)
function wl_proxy_get_listener(proxy:Pwl_proxy):pointer;cdecl;external;
(* Const before type ignored *)
function wl_proxy_add_dispatcher(proxy:Pwl_proxy; dispatcher_func:Twl_dispatcher_func_t; dispatcher_data:pointer; data:pointer):longint;cdecl;external;
procedure wl_proxy_set_user_data(proxy:Pwl_proxy; user_data:pointer);cdecl;external;
function wl_proxy_get_user_data(proxy:Pwl_proxy):pointer;cdecl;external;
function wl_proxy_get_version(proxy:Pwl_proxy):Tuint32_t;cdecl;external;
function wl_proxy_get_id(proxy:Pwl_proxy):Tuint32_t;cdecl;external;
(* Const before type ignored *)
(* Const before declarator ignored *)
procedure wl_proxy_set_tag(proxy:Pwl_proxy; tag:PPchar);cdecl;external;
(* Const before type ignored *)
(* Const before declarator ignored *)
function wl_proxy_get_tag(proxy:Pwl_proxy):^Pchar;cdecl;external;
(* Const before type ignored *)
function wl_proxy_get_class(proxy:Pwl_proxy):Pchar;cdecl;external;
procedure wl_proxy_set_queue(proxy:Pwl_proxy; queue:Pwl_event_queue);cdecl;external;
(* Const before type ignored *)
function wl_display_connect(name:Pchar):Pwl_display;cdecl;external;
function wl_display_connect_to_fd(fd:longint):Pwl_display;cdecl;external;
procedure wl_display_disconnect(display:Pwl_display);cdecl;external;
function wl_display_get_fd(display:Pwl_display):longint;cdecl;external;
function wl_display_dispatch(display:Pwl_display):longint;cdecl;external;
function wl_display_dispatch_queue(display:Pwl_display; queue:Pwl_event_queue):longint;cdecl;external;
function wl_display_dispatch_queue_pending(display:Pwl_display; queue:Pwl_event_queue):longint;cdecl;external;
function wl_display_dispatch_pending(display:Pwl_display):longint;cdecl;external;
function wl_display_get_error(display:Pwl_display):longint;cdecl;external;
(* Const before type ignored *)
function wl_display_get_protocol_error(display:Pwl_display; interface:PPwl_interface; id:Puint32_t):Tuint32_t;cdecl;external;
function wl_display_flush(display:Pwl_display):longint;cdecl;external;
function wl_display_roundtrip_queue(display:Pwl_display; queue:Pwl_event_queue):longint;cdecl;external;
function wl_display_roundtrip(display:Pwl_display):longint;cdecl;external;
function wl_display_create_queue(display:Pwl_display):Pwl_event_queue;cdecl;external;
function wl_display_prepare_read_queue(display:Pwl_display; queue:Pwl_event_queue):longint;cdecl;external;
function wl_display_prepare_read(display:Pwl_display):longint;cdecl;external;
procedure wl_display_cancel_read(display:Pwl_display);cdecl;external;
function wl_display_read_events(display:Pwl_display):longint;cdecl;external;
procedure wl_log_set_handler_client(handler:Twl_log_func_t);cdecl;external;
{ C++ end of extern C conditionnal removed }
{$endif}

implementation


end.
