unit nm_dbus_interface;

{$DEFINE read_enum}{$DEFINE read_struct}{$DEFINE read_function}

interface

uses
  fp_glib2, fp_nm;

  {$IFDEF FPC}
  {$PACKRECORDS C}
  {$ENDIF}

  {$IFDEF read_enum}
const
  NM_DBUS_SERVICE_ = 'org.freedesktop.NetworkManager';
  NM_DBUS_INTERFACE_ = 'org.freedesktop.NetworkManager';
  NM_DBUS_INTERFACE_ACCESS_POINT = 'org.freedesktop.NetworkManager.AccessPoint';
  NM_DBUS_INTERFACE_ACTIVE_CONNECTION = 'org.freedesktop.NetworkManager.Connection.Active';
  NM_DBUS_INTERFACE_CHECKPOINT = 'org.freedesktop.NetworkManager.Checkpoint';
  NM_DBUS_INTERFACE_DEVICE = 'org.freedesktop.NetworkManager.Device';
  NM_DBUS_INTERFACE_DEVICE_6LOWPAN = 'org.freedesktop.NetworkManager.Device.Lowpan';
  NM_DBUS_INTERFACE_DEVICE_ADSL = 'org.freedesktop.NetworkManager.Device.Adsl';
  NM_DBUS_INTERFACE_DEVICE_BLUETOOTH = 'org.freedesktop.NetworkManager.Device.Bluetooth';
  NM_DBUS_INTERFACE_DEVICE_BOND = 'org.freedesktop.NetworkManager.Device.Bond';
  NM_DBUS_INTERFACE_DEVICE_BRIDGE = 'org.freedesktop.NetworkManager.Device.Bridge';
  NM_DBUS_INTERFACE_DEVICE_DUMMY = 'org.freedesktop.NetworkManager.Device.Dummy';
  NM_DBUS_INTERFACE_DEVICE_GENERIC = 'org.freedesktop.NetworkManager.Device.Generic';
  NM_DBUS_INTERFACE_DEVICE_GRE = 'org.freedesktop.NetworkManager.Device.Gre';
  NM_DBUS_INTERFACE_DEVICE_HSR = 'org.freedesktop.NetworkManager.Device.Hsr';
  NM_DBUS_INTERFACE_DEVICE_INFINIBAND = 'org.freedesktop.NetworkManager.Device.Infiniband';
  NM_DBUS_INTERFACE_DEVICE_IP_TUNNEL = 'org.freedesktop.NetworkManager.Device.IPTunnel';
  NM_DBUS_INTERFACE_DEVICE_LOOPBACK = 'org.freedesktop.NetworkManager.Device.Loopback';
  NM_DBUS_INTERFACE_DEVICE_MACSEC = 'org.freedesktop.NetworkManager.Device.Macsec';
  NM_DBUS_INTERFACE_DEVICE_MACVLAN = 'org.freedesktop.NetworkManager.Device.Macvlan';
  NM_DBUS_INTERFACE_DEVICE_MODEM = 'org.freedesktop.NetworkManager.Device.Modem';
  NM_DBUS_INTERFACE_DEVICE_OLPC_MESH = 'org.freedesktop.NetworkManager.Device.OlpcMesh';
  NM_DBUS_INTERFACE_DEVICE_OVS_BRIDGE = 'org.freedesktop.NetworkManager.Device.OvsBridge';
  NM_DBUS_INTERFACE_DEVICE_OVS_INTERFACE = 'org.freedesktop.NetworkManager.Device.OvsInterface';
  NM_DBUS_INTERFACE_DEVICE_OVS_PORT = 'org.freedesktop.NetworkManager.Device.OvsPort';
  NM_DBUS_INTERFACE_DEVICE_PPP = 'org.freedesktop.NetworkManager.Device.Ppp';
  NM_DBUS_INTERFACE_DEVICE_STATISTICS = 'org.freedesktop.NetworkManager.Device.Statistics';
  NM_DBUS_INTERFACE_DEVICE_TEAM = 'org.freedesktop.NetworkManager.Device.Team';
  NM_DBUS_INTERFACE_DEVICE_TUN = 'org.freedesktop.NetworkManager.Device.Tun';
  NM_DBUS_INTERFACE_DEVICE_VETH = 'org.freedesktop.NetworkManager.Device.Veth';
  NM_DBUS_INTERFACE_DEVICE_VLAN = 'org.freedesktop.NetworkManager.Device.Vlan';
  NM_DBUS_INTERFACE_DEVICE_VRF = 'org.freedesktop.NetworkManager.Device.Vrf';
  NM_DBUS_INTERFACE_DEVICE_VXLAN = 'org.freedesktop.NetworkManager.Device.Vxlan';
  NM_DBUS_INTERFACE_DEVICE_WIFI_P2P = 'org.freedesktop.NetworkManager.Device.WifiP2P';
  NM_DBUS_INTERFACE_DEVICE_WIMAX = 'org.freedesktop.NetworkManager.Device.WiMax';
  NM_DBUS_INTERFACE_DEVICE_WIRED = 'org.freedesktop.NetworkManager.Device.Wired';
  NM_DBUS_INTERFACE_DEVICE_WIREGUARD = 'org.freedesktop.NetworkManager.Device.WireGuard';
  NM_DBUS_INTERFACE_DEVICE_WIRELESS = 'org.freedesktop.NetworkManager.Device.Wireless';
  NM_DBUS_INTERFACE_DEVICE_WPAN = 'org.freedesktop.NetworkManager.Device.Wpan';
  NM_DBUS_INTERFACE_DHCP4_CONFIG = 'org.freedesktop.NetworkManager.DHCP4Config';
  NM_DBUS_INTERFACE_DHCP6_CONFIG = 'org.freedesktop.NetworkManager.DHCP6Config';
  NM_DBUS_INTERFACE_IP4_CONFIG = 'org.freedesktop.NetworkManager.IP4Config';
  NM_DBUS_INTERFACE_IP6_CONFIG = 'org.freedesktop.NetworkManager.IP6Config';
  NM_DBUS_INTERFACE_WIFI_P2P_PEER = 'org.freedesktop.NetworkManager.WifiP2PPeer';
  NM_DBUS_INTERFACE_WIMAX_NSP = 'org.freedesktop.NetworkManager.WiMax.Nsp';

  NM_DBUS_PATH = '/org/freedesktop/NetworkManager';
  NM_DBUS_PATH_ACCESS_POINT = '/org/freedesktop/NetworkManager/AccessPoint';
  NM_DBUS_PATH_WIFI_P2P_PEER = '/org/freedesktop/NetworkManager/WifiP2PPeer';
  NM_DBUS_PATH_WIMAX_NSP = '/org/freedesktop/NetworkManager/Nsp';

  NM_DBUS_INTERFACE_SETTINGS = 'org.freedesktop.NetworkManager.Settings';
  NM_DBUS_PATH_SETTINGS = '/org/freedesktop/NetworkManager/Settings';
  NM_DBUS_INTERFACE_SETTINGS_CONNECTION = 'org.freedesktop.NetworkManager.Settings.Connection';
  NM_DBUS_PATH_SETTINGS_CONNECTION = '/org/freedesktop/NetworkManager/Settings/Connection';
  NM_DBUS_INTERFACE_SETTINGS_CONNECTION_SECRETS = 'org.freedesktop.NetworkManager.Settings.Connection.Secrets';

  NM_DBUS_INTERFACE_AGENT_MANAGER = 'org.freedesktop.NetworkManager.AgentManager';
  NM_DBUS_PATH_AGENT_MANAGER = '/org/freedesktop/NetworkManager/AgentManager';
  NM_DBUS_INTERFACE_SECRET_AGENT = 'org.freedesktop.NetworkManager.SecretAgent';
  NM_DBUS_PATH_SECRET_AGENT = '/org/freedesktop/NetworkManager/SecretAgent';
  NM_DBUS_INTERFACE_DNS_MANAGER = 'org.freedesktop.NetworkManager.DnsManager';
  NM_DBUS_PATH_DNS_MANAGER = '/org/freedesktop/NetworkManager/DnsManager';

type
  PNMVersionInfoCapability = ^TNMVersionInfoCapability;
  TNMVersionInfoCapability = longint;

const
  _NM_VERSION_INFO_CAPABILITY_UNUSED = $7FFFFFFF;

type
  PNMCapability = ^TNMCapability;
  TNMCapability = longint;

const
  NM_CAPABILITY_TEAM = 1;
  NM_CAPABILITY_OVS = 2;

type
  PNMState = ^TNMState;
  TNMState = longint;

const
  NM_STATE_UNKNOWN = 0;
  NM_STATE_ASLEEP = 10;
  NM_STATE_DISCONNECTED = 20;
  NM_STATE_DISCONNECTING = 30;
  NM_STATE_CONNECTING = 40;
  NM_STATE_CONNECTED_LOCAL = 50;
  NM_STATE_CONNECTED_SITE = 60;
  NM_STATE_CONNECTED_GLOBAL = 70;

type
  PNMConnectivityState = ^TNMConnectivityState;
  TNMConnectivityState = longint;

const
  NM_CONNECTIVITY_UNKNOWN = 0;
  NM_CONNECTIVITY_NONE = 1;
  NM_CONNECTIVITY_PORTAL = 2;
  NM_CONNECTIVITY_LIMITED = 3;
  NM_CONNECTIVITY_FULL = 4;

type
  PNMDeviceType = ^TNMDeviceType;
  TNMDeviceType = longint;

const
  NM_DEVICE_TYPE_UNKNOWN = 0;
  NM_DEVICE_TYPE_ETHERNET = 1;
  NM_DEVICE_TYPE_WIFI = 2;
  NM_DEVICE_TYPE_UNUSED1 = 3;
  NM_DEVICE_TYPE_UNUSED2 = 4;
  NM_DEVICE_TYPE_BT = 5;
  NM_DEVICE_TYPE_OLPC_MESH = 6;
  NM_DEVICE_TYPE_WIMAX = 7;
  NM_DEVICE_TYPE_MODEM = 8;
  NM_DEVICE_TYPE_INFINIBAND = 9;
  NM_DEVICE_TYPE_BOND = 10;
  NM_DEVICE_TYPE_VLAN = 11;
  NM_DEVICE_TYPE_ADSL = 12;
  NM_DEVICE_TYPE_BRIDGE = 13;
  NM_DEVICE_TYPE_GENERIC = 14;
  NM_DEVICE_TYPE_TEAM = 15;
  NM_DEVICE_TYPE_TUN = 16;
  NM_DEVICE_TYPE_IP_TUNNEL = 17;
  NM_DEVICE_TYPE_MACVLAN = 18;
  NM_DEVICE_TYPE_VXLAN = 19;
  NM_DEVICE_TYPE_VETH = 20;
  NM_DEVICE_TYPE_MACSEC = 21;
  NM_DEVICE_TYPE_DUMMY = 22;
  NM_DEVICE_TYPE_PPP = 23;
  NM_DEVICE_TYPE_OVS_INTERFACE = 24;
  NM_DEVICE_TYPE_OVS_PORT = 25;
  NM_DEVICE_TYPE_OVS_BRIDGE = 26;
  NM_DEVICE_TYPE_WPAN = 27;
  NM_DEVICE_TYPE_6LOWPAN = 28;
  NM_DEVICE_TYPE_WIREGUARD = 29;
  NM_DEVICE_TYPE_WIFI_P2P = 30;
  NM_DEVICE_TYPE_VRF = 31;
  NM_DEVICE_TYPE_LOOPBACK = 32;
  NM_DEVICE_TYPE_HSR = 33;

type
  PNMDeviceCapabilities = ^TNMDeviceCapabilities;
  TNMDeviceCapabilities = longint;

const
  NM_DEVICE_CAP_NONE = $00000000;
  NM_DEVICE_CAP_NM_SUPPORTED = $00000001;
  NM_DEVICE_CAP_CARRIER_DETECT = $00000002;
  NM_DEVICE_CAP_IS_SOFTWARE = $00000004;
  NM_DEVICE_CAP_SRIOV = $00000008;

type
  PNMDeviceWifiCapabilities = ^TNMDeviceWifiCapabilities;
  TNMDeviceWifiCapabilities = longint;

const
  NM_WIFI_DEVICE_CAP_NONE = $00000000;
  NM_WIFI_DEVICE_CAP_CIPHER_WEP40 = $00000001;
  NM_WIFI_DEVICE_CAP_CIPHER_WEP104 = $00000002;
  NM_WIFI_DEVICE_CAP_CIPHER_TKIP = $00000004;
  NM_WIFI_DEVICE_CAP_CIPHER_CCMP = $00000008;
  NM_WIFI_DEVICE_CAP_WPA = $00000010;
  NM_WIFI_DEVICE_CAP_RSN = $00000020;
  NM_WIFI_DEVICE_CAP_AP = $00000040;
  NM_WIFI_DEVICE_CAP_ADHOC = $00000080;
  NM_WIFI_DEVICE_CAP_FREQ_VALID = $00000100;
  NM_WIFI_DEVICE_CAP_FREQ_2GHZ = $00000200;
  NM_WIFI_DEVICE_CAP_FREQ_5GHZ = $00000400;
  NM_WIFI_DEVICE_CAP_FREQ_6GHZ = $00000800;
  NM_WIFI_DEVICE_CAP_MESH = $00001000;
  NM_WIFI_DEVICE_CAP_IBSS_RSN = $00002000;

type
  PNM80211ApFlags = ^TNM80211ApFlags;
  TNM80211ApFlags = longint;

const
  NM_802_11_AP_FLAGS_NONE = $00000000;
  NM_802_11_AP_FLAGS_PRIVACY = $00000001;
  NM_802_11_AP_FLAGS_WPS = $00000002;
  NM_802_11_AP_FLAGS_WPS_PBC = $00000004;
  NM_802_11_AP_FLAGS_WPS_PIN = $00000008;

type
  PNM80211ApSecurityFlags = ^TNM80211ApSecurityFlags;
  TNM80211ApSecurityFlags = longint;

const
  NM_802_11_AP_SEC_NONE = $00000000;
  NM_802_11_AP_SEC_PAIR_WEP40 = $00000001;
  NM_802_11_AP_SEC_PAIR_WEP104 = $00000002;
  NM_802_11_AP_SEC_PAIR_TKIP = $00000004;
  NM_802_11_AP_SEC_PAIR_CCMP = $00000008;
  NM_802_11_AP_SEC_GROUP_WEP40 = $00000010;
  NM_802_11_AP_SEC_GROUP_WEP104 = $00000020;
  NM_802_11_AP_SEC_GROUP_TKIP = $00000040;
  NM_802_11_AP_SEC_GROUP_CCMP = $00000080;
  NM_802_11_AP_SEC_KEY_MGMT_PSK = $00000100;
  NM_802_11_AP_SEC_KEY_MGMT_802_1X = $00000200;
  NM_802_11_AP_SEC_KEY_MGMT_SAE = $00000400;
  NM_802_11_AP_SEC_KEY_MGMT_OWE = $00000800;
  NM_802_11_AP_SEC_KEY_MGMT_OWE_TM = $00001000;
  NM_802_11_AP_SEC_KEY_MGMT_EAP_SUITE_B_192 = $00002000;

type
  PNM80211Mode = ^TNM80211Mode;
  TNM80211Mode = longint;

const
  NM_802_11_MODE_UNKNOWN = 0;
  NM_802_11_MODE_ADHOC = 1;
  NM_802_11_MODE_INFRA = 2;
  NM_802_11_MODE_AP = 3;
  NM_802_11_MODE_MESH = 4;

type
  PNMBluetoothCapabilities = ^TNMBluetoothCapabilities;
  TNMBluetoothCapabilities = longint;

const
  NM_BT_CAPABILITY_NONE = $00000000;
  NM_BT_CAPABILITY_DUN = $00000001;
  NM_BT_CAPABILITY_NAP = $00000002;

type
  PNMDeviceModemCapabilities = ^TNMDeviceModemCapabilities;
  TNMDeviceModemCapabilities = longint;

const
  NM_DEVICE_MODEM_CAPABILITY_NONE = $00000000;
  NM_DEVICE_MODEM_CAPABILITY_POTS = $00000001;
  NM_DEVICE_MODEM_CAPABILITY_CDMA_EVDO = $00000002;
  NM_DEVICE_MODEM_CAPABILITY_GSM_UMTS = $00000004;
  NM_DEVICE_MODEM_CAPABILITY_LTE = $00000008;
  NM_DEVICE_MODEM_CAPABILITY_5GNR = $00000040;

type
  PNMWimaxNspNetworkType = ^TNMWimaxNspNetworkType;
  TNMWimaxNspNetworkType = longint;

const
  NM_WIMAX_NSP_NETWORK_TYPE_UNKNOWN = 0;
  NM_WIMAX_NSP_NETWORK_TYPE_HOME = 1;
  NM_WIMAX_NSP_NETWORK_TYPE_PARTNER = 2;
  NM_WIMAX_NSP_NETWORK_TYPE_ROAMING_PARTNER = 3;

type
  PNMDeviceState = ^TNMDeviceState;
  TNMDeviceState = longint;

const
  NM_DEVICE_STATE_UNKNOWN = 0;
  NM_DEVICE_STATE_UNMANAGED = 10;
  NM_DEVICE_STATE_UNAVAILABLE = 20;
  NM_DEVICE_STATE_DISCONNECTED = 30;
  NM_DEVICE_STATE_PREPARE = 40;
  NM_DEVICE_STATE_CONFIG = 50;
  NM_DEVICE_STATE_NEED_AUTH = 60;
  NM_DEVICE_STATE_IP_CONFIG = 70;
  NM_DEVICE_STATE_IP_CHECK = 80;
  NM_DEVICE_STATE_SECONDARIES = 90;
  NM_DEVICE_STATE_ACTIVATED = 100;
  NM_DEVICE_STATE_DEACTIVATING = 110;
  NM_DEVICE_STATE_FAILED = 120;

type
  PNMDeviceStateReason = ^TNMDeviceStateReason;
  TNMDeviceStateReason = longint;

const
  NM_DEVICE_STATE_REASON_NONE = 0;
  NM_DEVICE_STATE_REASON_UNKNOWN = 1;
  NM_DEVICE_STATE_REASON_NOW_MANAGED = 2;
  NM_DEVICE_STATE_REASON_NOW_UNMANAGED = 3;
  NM_DEVICE_STATE_REASON_CONFIG_FAILED = 4;
  NM_DEVICE_STATE_REASON_IP_CONFIG_UNAVAILABLE = 5;
  NM_DEVICE_STATE_REASON_IP_CONFIG_EXPIRED = 6;
  NM_DEVICE_STATE_REASON_NO_SECRETS = 7;
  NM_DEVICE_STATE_REASON_SUPPLICANT_DISCONNECT = 8;
  NM_DEVICE_STATE_REASON_SUPPLICANT_CONFIG_FAILED = 9;
  NM_DEVICE_STATE_REASON_SUPPLICANT_FAILED = 10;
  NM_DEVICE_STATE_REASON_SUPPLICANT_TIMEOUT = 11;
  NM_DEVICE_STATE_REASON_PPP_START_FAILED = 12;
  NM_DEVICE_STATE_REASON_PPP_DISCONNECT = 13;
  NM_DEVICE_STATE_REASON_PPP_FAILED = 14;
  NM_DEVICE_STATE_REASON_DHCP_START_FAILED = 15;
  NM_DEVICE_STATE_REASON_DHCP_ERROR = 16;
  NM_DEVICE_STATE_REASON_DHCP_FAILED = 17;
  NM_DEVICE_STATE_REASON_SHARED_START_FAILED = 18;
  NM_DEVICE_STATE_REASON_SHARED_FAILED = 19;
  NM_DEVICE_STATE_REASON_AUTOIP_START_FAILED = 20;
  NM_DEVICE_STATE_REASON_AUTOIP_ERROR = 21;
  NM_DEVICE_STATE_REASON_AUTOIP_FAILED = 22;
  NM_DEVICE_STATE_REASON_MODEM_BUSY = 23;
  NM_DEVICE_STATE_REASON_MODEM_NO_DIAL_TONE = 24;
  NM_DEVICE_STATE_REASON_MODEM_NO_CARRIER = 25;
  NM_DEVICE_STATE_REASON_MODEM_DIAL_TIMEOUT = 26;
  NM_DEVICE_STATE_REASON_MODEM_DIAL_FAILED = 27;
  NM_DEVICE_STATE_REASON_MODEM_INIT_FAILED = 28;
  NM_DEVICE_STATE_REASON_GSM_APN_FAILED = 29;
  NM_DEVICE_STATE_REASON_GSM_REGISTRATION_NOT_SEARCHING = 30;
  NM_DEVICE_STATE_REASON_GSM_REGISTRATION_DENIED = 31;
  NM_DEVICE_STATE_REASON_GSM_REGISTRATION_TIMEOUT = 32;
  NM_DEVICE_STATE_REASON_GSM_REGISTRATION_FAILED = 33;
  NM_DEVICE_STATE_REASON_GSM_PIN_CHECK_FAILED = 34;
  NM_DEVICE_STATE_REASON_FIRMWARE_MISSING = 35;
  NM_DEVICE_STATE_REASON_REMOVED = 36;
  NM_DEVICE_STATE_REASON_SLEEPING = 37;
  NM_DEVICE_STATE_REASON_CONNECTION_REMOVED = 38;
  NM_DEVICE_STATE_REASON_USER_REQUESTED = 39;
  NM_DEVICE_STATE_REASON_CARRIER = 40;
  NM_DEVICE_STATE_REASON_CONNECTION_ASSUMED = 41;
  NM_DEVICE_STATE_REASON_SUPPLICANT_AVAILABLE = 42;
  NM_DEVICE_STATE_REASON_MODEM_NOT_FOUND = 43;
  NM_DEVICE_STATE_REASON_BT_FAILED = 44;
  NM_DEVICE_STATE_REASON_GSM_SIM_NOT_INSERTED = 45;
  NM_DEVICE_STATE_REASON_GSM_SIM_PIN_REQUIRED = 46;
  NM_DEVICE_STATE_REASON_GSM_SIM_PUK_REQUIRED = 47;
  NM_DEVICE_STATE_REASON_GSM_SIM_WRONG = 48;
  NM_DEVICE_STATE_REASON_INFINIBAND_MODE = 49;
  NM_DEVICE_STATE_REASON_DEPENDENCY_FAILED = 50;
  NM_DEVICE_STATE_REASON_BR2684_FAILED = 51;
  NM_DEVICE_STATE_REASON_MODEM_MANAGER_UNAVAILABLE = 52;
  NM_DEVICE_STATE_REASON_SSID_NOT_FOUND = 53;
  NM_DEVICE_STATE_REASON_SECONDARY_CONNECTION_FAILED = 54;
  NM_DEVICE_STATE_REASON_DCB_FCOE_FAILED = 55;
  NM_DEVICE_STATE_REASON_TEAMD_CONTROL_FAILED = 56;
  NM_DEVICE_STATE_REASON_MODEM_FAILED = 57;
  NM_DEVICE_STATE_REASON_MODEM_AVAILABLE = 58;
  NM_DEVICE_STATE_REASON_SIM_PIN_INCORRECT = 59;
  NM_DEVICE_STATE_REASON_NEW_ACTIVATION = 60;
  NM_DEVICE_STATE_REASON_PARENT_CHANGED = 61;
  NM_DEVICE_STATE_REASON_PARENT_MANAGED_CHANGED = 62;
  NM_DEVICE_STATE_REASON_OVSDB_FAILED = 63;
  NM_DEVICE_STATE_REASON_IP_ADDRESS_DUPLICATE = 64;
  NM_DEVICE_STATE_REASON_IP_METHOD_UNSUPPORTED = 65;
  NM_DEVICE_STATE_REASON_SRIOV_CONFIGURATION_FAILED = 66;
  NM_DEVICE_STATE_REASON_PEER_NOT_FOUND = 67;
  NM_DEVICE_STATE_REASON_DEVICE_HANDLER_FAILED = 68;

type
  PNMMetered = ^TNMMetered;
  TNMMetered = longint;

const
  NM_METERED_UNKNOWN = 0;
  NM_METERED_YES = 1;
  NM_METERED_NO = 2;
  NM_METERED_GUESS_YES = 3;
  NM_METERED_GUESS_NO = 4;

type
  PNMConnectionMultiConnect = ^TNMConnectionMultiConnect;
  TNMConnectionMultiConnect = longint;

const
  NM_CONNECTION_MULTI_CONNECT_DEFAULT = 0;
  NM_CONNECTION_MULTI_CONNECT_SINGLE = 1;
  NM_CONNECTION_MULTI_CONNECT_MANUAL_MULTIPLE = 2;
  NM_CONNECTION_MULTI_CONNECT_MULTIPLE = 3;

type
  PNMActiveConnectionState = ^TNMActiveConnectionState;
  TNMActiveConnectionState = longint;

const
  NM_ACTIVE_CONNECTION_STATE_UNKNOWN = 0;
  NM_ACTIVE_CONNECTION_STATE_ACTIVATING = 1;
  NM_ACTIVE_CONNECTION_STATE_ACTIVATED = 2;
  NM_ACTIVE_CONNECTION_STATE_DEACTIVATING = 3;
  NM_ACTIVE_CONNECTION_STATE_DEACTIVATED = 4;

type
  PNMActiveConnectionStateReason = ^TNMActiveConnectionStateReason;
  TNMActiveConnectionStateReason = longint;

const
  NM_ACTIVE_CONNECTION_STATE_REASON_UNKNOWN = 0;
  NM_ACTIVE_CONNECTION_STATE_REASON_NONE = 1;
  NM_ACTIVE_CONNECTION_STATE_REASON_USER_DISCONNECTED = 2;
  NM_ACTIVE_CONNECTION_STATE_REASON_DEVICE_DISCONNECTED = 3;
  NM_ACTIVE_CONNECTION_STATE_REASON_SERVICE_STOPPED = 4;
  NM_ACTIVE_CONNECTION_STATE_REASON_IP_CONFIG_INVALID = 5;
  NM_ACTIVE_CONNECTION_STATE_REASON_CONNECT_TIMEOUT = 6;
  NM_ACTIVE_CONNECTION_STATE_REASON_SERVICE_START_TIMEOUT = 7;
  NM_ACTIVE_CONNECTION_STATE_REASON_SERVICE_START_FAILED = 8;
  NM_ACTIVE_CONNECTION_STATE_REASON_NO_SECRETS = 9;
  NM_ACTIVE_CONNECTION_STATE_REASON_LOGIN_FAILED = 10;
  NM_ACTIVE_CONNECTION_STATE_REASON_CONNECTION_REMOVED = 11;
  NM_ACTIVE_CONNECTION_STATE_REASON_DEPENDENCY_FAILED = 12;
  NM_ACTIVE_CONNECTION_STATE_REASON_DEVICE_REALIZE_FAILED = 13;
  NM_ACTIVE_CONNECTION_STATE_REASON_DEVICE_REMOVED = 14;

type
  PNMSecretAgentGetSecretsFlags = ^TNMSecretAgentGetSecretsFlags;
  TNMSecretAgentGetSecretsFlags = longint;

const
  NM_SECRET_AGENT_GET_SECRETS_FLAG_NONE = $0;
  NM_SECRET_AGENT_GET_SECRETS_FLAG_ALLOW_INTERACTION = $1;
  NM_SECRET_AGENT_GET_SECRETS_FLAG_REQUEST_NEW = $2;
  NM_SECRET_AGENT_GET_SECRETS_FLAG_USER_REQUESTED = $4;
  NM_SECRET_AGENT_GET_SECRETS_FLAG_WPS_PBC_ACTIVE = $8;
  NM_SECRET_AGENT_GET_SECRETS_FLAG_ONLY_SYSTEM = $80000000;
  NM_SECRET_AGENT_GET_SECRETS_FLAG_NO_ERRORS = $40000000;

type
  PNMSecretAgentCapabilities = ^TNMSecretAgentCapabilities;
  TNMSecretAgentCapabilities = longint;

const
  NM_SECRET_AGENT_CAPABILITY_NONE = $0;
  NM_SECRET_AGENT_CAPABILITY_VPN_HINTS = $1;
  NM_SECRET_AGENT_CAPABILITY_LAST = NM_SECRET_AGENT_CAPABILITY_VPN_HINTS;

const
  NM_LLDP_ATTR_RAW = 'raw';
  NM_LLDP_ATTR_DESTINATION = 'destination';
  NM_LLDP_ATTR_CHASSIS_ID_TYPE = 'chassis-id-type';
  NM_LLDP_ATTR_CHASSIS_ID = 'chassis-id';
  NM_LLDP_ATTR_PORT_ID_TYPE = 'port-id-type';
  NM_LLDP_ATTR_PORT_ID = 'port-id';
  NM_LLDP_ATTR_PORT_DESCRIPTION = 'port-description';
  NM_LLDP_ATTR_SYSTEM_NAME = 'system-name';
  NM_LLDP_ATTR_SYSTEM_DESCRIPTION = 'system-description';
  NM_LLDP_ATTR_SYSTEM_CAPABILITIES = 'system-capabilities';
  NM_LLDP_ATTR_MANAGEMENT_ADDRESSES = 'management-addresses';
  NM_LLDP_ATTR_IEEE_802_1_PVID = 'ieee-802-1-pvid';
  NM_LLDP_ATTR_IEEE_802_1_VLANS = 'ieee-802-1-vlans';
  NM_LLDP_ATTR_IEEE_802_1_PPVIDS = 'ieee-802-1-ppvids';
  NM_LLDP_ATTR_IEEE_802_3_MAC_PHY_CONF = 'ieee-802-3-mac-phy-conf';
  NM_LLDP_ATTR_IEEE_802_3_POWER_VIA_MDI = 'ieee-802-3-power-via-mdi';
  NM_LLDP_ATTR_IEEE_802_3_MAX_FRAME_SIZE = 'ieee-802-3-max-frame-size';
  NM_LLDP_ATTR_MUD_URL = 'mud-url';
  NM_LLDP_ATTR_IEEE_802_1_VID = 'ieee-802-1-vid';
  NM_LLDP_ATTR_IEEE_802_1_VLAN_NAME = 'ieee-802-1-vlan-name';
  NM_LLDP_ATTR_IEEE_802_1_PPVID = 'ieee-802-1-ppvid';
  NM_LLDP_ATTR_IEEE_802_1_PPVID_FLAGS = 'ieee-802-1-ppvid-flags';
  NM_LLDP_DEST_NEAREST_BRIDGE = 'nearest-bridge';
  NM_LLDP_DEST_NEAREST_NON_TPMR_BRIDGE = 'nearest-non-tpmr-bridge';
  NM_LLDP_DEST_NEAREST_CUSTOMER_BRIDGE = 'nearest-customer-bridge';

type
  PNMIPTunnelMode = ^TNMIPTunnelMode;
  TNMIPTunnelMode = longint;

const
  NM_IP_TUNNEL_MODE_UNKNOWN = 0;
  NM_IP_TUNNEL_MODE_IPIP = 1;
  NM_IP_TUNNEL_MODE_GRE = 2;
  NM_IP_TUNNEL_MODE_SIT = 3;
  NM_IP_TUNNEL_MODE_ISATAP = 4;
  NM_IP_TUNNEL_MODE_VTI = 5;
  NM_IP_TUNNEL_MODE_IP6IP6 = 6;
  NM_IP_TUNNEL_MODE_IPIP6 = 7;
  NM_IP_TUNNEL_MODE_IP6GRE = 8;
  NM_IP_TUNNEL_MODE_VTI6 = 9;
  NM_IP_TUNNEL_MODE_GRETAP = 10;
  NM_IP_TUNNEL_MODE_IP6GRETAP = 11;

type
  PNMCheckpointCreateFlags = ^TNMCheckpointCreateFlags;
  TNMCheckpointCreateFlags = longint;

const
  NM_CHECKPOINT_CREATE_FLAG_NONE = 0;
  NM_CHECKPOINT_CREATE_FLAG_DESTROY_ALL = $01;
  NM_CHECKPOINT_CREATE_FLAG_DELETE_NEW_CONNECTIONS = $02;
  NM_CHECKPOINT_CREATE_FLAG_DISCONNECT_NEW_DEVICES = $04;
  NM_CHECKPOINT_CREATE_FLAG_ALLOW_OVERLAPPING = $08;
  NM_CHECKPOINT_CREATE_FLAG_NO_PRESERVE_EXTERNAL_PORTS = $10;

type
  PNMRollbackResult = ^TNMRollbackResult;
  TNMRollbackResult = longint;

const
  NM_ROLLBACK_RESULT_OK = 0;
  NM_ROLLBACK_RESULT_ERR_NO_DEVICE = 1;
  NM_ROLLBACK_RESULT_ERR_DEVICE_UNMANAGED = 2;
  NM_ROLLBACK_RESULT_ERR_FAILED = 3;

type
  PNMSettingsConnectionFlags = ^TNMSettingsConnectionFlags;
  TNMSettingsConnectionFlags = longint;

const
  NM_SETTINGS_CONNECTION_FLAG_NONE = 0;
  NM_SETTINGS_CONNECTION_FLAG_UNSAVED = $01;
  NM_SETTINGS_CONNECTION_FLAG_NM_GENERATED = $02;
  NM_SETTINGS_CONNECTION_FLAG_VOLATILE = $04;
  NM_SETTINGS_CONNECTION_FLAG_EXTERNAL = $08;

type
  PNMActivationStateFlags = ^TNMActivationStateFlags;
  TNMActivationStateFlags = longint;

const
  NM_ACTIVATION_STATE_FLAG_NONE = 0;
  NM_ACTIVATION_STATE_FLAG_IS_MASTER = $1;
  NM_ACTIVATION_STATE_FLAG_IS_SLAVE = $2;
  NM_ACTIVATION_STATE_FLAG_LAYER2_READY = $4;
  NM_ACTIVATION_STATE_FLAG_IP4_READY = $8;
  NM_ACTIVATION_STATE_FLAG_IP6_READY = $10;
  NM_ACTIVATION_STATE_FLAG_MASTER_HAS_SLAVES = $20;
  NM_ACTIVATION_STATE_FLAG_LIFETIME_BOUND_TO_PROFILE_VISIBILITY = $40;
  NM_ACTIVATION_STATE_FLAG_EXTERNAL = $80;

type
  PNMSettingsAddConnection2Flags = ^TNMSettingsAddConnection2Flags;
  TNMSettingsAddConnection2Flags = longint;

const
  NM_SETTINGS_ADD_CONNECTION2_FLAG_NONE = 0;
  NM_SETTINGS_ADD_CONNECTION2_FLAG_TO_DISK = $1;
  NM_SETTINGS_ADD_CONNECTION2_FLAG_IN_MEMORY = $2;
  NM_SETTINGS_ADD_CONNECTION2_FLAG_BLOCK_AUTOCONNECT = $20;

type
  PNMSettingsUpdate2Flags = ^TNMSettingsUpdate2Flags;
  TNMSettingsUpdate2Flags = longint;

const
  NM_SETTINGS_UPDATE2_FLAG_NONE = 0;
  NM_SETTINGS_UPDATE2_FLAG_TO_DISK = $1;
  NM_SETTINGS_UPDATE2_FLAG_IN_MEMORY = $2;
  NM_SETTINGS_UPDATE2_FLAG_IN_MEMORY_DETACHED = $4;
  NM_SETTINGS_UPDATE2_FLAG_IN_MEMORY_ONLY = $8;
  NM_SETTINGS_UPDATE2_FLAG_VOLATILE = $10;
  NM_SETTINGS_UPDATE2_FLAG_BLOCK_AUTOCONNECT = $20;
  NM_SETTINGS_UPDATE2_FLAG_NO_REAPPLY = $40;

type
  PNMDeviceReapplyFlags = ^TNMDeviceReapplyFlags;
  TNMDeviceReapplyFlags = longint;

const
  NM_DEVICE_REAPPLY_FLAGS_NONE = 0;
  NM_DEVICE_REAPPLY_FLAGS_PRESERVE_EXTERNAL_IP = $1;

type
  PNMTernary = ^TNMTernary;
  TNMTernary = longint;

const
  NM_TERNARY_DEFAULT = -(1);
  NM_TERNARY_FALSE = 0;
  NM_TERNARY_TRUE = 1;

type
  PNMManagerReloadFlags = ^TNMManagerReloadFlags;
  TNMManagerReloadFlags = longint;

const
  NM_MANAGER_RELOAD_FLAG_NONE = 0;
  NM_MANAGER_RELOAD_FLAG_CONF = $1;
  NM_MANAGER_RELOAD_FLAG_DNS_RC = $2;
  NM_MANAGER_RELOAD_FLAG_DNS_FULL = $4;
  NM_MANAGER_RELOAD_FLAG_ALL = $7;

type
  PNMDeviceInterfaceFlags = ^TNMDeviceInterfaceFlags;
  TNMDeviceInterfaceFlags = longint;

const
  NM_DEVICE_INTERFACE_FLAG_NONE = 0;
  NM_DEVICE_INTERFACE_FLAG_UP = $1;
  NM_DEVICE_INTERFACE_FLAG_LOWER_UP = $2;
  NM_DEVICE_INTERFACE_FLAG_PROMISC = $4;
  NM_DEVICE_INTERFACE_FLAG_CARRIER = $10000;
  NM_DEVICE_INTERFACE_FLAG_LLDP_CLIENT_ENABLED = $20000;

type
  PNMClientPermission = ^TNMClientPermission;
  TNMClientPermission = longint;

const
  NM_CLIENT_PERMISSION_NONE = 0;
  NM_CLIENT_PERMISSION_ENABLE_DISABLE_NETWORK = 1;
  NM_CLIENT_PERMISSION_ENABLE_DISABLE_WIFI = 2;
  NM_CLIENT_PERMISSION_ENABLE_DISABLE_WWAN = 3;
  NM_CLIENT_PERMISSION_ENABLE_DISABLE_WIMAX = 4;
  NM_CLIENT_PERMISSION_SLEEP_WAKE = 5;
  NM_CLIENT_PERMISSION_NETWORK_CONTROL = 6;
  NM_CLIENT_PERMISSION_WIFI_SHARE_PROTECTED = 7;
  NM_CLIENT_PERMISSION_WIFI_SHARE_OPEN = 8;
  NM_CLIENT_PERMISSION_SETTINGS_MODIFY_SYSTEM = 9;
  NM_CLIENT_PERMISSION_SETTINGS_MODIFY_OWN = 10;
  NM_CLIENT_PERMISSION_SETTINGS_MODIFY_HOSTNAME = 11;
  NM_CLIENT_PERMISSION_SETTINGS_MODIFY_GLOBAL_DNS = 12;
  NM_CLIENT_PERMISSION_RELOAD = 13;
  NM_CLIENT_PERMISSION_CHECKPOINT_ROLLBACK = 14;
  NM_CLIENT_PERMISSION_ENABLE_DISABLE_STATISTICS = 15;
  NM_CLIENT_PERMISSION_ENABLE_DISABLE_CONNECTIVITY_CHECK = 16;
  NM_CLIENT_PERMISSION_WIFI_SCAN = 17;
  NM_CLIENT_PERMISSION_LAST = 17;

type
  PNMClientPermissionResult = ^TNMClientPermissionResult;
  TNMClientPermissionResult = longint;

const
  NM_CLIENT_PERMISSION_RESULT_UNKNOWN = 0;
  NM_CLIENT_PERMISSION_RESULT_YES = 1;
  NM_CLIENT_PERMISSION_RESULT_AUTH = 2;
  NM_CLIENT_PERMISSION_RESULT_NO = 3;

type
  PNMRadioFlags = ^TNMRadioFlags;
  TNMRadioFlags = longint;

const
  NM_RADIO_FLAG_NONE = 0;
  NM_RADIO_FLAG_WLAN_AVAILABLE = $1;
  NM_RADIO_FLAG_WWAN_AVAILABLE = $2;

type
  PNMMptcpFlags = ^TNMMptcpFlags;
  TNMMptcpFlags = longint;

const
  NM_MPTCP_FLAGS_NONE = 0;
  NM_MPTCP_FLAGS_DISABLED = $1;
  NM_MPTCP_FLAGS_ENABLED = $2;
  NM_MPTCP_FLAGS_ALSO_WITHOUT_SYSCTL = $4;
  NM_MPTCP_FLAGS_ALSO_WITHOUT_DEFAULT_ROUTE = $8;
  NM_MPTCP_FLAGS_SIGNAL = $10;
  NM_MPTCP_FLAGS_SUBFLOW = $20;
  NM_MPTCP_FLAGS_BACKUP = $40;
  NM_MPTCP_FLAGS_FULLMESH = $80;

const
  NM_SECRET_TAG_VPN_MSG = 'x-vpn-message:';
  NM_SECRET_TAG_DYNAMIC_CHALLENGE = 'x-dynamic-challenge:';
  NM_SECRET_TAG_DYNAMIC_CHALLENGE_ECHO = 'x-dynamic-challenge-echo:';
  {$ENDIF read_enum}

  // === Konventiert am: 19-4-26 19:31:31 ===


implementation



end.
