unit nm_enum_types;

interface

uses
  fp_glib2, fp_nm;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
{ Generated by glib-mkenums. Do not edit  }
{$ifndef __NM_ENUM_TYPES_H__}
{$define __NM_ENUM_TYPES_H__}
{$include "nm-core-enum-types.h"}
{$include <glib-object.h>}

function nm_client_instance_flags_get_type:TGType;cdecl;external libnm;
{ was #define dname def_expr }
function NM_TYPE_CLIENT_INSTANCE_FLAGS : longint; { return type might be wrong }

function nm_client_error_get_type:TGType;cdecl;external libnm;
{ was #define dname def_expr }
function NM_TYPE_CLIENT_ERROR : longint; { return type might be wrong }

{$endif}
{ __NM_ENUM_TYPES_H__  }
{ Generated data ends here  }

// === Konventiert am: 19-4-26 19:29:13 ===


implementation


{ was #define dname def_expr }
function NM_TYPE_CLIENT_INSTANCE_FLAGS : longint; { return type might be wrong }
  begin
    NM_TYPE_CLIENT_INSTANCE_FLAGS:=nm_client_instance_flags_get_type;
  end;

{ was #define dname def_expr }
function NM_TYPE_CLIENT_ERROR : longint; { return type might be wrong }
  begin
    NM_TYPE_CLIENT_ERROR:=nm_client_error_get_type;
  end;


end.
