unit nm_vpn_dbus_interface;

{$DEFINE read_enum}{$DEFINE read_struct}{$DEFINE read_function}

interface

uses
  fp_glib2, fp_nm;

  {$IFDEF FPC}
  {$PACKRECORDS C}
  {$ENDIF}

  {$IFDEF read_enum}
const
  NM_DBUS_PATH_VPN = '/org/freedesktop/NetworkManager/VPN/Manager';
  NM_DBUS_INTERFACE_VPN = 'org.freedesktop.NetworkManager.VPN.Manager';
  NM_DBUS_PATH_VPN_CONNECTION = '/org/freedesktop/NetworkManager/VPN/Connection';
  NM_DBUS_INTERFACE_VPN_CONNECTION = 'org.freedesktop.NetworkManager.VPN.Connection';
  NM_VPN_DBUS_PLUGIN_PATH = '/org/freedesktop/NetworkManager/VPN/Plugin';
  NM_VPN_DBUS_PLUGIN_INTERFACE = 'org.freedesktop.NetworkManager.VPN.Plugin';

  NM_DBUS_NO_ACTIVE_VPN_CONNECTION = 'org.freedesktop.NetworkManager.VPNConnections.NoActiveVPNConnection';
  NM_DBUS_NO_VPN_CONNECTIONS = 'org.freedesktop.NetworkManager.VPNConnections.NoVPNConnections';
  NM_DBUS_INVALID_VPN_CONNECTION = 'org.freedesktop.NetworkManager.VPNConnections.InvalidVPNConnection';
  NM_DBUS_VPN_ERROR_PREFIX = 'org.freedesktop.NetworkManager.VPN.Error';
  NM_DBUS_VPN_STARTING_IN_PROGRESS = 'StartingInProgress';
  NM_DBUS_VPN_ALREADY_STARTED = 'AlreadyStarted';
  NM_DBUS_VPN_STOPPING_IN_PROGRESS = 'StoppingInProgress';
  NM_DBUS_VPN_ALREADY_STOPPED = 'AlreadyStopped';
  NM_DBUS_VPN_WRONG_STATE = 'WrongState';
  NM_DBUS_VPN_BAD_ARGUMENTS = 'BadArguments';
  NM_DBUS_VPN_INTERACTIVE_NOT_SUPPORTED = 'InteractiveNotSupported';

  NM_DBUS_VPN_SIGNAL_LOGIN_BANNER = 'LoginBanner';
  NM_DBUS_VPN_SIGNAL_LOGIN_FAILED = 'LoginFailed';
  NM_DBUS_VPN_SIGNAL_LAUNCH_FAILED = 'LaunchFailed';
  NM_DBUS_VPN_SIGNAL_CONNECT_FAILED = 'ConnectFailed';
  NM_DBUS_VPN_SIGNAL_VPN_CONFIG_BAD = 'VPNConfigBad';
  NM_DBUS_VPN_SIGNAL_IP_CONFIG_BAD = 'IPConfigBad';
  NM_DBUS_VPN_SIGNAL_STATE_CHANGE = 'StateChange';
  NM_DBUS_VPN_SIGNAL_IP4_CONFIG = 'IP4Config';

type
  PNMVpnServiceState = ^TNMVpnServiceState;
  TNMVpnServiceState = longint;

const
  NM_VPN_SERVICE_STATE_UNKNOWN = 0;
  NM_VPN_SERVICE_STATE_INIT = 1;
  NM_VPN_SERVICE_STATE_SHUTDOWN = 2;
  NM_VPN_SERVICE_STATE_STARTING = 3;
  NM_VPN_SERVICE_STATE_STARTED = 4;
  NM_VPN_SERVICE_STATE_STOPPING = 5;
  NM_VPN_SERVICE_STATE_STOPPED = 6;

type
  PNMVpnConnectionState = ^TNMVpnConnectionState;
  TNMVpnConnectionState = longint;

const
  NM_VPN_CONNECTION_STATE_UNKNOWN = 0;
  NM_VPN_CONNECTION_STATE_PREPARE = 1;
  NM_VPN_CONNECTION_STATE_NEED_AUTH = 2;
  NM_VPN_CONNECTION_STATE_CONNECT = 3;
  NM_VPN_CONNECTION_STATE_IP_CONFIG_GET = 4;
  NM_VPN_CONNECTION_STATE_ACTIVATED = 5;
  NM_VPN_CONNECTION_STATE_FAILED = 6;
  NM_VPN_CONNECTION_STATE_DISCONNECTED = 7;

type
  PNMVpnConnectionStateReason = ^TNMVpnConnectionStateReason;
  TNMVpnConnectionStateReason = longint;

const
  NM_VPN_CONNECTION_STATE_REASON_UNKNOWN = 0;
  NM_VPN_CONNECTION_STATE_REASON_NONE = 1;
  NM_VPN_CONNECTION_STATE_REASON_USER_DISCONNECTED = 2;
  NM_VPN_CONNECTION_STATE_REASON_DEVICE_DISCONNECTED = 3;
  NM_VPN_CONNECTION_STATE_REASON_SERVICE_STOPPED = 4;
  NM_VPN_CONNECTION_STATE_REASON_IP_CONFIG_INVALID = 5;
  NM_VPN_CONNECTION_STATE_REASON_CONNECT_TIMEOUT = 6;
  NM_VPN_CONNECTION_STATE_REASON_SERVICE_START_TIMEOUT = 7;
  NM_VPN_CONNECTION_STATE_REASON_SERVICE_START_FAILED = 8;
  NM_VPN_CONNECTION_STATE_REASON_NO_SECRETS = 9;
  NM_VPN_CONNECTION_STATE_REASON_LOGIN_FAILED = 10;
  NM_VPN_CONNECTION_STATE_REASON_CONNECTION_REMOVED = 11;

type
  PNMVpnPluginFailure = ^TNMVpnPluginFailure;
  TNMVpnPluginFailure = longint;

const
  NM_VPN_PLUGIN_FAILURE_LOGIN_FAILED = 0;
  NM_VPN_PLUGIN_FAILURE_CONNECT_FAILED = 1;
  NM_VPN_PLUGIN_FAILURE_BAD_IP_CONFIG = 2;

const
  NM_VPN_PLUGIN_CONFIG_TUNDEV = 'tundev';
  NM_VPN_PLUGIN_CONFIG_PROXY_PAC = 'pac';
  NM_VPN_PLUGIN_CONFIG_BANNER = 'banner';
  NM_VPN_PLUGIN_CONFIG_EXT_GATEWAY = 'gateway';
  NM_VPN_PLUGIN_CONFIG_MTU = 'mtu';
  NM_VPN_PLUGIN_CONFIG_HAS_IP4 = 'has-ip4';
  NM_VPN_PLUGIN_CONFIG_HAS_IP6 = 'has-ip6';
  NM_VPN_PLUGIN_CAN_PERSIST = 'can-persist';
  NM_VPN_PLUGIN_IP4_CONFIG_INT_GATEWAY = 'internal-gateway';
  NM_VPN_PLUGIN_IP4_CONFIG_ADDRESS = 'address';
  NM_VPN_PLUGIN_IP4_CONFIG_PTP = 'ptp';
  NM_VPN_PLUGIN_IP4_CONFIG_PREFIX = 'prefix';
  NM_VPN_PLUGIN_IP4_CONFIG_DNS = 'dns';
  NM_VPN_PLUGIN_IP4_CONFIG_NBNS = 'nbns';
  NM_VPN_PLUGIN_IP4_CONFIG_MSS = 'mss';
  NM_VPN_PLUGIN_IP4_CONFIG_DOMAIN = 'domain';
  NM_VPN_PLUGIN_IP4_CONFIG_DOMAINS = 'domains';
  NM_VPN_PLUGIN_IP4_CONFIG_ROUTES = 'routes';
  NM_VPN_PLUGIN_IP4_CONFIG_PRESERVE_ROUTES = 'preserve-routes';
  NM_VPN_PLUGIN_IP4_CONFIG_NEVER_DEFAULT = 'never-default';
  NM_VPN_PLUGIN_IP4_CONFIG_EXT_GATEWAY = NM_VPN_PLUGIN_CONFIG_EXT_GATEWAY;
  NM_VPN_PLUGIN_IP4_CONFIG_GATEWAY = NM_VPN_PLUGIN_IP4_CONFIG_EXT_GATEWAY;
  NM_VPN_PLUGIN_IP4_CONFIG_BANNER = NM_VPN_PLUGIN_CONFIG_BANNER;
  NM_VPN_PLUGIN_IP4_CONFIG_MTU = NM_VPN_PLUGIN_CONFIG_MTU;
  NM_VPN_PLUGIN_IP4_CONFIG_TUNDEV = NM_VPN_PLUGIN_CONFIG_TUNDEV;
  NM_VPN_PLUGIN_IP6_CONFIG_INT_GATEWAY = 'internal-gateway';
  NM_VPN_PLUGIN_IP6_CONFIG_ADDRESS = 'address';
  NM_VPN_PLUGIN_IP6_CONFIG_PTP = 'ptp';
  NM_VPN_PLUGIN_IP6_CONFIG_PREFIX = 'prefix';
  NM_VPN_PLUGIN_IP6_CONFIG_DNS = 'dns';
  NM_VPN_PLUGIN_IP6_CONFIG_MSS = 'mss';
  NM_VPN_PLUGIN_IP6_CONFIG_DOMAIN = 'domain';
  NM_VPN_PLUGIN_IP6_CONFIG_DOMAINS = 'domains';
  NM_VPN_PLUGIN_IP6_CONFIG_ROUTES = 'routes';
  NM_VPN_PLUGIN_IP6_CONFIG_PRESERVE_ROUTES = 'preserve-routes';
  NM_VPN_PLUGIN_IP6_CONFIG_NEVER_DEFAULT = 'never-default';
  {$ENDIF read_enum}

  // === Konventiert am: 19-4-26 19:20:00 ===


implementation



end.
