{$IFDEF read_interface}


{
 * Copyright © 2021, VideoLAN and librist authors
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-2-Clause
  }
{$ifndef LIBRIST_CONFIG_H}
{$define LIBRIST_CONFIG_H}

const
  HAVE_SRP_SUPPORT = 1;  
{$endif}
{ LIBRIST_CONFIG_H  }

// === Konventiert am: 15-8-26 19:17:07 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
