{$IFDEF read_interface}


procedure _shumate_marshal_VOID__DOUBLE_DOUBLE_BOXED(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libshumate;
procedure _shumate_marshal_VOID__UINT_UINT(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libshumate;
procedure _shumate_marshal_VOID__OBJECT_OBJECT(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libshumate;

// === Konventiert am: 6-5-26 15:48:57 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
