unit gstenumtypes;

interface

uses
  fp_glib2, fp_gst;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
(** unsupported pragma#pragma once*)
{$include <glib-object.h>}
{$include <gst/gstconfig.h>}
{ enumerations from "gstallocator.h"  }

function gst_allocator_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_ALLOCATOR_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstbin.h"  }
function gst_bin_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_BIN_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstbuffer.h"  }
function gst_buffer_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_BUFFER_FLAGS : longint; { return type might be wrong }

function gst_buffer_copy_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_BUFFER_COPY_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstbufferpool.h"  }
function gst_buffer_pool_acquire_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_BUFFER_POOL_ACQUIRE_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstbus.h"  }
function gst_bus_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_BUS_FLAGS : longint; { return type might be wrong }

function gst_bus_sync_reply_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_BUS_SYNC_REPLY : longint; { return type might be wrong }

{ enumerations from "gstcaps.h"  }
function gst_caps_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_CAPS_FLAGS : longint; { return type might be wrong }

function gst_caps_intersect_mode_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_CAPS_INTERSECT_MODE : longint; { return type might be wrong }

{ enumerations from "gstclock.h"  }
function gst_clock_return_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_CLOCK_RETURN : longint; { return type might be wrong }

function gst_clock_entry_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_CLOCK_ENTRY_TYPE : longint; { return type might be wrong }

function gst_clock_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_CLOCK_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstdebugutils.h"  }
function gst_debug_graph_details_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_DEBUG_GRAPH_DETAILS : longint; { return type might be wrong }

{ enumerations from "gstelement.h"  }
function gst_state_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_STATE : longint; { return type might be wrong }

function gst_state_change_return_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_STATE_CHANGE_RETURN : longint; { return type might be wrong }

function gst_state_change_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_STATE_CHANGE : longint; { return type might be wrong }

function gst_element_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_ELEMENT_FLAGS : longint; { return type might be wrong }

{ enumerations from "gsterror.h"  }
function gst_core_error_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_CORE_ERROR : longint; { return type might be wrong }

function gst_library_error_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_LIBRARY_ERROR : longint; { return type might be wrong }

function gst_resource_error_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_RESOURCE_ERROR : longint; { return type might be wrong }

function gst_stream_error_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_STREAM_ERROR : longint; { return type might be wrong }

{ enumerations from "gstevent.h"  }
function gst_event_type_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_EVENT_TYPE_FLAGS : longint; { return type might be wrong }

function gst_event_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_EVENT_TYPE : longint; { return type might be wrong }

function gst_stream_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_STREAM_FLAGS : longint; { return type might be wrong }

function gst_qos_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_QOS_TYPE : longint; { return type might be wrong }

function gst_gap_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_GAP_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstformat.h"  }
function gst_format_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_FORMAT : longint; { return type might be wrong }

{ enumerations from "gstinfo.h"  }
function gst_debug_level_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_DEBUG_LEVEL : longint; { return type might be wrong }

function gst_debug_color_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_DEBUG_COLOR_FLAGS : longint; { return type might be wrong }

function gst_stack_trace_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_STACK_TRACE_FLAGS : longint; { return type might be wrong }

function gst_debug_color_mode_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_DEBUG_COLOR_MODE : longint; { return type might be wrong }

function gst_log_context_hash_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_LOG_CONTEXT_HASH_FLAGS : longint; { return type might be wrong }

function gst_log_context_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_LOG_CONTEXT_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstiterator.h"  }
function gst_iterator_result_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_ITERATOR_RESULT : longint; { return type might be wrong }

function gst_iterator_item_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_ITERATOR_ITEM : longint; { return type might be wrong }

{ enumerations from "gstmemory.h"  }
function gst_memory_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_MEMORY_FLAGS : longint; { return type might be wrong }

function gst_map_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_MAP_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstmessage.h"  }
function gst_message_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_MESSAGE_TYPE : longint; { return type might be wrong }

function gst_structure_change_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_STRUCTURE_CHANGE_TYPE : longint; { return type might be wrong }

function gst_stream_status_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_STREAM_STATUS_TYPE : longint; { return type might be wrong }

function gst_progress_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PROGRESS_TYPE : longint; { return type might be wrong }

{ enumerations from "gstmeta.h"  }
function gst_meta_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_META_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstminiobject.h"  }
function gst_mini_object_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_MINI_OBJECT_FLAGS : longint; { return type might be wrong }

function gst_lock_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_LOCK_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstobject.h"  }
function gst_object_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_OBJECT_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstpad.h"  }
function gst_pad_direction_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PAD_DIRECTION : longint; { return type might be wrong }

function gst_pad_mode_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PAD_MODE : longint; { return type might be wrong }

function gst_pad_link_return_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PAD_LINK_RETURN : longint; { return type might be wrong }

function gst_flow_return_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_FLOW_RETURN : longint; { return type might be wrong }

function gst_pad_link_check_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PAD_LINK_CHECK : longint; { return type might be wrong }

function gst_pad_probe_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PAD_PROBE_TYPE : longint; { return type might be wrong }

function gst_pad_probe_return_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PAD_PROBE_RETURN : longint; { return type might be wrong }

function gst_pad_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PAD_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstpadtemplate.h"  }
function gst_pad_presence_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PAD_PRESENCE : longint; { return type might be wrong }

function gst_pad_template_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PAD_TEMPLATE_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstparse.h"  }
function gst_parse_error_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PARSE_ERROR : longint; { return type might be wrong }

function gst_parse_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PARSE_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstpipeline.h"  }
function gst_pipeline_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PIPELINE_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstplugin.h"  }
function gst_plugin_error_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PLUGIN_ERROR : longint; { return type might be wrong }

function gst_plugin_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PLUGIN_FLAGS : longint; { return type might be wrong }

function gst_plugin_dependency_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PLUGIN_DEPENDENCY_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstpluginfeature.h"  }
function gst_rank_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_RANK : longint; { return type might be wrong }

{ enumerations from "gstpromise.h"  }
function gst_promise_result_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PROMISE_RESULT : longint; { return type might be wrong }

{ enumerations from "gstquery.h"  }
function gst_query_type_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_QUERY_TYPE_FLAGS : longint; { return type might be wrong }

function gst_query_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_QUERY_TYPE : longint; { return type might be wrong }

function gst_buffering_mode_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_BUFFERING_MODE : longint; { return type might be wrong }

function gst_scheduling_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_SCHEDULING_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstsegment.h"  }
function gst_seek_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_SEEK_TYPE : longint; { return type might be wrong }

function gst_seek_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_SEEK_FLAGS : longint; { return type might be wrong }

function gst_segment_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_SEGMENT_FLAGS : longint; { return type might be wrong }

{ enumerations from "gststreams.h"  }
function gst_stream_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_STREAM_TYPE : longint; { return type might be wrong }

{ enumerations from "gststructure.h"  }
function gst_serialize_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_SERIALIZE_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstsystemclock.h"  }
function gst_clock_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_CLOCK_TYPE : longint; { return type might be wrong }

{ enumerations from "gsttaglist.h"  }
function gst_tag_merge_mode_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_TAG_MERGE_MODE : longint; { return type might be wrong }

function gst_tag_flag_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_TAG_FLAG : longint; { return type might be wrong }

function gst_tag_scope_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_TAG_SCOPE : longint; { return type might be wrong }

{ enumerations from "gsttask.h"  }
function gst_task_state_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_TASK_STATE : longint; { return type might be wrong }

{ enumerations from "gsttoc.h"  }
function gst_toc_scope_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_TOC_SCOPE : longint; { return type might be wrong }

function gst_toc_entry_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_TOC_ENTRY_TYPE : longint; { return type might be wrong }

function gst_toc_loop_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_TOC_LOOP_TYPE : longint; { return type might be wrong }

{ enumerations from "gsttracerrecord.h"  }
function gst_tracer_value_scope_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_TRACER_VALUE_SCOPE : longint; { return type might be wrong }

function gst_tracer_value_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_TRACER_VALUE_FLAGS : longint; { return type might be wrong }

{ enumerations from "gsttypefind.h"  }
function gst_type_find_probability_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_TYPE_FIND_PROBABILITY : longint; { return type might be wrong }

{ enumerations from "gsturi.h"  }
function gst_uri_error_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_URI_ERROR : longint; { return type might be wrong }

function gst_uri_type_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_URI_TYPE : longint; { return type might be wrong }

{ enumerations from "gstutils.h"  }
function gst_search_mode_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_SEARCH_MODE : longint; { return type might be wrong }

function gst_plugin_api_flags_get_type:TGType;cdecl;external libgstreamer;
{ was #define dname def_expr }
function GST_TYPE_PLUGIN_API_FLAGS : longint; { return type might be wrong }

{ Generated data ends here  }

// === Konventiert am: 11-7-26 10:58:24 ===


implementation


{ was #define dname def_expr }
function GST_TYPE_ALLOCATOR_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_ALLOCATOR_FLAGS:=gst_allocator_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_BIN_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_BIN_FLAGS:=gst_bin_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_BUFFER_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_BUFFER_FLAGS:=gst_buffer_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_BUFFER_COPY_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_BUFFER_COPY_FLAGS:=gst_buffer_copy_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_BUFFER_POOL_ACQUIRE_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_BUFFER_POOL_ACQUIRE_FLAGS:=gst_buffer_pool_acquire_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_BUS_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_BUS_FLAGS:=gst_bus_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_BUS_SYNC_REPLY : longint; { return type might be wrong }
  begin
    GST_TYPE_BUS_SYNC_REPLY:=gst_bus_sync_reply_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_CAPS_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_CAPS_FLAGS:=gst_caps_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_CAPS_INTERSECT_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_CAPS_INTERSECT_MODE:=gst_caps_intersect_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_CLOCK_RETURN : longint; { return type might be wrong }
  begin
    GST_TYPE_CLOCK_RETURN:=gst_clock_return_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_CLOCK_ENTRY_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_CLOCK_ENTRY_TYPE:=gst_clock_entry_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_CLOCK_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_CLOCK_FLAGS:=gst_clock_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_DEBUG_GRAPH_DETAILS : longint; { return type might be wrong }
  begin
    GST_TYPE_DEBUG_GRAPH_DETAILS:=gst_debug_graph_details_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_STATE : longint; { return type might be wrong }
  begin
    GST_TYPE_STATE:=gst_state_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_STATE_CHANGE_RETURN : longint; { return type might be wrong }
  begin
    GST_TYPE_STATE_CHANGE_RETURN:=gst_state_change_return_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_STATE_CHANGE : longint; { return type might be wrong }
  begin
    GST_TYPE_STATE_CHANGE:=gst_state_change_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_ELEMENT_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_ELEMENT_FLAGS:=gst_element_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_CORE_ERROR : longint; { return type might be wrong }
  begin
    GST_TYPE_CORE_ERROR:=gst_core_error_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_LIBRARY_ERROR : longint; { return type might be wrong }
  begin
    GST_TYPE_LIBRARY_ERROR:=gst_library_error_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_RESOURCE_ERROR : longint; { return type might be wrong }
  begin
    GST_TYPE_RESOURCE_ERROR:=gst_resource_error_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_STREAM_ERROR : longint; { return type might be wrong }
  begin
    GST_TYPE_STREAM_ERROR:=gst_stream_error_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_EVENT_TYPE_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_EVENT_TYPE_FLAGS:=gst_event_type_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_EVENT_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_EVENT_TYPE:=gst_event_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_STREAM_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_STREAM_FLAGS:=gst_stream_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_QOS_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_QOS_TYPE:=gst_qos_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_GAP_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_GAP_FLAGS:=gst_gap_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_FORMAT : longint; { return type might be wrong }
  begin
    GST_TYPE_FORMAT:=gst_format_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_DEBUG_LEVEL : longint; { return type might be wrong }
  begin
    GST_TYPE_DEBUG_LEVEL:=gst_debug_level_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_DEBUG_COLOR_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_DEBUG_COLOR_FLAGS:=gst_debug_color_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_STACK_TRACE_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_STACK_TRACE_FLAGS:=gst_stack_trace_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_DEBUG_COLOR_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_DEBUG_COLOR_MODE:=gst_debug_color_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_LOG_CONTEXT_HASH_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_LOG_CONTEXT_HASH_FLAGS:=gst_log_context_hash_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_LOG_CONTEXT_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_LOG_CONTEXT_FLAGS:=gst_log_context_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_ITERATOR_RESULT : longint; { return type might be wrong }
  begin
    GST_TYPE_ITERATOR_RESULT:=gst_iterator_result_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_ITERATOR_ITEM : longint; { return type might be wrong }
  begin
    GST_TYPE_ITERATOR_ITEM:=gst_iterator_item_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_MEMORY_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_MEMORY_FLAGS:=gst_memory_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_MAP_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_MAP_FLAGS:=gst_map_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_MESSAGE_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_MESSAGE_TYPE:=gst_message_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_STRUCTURE_CHANGE_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_STRUCTURE_CHANGE_TYPE:=gst_structure_change_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_STREAM_STATUS_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_STREAM_STATUS_TYPE:=gst_stream_status_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PROGRESS_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_PROGRESS_TYPE:=gst_progress_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_META_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_META_FLAGS:=gst_meta_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_MINI_OBJECT_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_MINI_OBJECT_FLAGS:=gst_mini_object_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_LOCK_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_LOCK_FLAGS:=gst_lock_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_OBJECT_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_OBJECT_FLAGS:=gst_object_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PAD_DIRECTION : longint; { return type might be wrong }
  begin
    GST_TYPE_PAD_DIRECTION:=gst_pad_direction_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PAD_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_PAD_MODE:=gst_pad_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PAD_LINK_RETURN : longint; { return type might be wrong }
  begin
    GST_TYPE_PAD_LINK_RETURN:=gst_pad_link_return_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_FLOW_RETURN : longint; { return type might be wrong }
  begin
    GST_TYPE_FLOW_RETURN:=gst_flow_return_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PAD_LINK_CHECK : longint; { return type might be wrong }
  begin
    GST_TYPE_PAD_LINK_CHECK:=gst_pad_link_check_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PAD_PROBE_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_PAD_PROBE_TYPE:=gst_pad_probe_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PAD_PROBE_RETURN : longint; { return type might be wrong }
  begin
    GST_TYPE_PAD_PROBE_RETURN:=gst_pad_probe_return_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PAD_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_PAD_FLAGS:=gst_pad_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PAD_PRESENCE : longint; { return type might be wrong }
  begin
    GST_TYPE_PAD_PRESENCE:=gst_pad_presence_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PAD_TEMPLATE_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_PAD_TEMPLATE_FLAGS:=gst_pad_template_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PARSE_ERROR : longint; { return type might be wrong }
  begin
    GST_TYPE_PARSE_ERROR:=gst_parse_error_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PARSE_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_PARSE_FLAGS:=gst_parse_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PIPELINE_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_PIPELINE_FLAGS:=gst_pipeline_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PLUGIN_ERROR : longint; { return type might be wrong }
  begin
    GST_TYPE_PLUGIN_ERROR:=gst_plugin_error_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PLUGIN_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_PLUGIN_FLAGS:=gst_plugin_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PLUGIN_DEPENDENCY_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_PLUGIN_DEPENDENCY_FLAGS:=gst_plugin_dependency_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_RANK : longint; { return type might be wrong }
  begin
    GST_TYPE_RANK:=gst_rank_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PROMISE_RESULT : longint; { return type might be wrong }
  begin
    GST_TYPE_PROMISE_RESULT:=gst_promise_result_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_QUERY_TYPE_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_QUERY_TYPE_FLAGS:=gst_query_type_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_QUERY_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_QUERY_TYPE:=gst_query_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_BUFFERING_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_BUFFERING_MODE:=gst_buffering_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_SCHEDULING_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_SCHEDULING_FLAGS:=gst_scheduling_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_SEEK_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_SEEK_TYPE:=gst_seek_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_SEEK_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_SEEK_FLAGS:=gst_seek_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_SEGMENT_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_SEGMENT_FLAGS:=gst_segment_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_STREAM_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_STREAM_TYPE:=gst_stream_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_SERIALIZE_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_SERIALIZE_FLAGS:=gst_serialize_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_CLOCK_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_CLOCK_TYPE:=gst_clock_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_TAG_MERGE_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_TAG_MERGE_MODE:=gst_tag_merge_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_TAG_FLAG : longint; { return type might be wrong }
  begin
    GST_TYPE_TAG_FLAG:=gst_tag_flag_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_TAG_SCOPE : longint; { return type might be wrong }
  begin
    GST_TYPE_TAG_SCOPE:=gst_tag_scope_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_TASK_STATE : longint; { return type might be wrong }
  begin
    GST_TYPE_TASK_STATE:=gst_task_state_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_TOC_SCOPE : longint; { return type might be wrong }
  begin
    GST_TYPE_TOC_SCOPE:=gst_toc_scope_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_TOC_ENTRY_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_TOC_ENTRY_TYPE:=gst_toc_entry_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_TOC_LOOP_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_TOC_LOOP_TYPE:=gst_toc_loop_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_TRACER_VALUE_SCOPE : longint; { return type might be wrong }
  begin
    GST_TYPE_TRACER_VALUE_SCOPE:=gst_tracer_value_scope_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_TRACER_VALUE_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_TRACER_VALUE_FLAGS:=gst_tracer_value_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_TYPE_FIND_PROBABILITY : longint; { return type might be wrong }
  begin
    GST_TYPE_TYPE_FIND_PROBABILITY:=gst_type_find_probability_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_URI_ERROR : longint; { return type might be wrong }
  begin
    GST_TYPE_URI_ERROR:=gst_uri_error_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_URI_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_URI_TYPE:=gst_uri_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_SEARCH_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_SEARCH_MODE:=gst_search_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_PLUGIN_API_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_PLUGIN_API_FLAGS:=gst_plugin_api_flags_get_type;
  end;


end.
