
unit apriltag;
interface

{
  Automatically converted by H2Pas 1.0.0 from apriltag.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    apriltag.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

Type
Papriltag_detection  = ^apriltag_detection;
Papriltag_detection_t  = ^apriltag_detection_t;
Papriltag_detector  = ^apriltag_detector;
Papriltag_detector_t  = ^apriltag_detector_t;
Papriltag_family  = ^apriltag_family;
Papriltag_family_t  = ^apriltag_family_t;
Papriltag_quad_thresh_params  = ^apriltag_quad_thresh_params;
Pchar  = ^char;
Pimage_u8_t  = ^image_u8_t;
Pmatd_t  = ^matd_t;
Pquad  = ^quad;
Ptimeprofile_t  = ^timeprofile_t;
Puint32_t  = ^uint32_t;
Puint64_t  = ^uint64_t;
Pworkerpool_t  = ^workerpool_t;
Pzarray_t  = ^zarray_t;
{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ Copyright (C) 2013-2016, The Regents of The University of Michigan.
All rights reserved.
This software was developed in the APRIL Robotics Lab under the
direction of Edwin Olson, ebolson@umich.edu. This software may be
available under alternative licensing terms; contact the address above.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those
of the authors and should not be interpreted as representing official policies,
either expressed or implied, of the Regents of The University of Michigan.
 }
(** unsupported pragma#pragma once*)
{ C++ extern C conditionnal removed }
{$include <stdlib.h>}
{$include "common/matd.h"}
{$include "common/image_u8.h"}
{$include "common/zarray.h"}
{$include "common/workerpool.h"}
{$include "common/timeprofile.h"}
{$include "common/pthreads_cross.h"}

const
  APRILTAG_TASKS_PER_THREAD_TARGET = 10;  
{ corners }
{ H: tag coordinates ([-1,1] at the black corners) to pixels }
{ Hinv: pixels to tag }
type
  Pquad = ^Tquad;
  Tquad = record
      p : array[0..3] of array[0..1] of single;
      reversed_border : Tbool;
      H : Pmatd_t;
      Hinv : Pmatd_t;
    end;

{ Represents a tag family. Every tag belongs to a tag family. Tag }
{ families are generated by the Java tool }
{ april.tag.TagFamilyGenerator and can be converted to C using }
{ april.tag.TagToC. }
  Tapriltag_family = Tapriltag_family_t;
{ How many codes are there in this tag family? }
{ The codes in the family. }
{ The bit locations. }
{ minimum hamming distance between any two codes. (e.g. 36h11 => 11) }
{ a human-readable name, e.g., "tag36h11" }
{ some detector implementations may preprocess codes in order to }
{ accelerate decoding.  They put their data here. (Do not use the }
{ same apriltag_family instance in more than one implementation) }
  Papriltag_family = ^Tapriltag_family;
  Tapriltag_family = record
      ncodes : Tuint32_t;
      codes : Puint64_t;
      width_at_border : longint;
      total_width : longint;
      reversed_border : Tbool;
      nbits : Tuint32_t;
      bit_x : Puint32_t;
      bit_y : Puint32_t;
      h : Tuint32_t;
      name : Pchar;
      impl : pointer;
    end;

{ reject quads containing too few pixels }
{ how many corner candidates to consider when segmenting a group }
{ of pixels into a quad. }
{ Reject quads where pairs of edges have angles that are close to }
{ straight or close to 180 degrees. Zero means that no quads are }
{ rejected. (In radians). }
{ When fitting lines to the contours, what is the maximum mean }
{ squared error allowed?  This is useful in rejecting contours }
{ that are far from being quad shaped; rejecting these quads "early" }
{ saves expensive decoding processing. }
{ When we build our model of black & white pixels, we add an }
{ extra check that the white model must be (overall) brighter }
{ than the black model.  How much brighter? (in pixel values, }
{ [0,255]). . }
{ should the thresholded image be deglitched? Only useful for }
{ very noisy images }
  Papriltag_quad_thresh_params = ^Tapriltag_quad_thresh_params;
  Tapriltag_quad_thresh_params = record
      min_cluster_pixels : longint;
      max_nmaxima : longint;
      critical_rad : single;
      cos_critical_rad : single;
      max_line_fit_mse : single;
      min_white_black_diff : longint;
      deglitch : longint;
    end;

{ Represents a detector object. Upon creating a detector, all fields }
{ are set to reasonable values, but can be overridden by accessing }
{ these fields. }
  Tapriltag_detector = Tapriltag_detector_t;
{///////////////////////////////////////////////////////////// }
{ User-configurable parameters. }
{ How many threads should be used? }
{ detection of quads can be done on a lower-resolution image, }
{ improving speed at a cost of pose accuracy and a slight }
{ decrease in detection rate. Decoding the binary payload is }
{ still done at full resolution. . }
{ What Gaussian blur should be applied to the segmented image }
{ (used for quad detection?)  Parameter is the standard deviation }
{ in pixels.  Very noisy images benefit from non-zero values }
{ (e.g. 0.8). }
{ When true, the edges of the each quad are adjusted to "snap }
{ to" strong gradients nearby. This is useful when decimation is }
{ employed, as it can increase the quality of the initial quad }
{ estimate substantially. Generally recommended to be on (true). }
{ }
{ Very computationally inexpensive. Option is ignored if }
{ quad_decimate = 1. }
{ How much sharpening should be done to decoded images? This }
{ can help decode small tags but may or may not help in odd }
{ lighting conditions or low light conditions. }
{ }
{ The default value is 0.25. }
{ When true, write a variety of debugging images to the }
{ current working directory at various stages through the }
{ detection process. (Somewhat slow). }
{///////////////////////////////////////////////////////////// }
{ Statistics relating to last processed frame }
{///////////////////////////////////////////////////////////// }
{ Internal variables below }
{ Not freed on apriltag_destroy; a tag family can be shared }
{ between multiple users. The user should ultimately destroy the }
{ tag family passed into the constructor. }
{ Used to manage multi-threading. }
{ Used for thread safety. }
  Papriltag_detector = ^Tapriltag_detector;
  Tapriltag_detector = record
      nthreads : longint;
      quad_decimate : single;
      quad_sigma : single;
      refine_edges : Tbool;
      decode_sharpening : Tdouble;
      debug : Tbool;
      qtp : Tapriltag_quad_thresh_params;
      tp : Ptimeprofile_t;
      nedges : Tuint32_t;
      nsegments : Tuint32_t;
      nquads : Tuint32_t;
      tag_families : Pzarray_t;
      wp : Pworkerpool_t;
      mutex : Tpthread_mutex_t;
    end;

{ Represents the detection of a tag. These are returned to the user }
{ and must be individually destroyed by the user. }
  Tapriltag_detection = Tapriltag_detection_t;
{ a pointer for convenience. not freed by apriltag_detection_destroy. }
{ The decoded ID of the tag }
{ How many error bits were corrected? Note: accepting large numbers of }
{ corrected errors leads to greatly increased false positive rates. }
{ NOTE: As of this implementation, the detector cannot detect tags with }
{ a hamming distance greater than 2. }
{ A measure of the quality of the binary decoding process: the }
{ average difference between the intensity of a data bit versus }
{ the decision threshold. Higher numbers roughly indicate better }
{ decodes. This is a reasonable measure of detection accuracy }
{ only for very small tags-- not effective for larger tags (where }
{ we could have sampled anywhere within a bit cell and still }
{ gotten a good detection.) }
{ The 3x3 homography matrix describing the projection from an }
{ "ideal" tag (with corners at (-1,1), (1,1), (1,-1), and (-1, }
{ -1)) to pixels in the image. This matrix will be freed by }
{ apriltag_detection_destroy. }
{ The center of the detection in image pixel coordinates. }
{ The corners of the tag in image pixel coordinates. These always }
{ wrap counter-clock wise around the tag. }
  Papriltag_detection = ^Tapriltag_detection;
  Tapriltag_detection = record
      family : Papriltag_family_t;
      id : longint;
      hamming : longint;
      decision_margin : single;
      H : Pmatd_t;
      c : array[0..1] of Tdouble;
      p : array[0..3] of array[0..1] of Tdouble;
    end;

{ don't forget to add a family! }

function apriltag_detector_create:Papriltag_detector_t;cdecl;external;
{ add a family to the apriltag detector. caller still "owns" the family. }
{ a single instance should only be provided to one apriltag detector instance. }
procedure apriltag_detector_add_family_bits(td:Papriltag_detector_t; fam:Papriltag_family_t; bits_corrected:longint);cdecl;external;
{ Tunable, but really, 2 is a good choice. Values of >=3 }
{ consume prohibitively large amounts of memory, and otherwise }
{ you want the largest value possible. }
{xxxxxxxxxxxx
static inline void apriltag_detector_add_family(apriltag_detector_t *td, apriltag_family_t *fam)

    apriltag_detector_add_family_bits(td, fam, 2);

 }
{ does not deallocate the family. }
procedure apriltag_detector_remove_family(td:Papriltag_detector_t; fam:Papriltag_family_t);cdecl;external;
{ unregister all families, but does not deallocate the underlying tag family objects. }
procedure apriltag_detector_clear_families(td:Papriltag_detector_t);cdecl;external;
{ Destroy the april tag detector (but not the underlying }
{ apriltag_family_t used to initialize it.) }
procedure apriltag_detector_destroy(td:Papriltag_detector_t);cdecl;external;
{ Detect tags from an image and return an array of }
{ apriltag_detection_t*. You can use apriltag_detections_destroy to }
{ free the array and the detections it contains, or call }
{ _detection_destroy and zarray_destroy yourself. }
function apriltag_detector_detect(td:Papriltag_detector_t; im_orig:Pimage_u8_t):Pzarray_t;cdecl;external;
{ Call this method on each of the tags returned by apriltag_detector_detect }
procedure apriltag_detection_destroy(det:Papriltag_detection_t);cdecl;external;
{ destroys the array AND the detections within it. }
procedure apriltag_detections_destroy(detections:Pzarray_t);cdecl;external;
{ Renders the apriltag. }
{ Caller is responsible for calling image_u8_destroy on the image }
function apriltag_to_image(fam:Papriltag_family_t; idx:longint):Pimage_u8_t;cdecl;external;
{ C++ end of extern C conditionnal removed }

implementation


end.
