unit fp_colord_session;

interface

const
  CD_SESSION_DBUS_SERVICE = 'org.freedesktop.ColorHelper';
  CD_SESSION_DBUS_PATH = '/';
  CD_SESSION_DBUS_INTERFACE = 'org.freedesktop.ColorHelper';
  CD_SESSION_DBUS_INTERFACE_DISPLAY = 'org.freedesktop.ColorHelper.Display';

type
  PCdSessionStatus = ^TCdSessionStatus;
  TCdSessionStatus = longint;

const
  CD_SESSION_STATUS_IDLE = 0;
  CD_SESSION_STATUS_WAITING_FOR_INTERACTION = 1;
  CD_SESSION_STATUS_RUNNING = 2;

type
  PCdSessionInteraction = ^TCdSessionInteraction;
  TCdSessionInteraction = longint;

const
  CD_SESSION_INTERACTION_ATTACH_TO_SCREEN = 0;
  CD_SESSION_INTERACTION_MOVE_TO_CALIBRATION = 1;
  CD_SESSION_INTERACTION_MOVE_TO_SURFACE = 2;
  CD_SESSION_INTERACTION_SHUT_LAPTOP_LID = 3;
  CD_SESSION_INTERACTION_NONE = 4;

type
  PCdSessionError = ^TCdSessionError;
  TCdSessionError = longint;

const
  CD_SESSION_ERROR_NONE = 0;
  CD_SESSION_ERROR_INTERNAL = 1;
  CD_SESSION_ERROR_FAILED_TO_FIND_DEVICE = 2;
  CD_SESSION_ERROR_FAILED_TO_FIND_SENSOR = 3;
  CD_SESSION_ERROR_FAILED_TO_FIND_TOOL = 4;
  CD_SESSION_ERROR_FAILED_TO_GENERATE_PROFILE = 5;
  CD_SESSION_ERROR_FAILED_TO_GET_WHITEPOINT = 6;
  CD_SESSION_ERROR_FAILED_TO_OPEN_PROFILE = 7;
  CD_SESSION_ERROR_FAILED_TO_SAVE_PROFILE = 8;
  CD_SESSION_ERROR_INVALID_VALUE = 9;
  CD_SESSION_ERROR_LAST = 10;


implementation

end.
