unit gmarkup;

interface

uses
  common_GLIB, gtypes;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ gmarkup.h - Simple XML-like string parser/writer
 *
 *  Copyright 2000 Red Hat, Inc.
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, see <http://www.gnu.org/licenses/>.
  }
{$ifndef __G_MARKUP_H__}
{$define __G_MARKUP_H__}
{$if !defined (__GLIB_H_INSIDE__) && !defined (GLIB_COMPILATION)}
{$error "Only <glib.h> can be included directly."}
{$endif}
{$include <stdarg.h>}
{$include <glib/gerror.h>}
{$include <glib/gslist.h>}
{*
 * GMarkupError:
 * @G_MARKUP_ERROR_BAD_UTF8: text being parsed was not valid UTF-8
 * @G_MARKUP_ERROR_EMPTY: document contained nothing, or only whitespace
 * @G_MARKUP_ERROR_PARSE: document was ill-formed
 * @G_MARKUP_ERROR_UNKNOWN_ELEMENT: error should be set by #GMarkupParser
 *     functions; element wasn't known
 * @G_MARKUP_ERROR_UNKNOWN_ATTRIBUTE: error should be set by #GMarkupParser
 *     functions; attribute wasn't known
 * @G_MARKUP_ERROR_INVALID_CONTENT: error should be set by #GMarkupParser
 *     functions; content was invalid
 * @G_MARKUP_ERROR_MISSING_ATTRIBUTE: error should be set by #GMarkupParser
 *     functions; a required attribute was missing
 *
 * Error codes returned by markup parsing.
  }
{ The following are primarily intended for specific GMarkupParser
   * implementations to set.
    }
type
  PGMarkupError = ^TGMarkupError;
  TGMarkupError =  Longint;
  Const
    G_MARKUP_ERROR_BAD_UTF8 = 0;
    G_MARKUP_ERROR_EMPTY = 1;
    G_MARKUP_ERROR_PARSE = 2;
    G_MARKUP_ERROR_UNKNOWN_ELEMENT = 3;
    G_MARKUP_ERROR_UNKNOWN_ATTRIBUTE = 4;
    G_MARKUP_ERROR_INVALID_CONTENT = 5;
    G_MARKUP_ERROR_MISSING_ATTRIBUTE = 6;
;
{*
 * G_MARKUP_ERROR:
 *
 * Error domain for markup parsing.
 * Errors in this domain will be from the #GMarkupError enumeration.
 * See #GError for information on error domains.
  }

{ was #define dname def_expr }
function G_MARKUP_ERROR : longint; { return type might be wrong }

function g_markup_error_quark:TGQuark;cdecl;external libglib2;
{*
 * GMarkupParseFlags:
 * @G_MARKUP_DEFAULT_FLAGS: No special behaviour. Since: 2.74
 * @G_MARKUP_DO_NOT_USE_THIS_UNSUPPORTED_FLAG: flag you should not use
 * @G_MARKUP_TREAT_CDATA_AS_TEXT: When this flag is set, CDATA marked
 *     sections are not passed literally to the @passthrough function of
 *     the parser. Instead, the content of the section (without the
 *     `<![CDATA[` and `]]>`) is
 *     passed to the @text function. This flag was added in GLib 2.12
 * @G_MARKUP_PREFIX_ERROR_POSITION: Normally errors caught by GMarkup
 *     itself have line/column information prefixed to them to let the
 *     caller know the location of the error. When this flag is set the
 *     location information is also prefixed to errors generated by the
 *     #GMarkupParser implementation functions
 * @G_MARKUP_IGNORE_QUALIFIED: Ignore (don't report) qualified
 *     attributes and tags, along with their contents.  A qualified
 *     attribute or tag is one that contains ':' in its name (ie: is in
 *     another namespace).  Since: 2.40.
 *
 * Flags that affect the behaviour of the parser.
  }
type
  PGMarkupParseFlags = ^TGMarkupParseFlags;
  TGMarkupParseFlags =  Longint;
  Const
    G_MARKUP_DEFAULT_FLAGS = 0;
    G_MARKUP_DO_NOT_USE_THIS_UNSUPPORTED_FLAG = 1 shl 0;
    G_MARKUP_TREAT_CDATA_AS_TEXT = 1 shl 1;
    G_MARKUP_PREFIX_ERROR_POSITION = 1 shl 2;
    G_MARKUP_IGNORE_QUALIFIED = 1 shl 3;
;
{*
 * GMarkupParseContext:
 *
 * A parse context is used to parse a stream of bytes that
 * you expect to contain marked-up text.
 *
 * See g_markup_parse_context_new(), #GMarkupParser, and so
 * on for more details.
  }
type
{*
 * GMarkupParser:
 * @start_element: Callback to invoke when the opening tag of an element
 *     is seen. The callback's @attribute_names and @attribute_values parameters
 *     are %NULL-terminated.
 * @end_element: Callback to invoke when the closing tag of an element
 *     is seen. Note that this is also called for empty tags like
 *     `<empty/>`.
 * @text: Callback to invoke when some text is seen (text is always
 *     inside an element). Note that the text of an element may be spread
 *     over multiple calls of this function. If the
 *     %G_MARKUP_TREAT_CDATA_AS_TEXT flag is set, this function is also
 *     called for the content of CDATA marked sections.
 * @passthrough: Callback to invoke for comments, processing instructions
 *     and doctype declarations; if you're re-writing the parsed document,
 *     write the passthrough text back out in the same position. If the
 *     %G_MARKUP_TREAT_CDATA_AS_TEXT flag is not set, this function is also
 *     called for CDATA marked sections.
 * @error: Callback to invoke when an error occurs.
 *
 * Any of the fields in #GMarkupParser can be %NULL, in which case they
 * will be ignored. Except for the @error function, any of these callbacks
 * can set an error; in particular the %G_MARKUP_ERROR_UNKNOWN_ELEMENT,
 * %G_MARKUP_ERROR_UNKNOWN_ATTRIBUTE, and %G_MARKUP_ERROR_INVALID_CONTENT
 * errors are intended to be set from these callbacks. If you set an error
 * from a callback, g_markup_parse_context_parse() will report that error
 * back to its caller.
 *
 * Refer to the [GMarkup](../glib/markup.html) documentation to understand
 * the scope and limitations of `GMarkupParser`. In particular, it is not a
 * full XML parser and it must not be used to process untrusted data.
  }
{ Called for open tags <foo bar="baz">  }
{ Called for close tags </foo>  }
{ Called for character data  }
{ text is not nul-terminated  }
{ Called for strings that should be re-saved verbatim in this same
   * position, but are not otherwise interpretable.  At the moment
   * this includes comments and processing instructions.
    }
{ text is not nul-terminated.  }
{ Called on error, including one set by other
   * methods in the vtable. The GError should not be freed.
    }
  PGMarkupParser = ^TGMarkupParser;
  TGMarkupParser = record
      start_element : procedure (context:PGMarkupParseContext; element_name:Pgchar; attribute_names:PPgchar; attribute_values:PPgchar; user_data:Tgpointer; 
                    error:PPGError);cdecl;
      end_element : procedure (context:PGMarkupParseContext; element_name:Pgchar; user_data:Tgpointer; error:PPGError);cdecl;
      text : procedure (context:PGMarkupParseContext; text:Pgchar; text_len:Tgsize; user_data:Tgpointer; error:PPGError);cdecl;
      passthrough : procedure (context:PGMarkupParseContext; passthrough_text:Pgchar; text_len:Tgsize; user_data:Tgpointer; error:PPGError);cdecl;
      error : procedure (context:PGMarkupParseContext; error:PGError; user_data:Tgpointer);cdecl;
    end;


function g_markup_parse_context_new(parser:PGMarkupParser; flags:TGMarkupParseFlags; user_data:Tgpointer; user_data_dnotify:TGDestroyNotify):PGMarkupParseContext;cdecl;external libglib2;
function g_markup_parse_context_ref(context:PGMarkupParseContext):PGMarkupParseContext;cdecl;external libglib2;
procedure g_markup_parse_context_unref(context:PGMarkupParseContext);cdecl;external libglib2;
procedure g_markup_parse_context_free(context:PGMarkupParseContext);cdecl;external libglib2;
function g_markup_parse_context_parse(context:PGMarkupParseContext; text:Pgchar; text_len:Tgssize; error:PPGError):Tgboolean;cdecl;external libglib2;
procedure g_markup_parse_context_push(context:PGMarkupParseContext; parser:PGMarkupParser; user_data:Tgpointer);cdecl;external libglib2;
function g_markup_parse_context_pop(context:PGMarkupParseContext):Tgpointer;cdecl;external libglib2;
function g_markup_parse_context_end_parse(context:PGMarkupParseContext; error:PPGError):Tgboolean;cdecl;external libglib2;
function g_markup_parse_context_get_element(context:PGMarkupParseContext):Pgchar;cdecl;external libglib2;
function g_markup_parse_context_get_element_stack(context:PGMarkupParseContext):PGSList;cdecl;external libglib2;
{ For user-constructed error messages, has no precise semantics  }
procedure g_markup_parse_context_get_position(context:PGMarkupParseContext; line_number:Pgint; char_number:Pgint);cdecl;external libglib2;
function g_markup_parse_context_get_offset(context:PGMarkupParseContext):Tgsize;cdecl;external libglib2;
procedure g_markup_parse_context_get_tag_start(context:PGMarkupParseContext; line_number:Pgsize; char_number:Pgsize; offset:Pgsize);cdecl;external libglib2;
function g_markup_parse_context_get_user_data(context:PGMarkupParseContext):Tgpointer;cdecl;external libglib2;
{ useful when saving  }
function g_markup_escape_text(text:Pgchar; length:Tgssize):Pgchar;cdecl;external libglib2;
function g_markup_printf_escaped(format:Pchar; args:array of const):Pgchar;cdecl;external libglib2;
function g_markup_printf_escaped(format:Pchar):Pgchar;cdecl;external libglib2;
function g_markup_vprintf_escaped(format:Pchar; args:Tva_list):Pgchar;cdecl;external libglib2;
type
  PGMarkupCollectType = ^TGMarkupCollectType;
  TGMarkupCollectType =  Longint;
  Const
    G_MARKUP_COLLECT_INVALID = 0;
    G_MARKUP_COLLECT_STRING = 1;
    G_MARKUP_COLLECT_STRDUP = 2;
    G_MARKUP_COLLECT_BOOLEAN = 3;
    G_MARKUP_COLLECT_TRISTATE = 4;
    G_MARKUP_COLLECT_OPTIONAL = 1 shl 16;
;
{ useful from start_element  }

function g_markup_collect_attributes(element_name:Pgchar; attribute_names:PPgchar; attribute_values:PPgchar; error:PPGError; first_type:TGMarkupCollectType; 
           first_attr:Pgchar; args:array of const):Tgboolean;cdecl;external libglib2;
function g_markup_collect_attributes(element_name:Pgchar; attribute_names:PPgchar; attribute_values:PPgchar; error:PPGError; first_type:TGMarkupCollectType; 
           first_attr:Pgchar):Tgboolean;cdecl;external libglib2;
{$endif}
{ __G_MARKUP_H__  }

// === Konventiert am: 22-6-26 17:10:49 ===


implementation


{ was #define dname def_expr }
function G_MARKUP_ERROR : longint; { return type might be wrong }
  begin
    G_MARKUP_ERROR:=g_markup_error_quark;
  end;


end.
