unit video_enumtypes;

interface

uses
  fp_glib2, fp_gst;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
(** unsupported pragma#pragma once*)
{$include <glib-object.h>}
{$include <gst/video/video-prelude.h>}
{ enumerations from "colorbalance.h"  }

function gst_color_balance_type_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_COLOR_BALANCE_TYPE : longint; { return type might be wrong }

{ enumerations from "gstvideodecoder.h"  }
function gst_video_decoder_request_sync_point_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_DECODER_REQUEST_SYNC_POINT_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstvideometa.h"  }
function gst_video_gl_texture_type_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_GL_TEXTURE_TYPE : longint; { return type might be wrong }

function gst_video_gl_texture_orientation_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_GL_TEXTURE_ORIENTATION : longint; { return type might be wrong }

{ enumerations from "gstvideotimecode.h"  }
function gst_video_time_code_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_TIME_CODE_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstvideoutils.h"  }
function gst_video_codec_frame_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_CODEC_FRAME_FLAGS : longint; { return type might be wrong }

{ enumerations from "navigation.h"  }
function gst_navigation_modifier_type_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_NAVIGATION_MODIFIER_TYPE : longint; { return type might be wrong }

function gst_navigation_command_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_NAVIGATION_COMMAND : longint; { return type might be wrong }

function gst_navigation_query_type_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_NAVIGATION_QUERY_TYPE : longint; { return type might be wrong }

function gst_navigation_message_type_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_NAVIGATION_MESSAGE_TYPE : longint; { return type might be wrong }

function gst_navigation_event_type_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_NAVIGATION_EVENT_TYPE : longint; { return type might be wrong }

{ enumerations from "video-anc.h"  }
function gst_video_ancillary_did_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_ANCILLARY_DID : longint; { return type might be wrong }

function gst_video_ancillary_di_d16_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_ANCILLARY_DI_D16 : longint; { return type might be wrong }

function gst_ancillary_meta_field_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_ANCILLARY_META_FIELD : longint; { return type might be wrong }

function gst_video_afd_value_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_AFD_VALUE : longint; { return type might be wrong }

function gst_video_afd_spec_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_AFD_SPEC : longint; { return type might be wrong }

function gst_video_caption_type_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_CAPTION_TYPE : longint; { return type might be wrong }

function gst_video_vbi_parser_result_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_VBI_PARSER_RESULT : longint; { return type might be wrong }

{ enumerations from "video-chroma.h"  }
function gst_video_chroma_site_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_CHROMA_SITE : longint; { return type might be wrong }

function gst_video_chroma_method_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_CHROMA_METHOD : longint; { return type might be wrong }

function gst_video_chroma_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_CHROMA_FLAGS : longint; { return type might be wrong }

{ enumerations from "video-color.h"  }
function gst_video_color_range_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_COLOR_RANGE : longint; { return type might be wrong }

function gst_video_color_matrix_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_COLOR_MATRIX : longint; { return type might be wrong }

function gst_video_transfer_function_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_TRANSFER_FUNCTION : longint; { return type might be wrong }

function gst_video_color_primaries_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_COLOR_PRIMARIES : longint; { return type might be wrong }

{ enumerations from "video-converter.h"  }
function gst_video_alpha_mode_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_ALPHA_MODE : longint; { return type might be wrong }

function gst_video_chroma_mode_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_CHROMA_MODE : longint; { return type might be wrong }

function gst_video_matrix_mode_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_MATRIX_MODE : longint; { return type might be wrong }

function gst_video_gamma_mode_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_GAMMA_MODE : longint; { return type might be wrong }

function gst_video_primaries_mode_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_PRIMARIES_MODE : longint; { return type might be wrong }

{ enumerations from "video-dither.h"  }
function gst_video_dither_method_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_DITHER_METHOD : longint; { return type might be wrong }

function gst_video_dither_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_DITHER_FLAGS : longint; { return type might be wrong }

{ enumerations from "video-format.h"  }
function gst_video_format_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_FORMAT : longint; { return type might be wrong }

function gst_video_format_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_FORMAT_FLAGS : longint; { return type might be wrong }

function gst_video_pack_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_PACK_FLAGS : longint; { return type might be wrong }

{ enumerations from "video-frame.h"  }
function gst_video_frame_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_FRAME_FLAGS : longint; { return type might be wrong }

function gst_video_buffer_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_BUFFER_FLAGS : longint; { return type might be wrong }

function gst_video_frame_map_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_FRAME_MAP_FLAGS : longint; { return type might be wrong }

{ enumerations from "video-info.h"  }
function gst_video_interlace_mode_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_INTERLACE_MODE : longint; { return type might be wrong }

function gst_video_multiview_mode_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_MULTIVIEW_MODE : longint; { return type might be wrong }

function gst_video_multiview_frame_packing_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_MULTIVIEW_FRAME_PACKING : longint; { return type might be wrong }

function gst_video_multiview_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_MULTIVIEW_FLAGS : longint; { return type might be wrong }

function gst_video_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_FLAGS : longint; { return type might be wrong }

function gst_video_field_order_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_FIELD_ORDER : longint; { return type might be wrong }

{ enumerations from "video-overlay-composition.h"  }
function gst_video_overlay_format_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_OVERLAY_FORMAT_FLAGS : longint; { return type might be wrong }

{ enumerations from "video-resampler.h"  }
function gst_video_resampler_method_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_RESAMPLER_METHOD : longint; { return type might be wrong }

function gst_video_resampler_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_RESAMPLER_FLAGS : longint; { return type might be wrong }

{ enumerations from "video-scaler.h"  }
function gst_video_scaler_flags_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_SCALER_FLAGS : longint; { return type might be wrong }

{ enumerations from "video-tile.h"  }
function gst_video_tile_type_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_TILE_TYPE : longint; { return type might be wrong }

function gst_video_tile_mode_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_TILE_MODE : longint; { return type might be wrong }

{ enumerations from "video.h"  }
function gst_video_orientation_method_get_type:TGType;cdecl;external libgstvideo;
{ was #define dname def_expr }
function GST_TYPE_VIDEO_ORIENTATION_METHOD : longint; { return type might be wrong }

{ Generated data ends here  }

// === Konventiert am: 15-7-26 13:36:07 ===


implementation


{ was #define dname def_expr }
function GST_TYPE_COLOR_BALANCE_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_COLOR_BALANCE_TYPE:=gst_color_balance_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_DECODER_REQUEST_SYNC_POINT_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_DECODER_REQUEST_SYNC_POINT_FLAGS:=gst_video_decoder_request_sync_point_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_GL_TEXTURE_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_GL_TEXTURE_TYPE:=gst_video_gl_texture_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_GL_TEXTURE_ORIENTATION : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_GL_TEXTURE_ORIENTATION:=gst_video_gl_texture_orientation_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_TIME_CODE_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_TIME_CODE_FLAGS:=gst_video_time_code_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_CODEC_FRAME_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_CODEC_FRAME_FLAGS:=gst_video_codec_frame_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_NAVIGATION_MODIFIER_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_NAVIGATION_MODIFIER_TYPE:=gst_navigation_modifier_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_NAVIGATION_COMMAND : longint; { return type might be wrong }
  begin
    GST_TYPE_NAVIGATION_COMMAND:=gst_navigation_command_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_NAVIGATION_QUERY_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_NAVIGATION_QUERY_TYPE:=gst_navigation_query_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_NAVIGATION_MESSAGE_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_NAVIGATION_MESSAGE_TYPE:=gst_navigation_message_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_NAVIGATION_EVENT_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_NAVIGATION_EVENT_TYPE:=gst_navigation_event_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_ANCILLARY_DID : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_ANCILLARY_DID:=gst_video_ancillary_did_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_ANCILLARY_DI_D16 : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_ANCILLARY_DI_D16:=gst_video_ancillary_di_d16_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_ANCILLARY_META_FIELD : longint; { return type might be wrong }
  begin
    GST_TYPE_ANCILLARY_META_FIELD:=gst_ancillary_meta_field_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_AFD_VALUE : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_AFD_VALUE:=gst_video_afd_value_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_AFD_SPEC : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_AFD_SPEC:=gst_video_afd_spec_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_CAPTION_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_CAPTION_TYPE:=gst_video_caption_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_VBI_PARSER_RESULT : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_VBI_PARSER_RESULT:=gst_video_vbi_parser_result_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_CHROMA_SITE : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_CHROMA_SITE:=gst_video_chroma_site_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_CHROMA_METHOD : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_CHROMA_METHOD:=gst_video_chroma_method_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_CHROMA_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_CHROMA_FLAGS:=gst_video_chroma_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_COLOR_RANGE : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_COLOR_RANGE:=gst_video_color_range_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_COLOR_MATRIX : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_COLOR_MATRIX:=gst_video_color_matrix_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_TRANSFER_FUNCTION : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_TRANSFER_FUNCTION:=gst_video_transfer_function_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_COLOR_PRIMARIES : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_COLOR_PRIMARIES:=gst_video_color_primaries_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_ALPHA_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_ALPHA_MODE:=gst_video_alpha_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_CHROMA_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_CHROMA_MODE:=gst_video_chroma_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_MATRIX_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_MATRIX_MODE:=gst_video_matrix_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_GAMMA_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_GAMMA_MODE:=gst_video_gamma_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_PRIMARIES_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_PRIMARIES_MODE:=gst_video_primaries_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_DITHER_METHOD : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_DITHER_METHOD:=gst_video_dither_method_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_DITHER_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_DITHER_FLAGS:=gst_video_dither_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_FORMAT : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_FORMAT:=gst_video_format_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_FORMAT_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_FORMAT_FLAGS:=gst_video_format_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_PACK_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_PACK_FLAGS:=gst_video_pack_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_FRAME_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_FRAME_FLAGS:=gst_video_frame_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_BUFFER_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_BUFFER_FLAGS:=gst_video_buffer_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_FRAME_MAP_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_FRAME_MAP_FLAGS:=gst_video_frame_map_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_INTERLACE_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_INTERLACE_MODE:=gst_video_interlace_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_MULTIVIEW_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_MULTIVIEW_MODE:=gst_video_multiview_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_MULTIVIEW_FRAME_PACKING : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_MULTIVIEW_FRAME_PACKING:=gst_video_multiview_frame_packing_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_MULTIVIEW_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_MULTIVIEW_FLAGS:=gst_video_multiview_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_FLAGS:=gst_video_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_FIELD_ORDER : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_FIELD_ORDER:=gst_video_field_order_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_OVERLAY_FORMAT_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_OVERLAY_FORMAT_FLAGS:=gst_video_overlay_format_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_RESAMPLER_METHOD : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_RESAMPLER_METHOD:=gst_video_resampler_method_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_RESAMPLER_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_RESAMPLER_FLAGS:=gst_video_resampler_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_SCALER_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_SCALER_FLAGS:=gst_video_scaler_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_TILE_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_TILE_TYPE:=gst_video_tile_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_TILE_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_TILE_MODE:=gst_video_tile_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_VIDEO_ORIENTATION_METHOD : longint; { return type might be wrong }
  begin
    GST_TYPE_VIDEO_ORIENTATION_METHOD:=gst_video_orientation_method_get_type;
  end;


end.
