{$IFDEF read_interface}

type
  PEfl_Canvas_Animation_Repeat_Mode = ^TEfl_Canvas_Animation_Repeat_Mode;
  TEfl_Canvas_Animation_Repeat_Mode = longint;

const
  EFL_CANVAS_ANIMATION_REPEAT_MODE_RESTART = 0;
  EFL_CANVAS_ANIMATION_REPEAT_MODE_REVERSE = 1;
  EFL_CANVAS_ANIMATION_REPEAT_MODE_LAST = 2;

  // === Konventiert am: 13-5-25 17:08:22 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
