unit fribidi_bidi_types;

interface

uses
  fp_fribidi, fribidi_types;

type
  PFriBidiLevel = ^TFriBidiLevel;
  TFriBidiLevel = byte;

const
  FRIBIDI_MASK_RTL = $00000001;
  FRIBIDI_MASK_ARABIC = $00000002;
  FRIBIDI_MASK_STRONG = $00000010;
  FRIBIDI_MASK_WEAK = $00000020;
  FRIBIDI_MASK_NEUTRAL = $00000040;
  FRIBIDI_MASK_SENTINEL = $00000080;
  FRIBIDI_MASK_LETTER = $00000100;
  FRIBIDI_MASK_NUMBER = $00000200;
  FRIBIDI_MASK_NUMSEPTER = $00000400;
  FRIBIDI_MASK_SPACE = $00000800;
  FRIBIDI_MASK_EXPLICIT = $00001000;
  FRIBIDI_MASK_ISOLATE = $00008000;
  FRIBIDI_MASK_SEPARATOR = $00002000;
  FRIBIDI_MASK_OVERRIDE = $00004000;
  FRIBIDI_MASK_FIRST = $02000000;
  FRIBIDI_MASK_ES = $00010000;
  FRIBIDI_MASK_ET = $00020000;
  FRIBIDI_MASK_CS = $00040000;
  FRIBIDI_MASK_NSM = $00080000;
  FRIBIDI_MASK_BN = $00100000;
  FRIBIDI_MASK_BS = $00200000;
  FRIBIDI_MASK_SS = $00400000;
  FRIBIDI_MASK_WS = $00800000;
  FRIBIDI_MASK_PRIVATE = $01000000;

  FRIBIDI_TYPE_LTR_VAL = FRIBIDI_MASK_STRONG or FRIBIDI_MASK_LETTER;
  FRIBIDI_TYPE_RTL_VAL = (FRIBIDI_MASK_STRONG or FRIBIDI_MASK_LETTER) or FRIBIDI_MASK_RTL;
  FRIBIDI_TYPE_AL_VAL = ((FRIBIDI_MASK_STRONG or FRIBIDI_MASK_LETTER) or FRIBIDI_MASK_RTL) or FRIBIDI_MASK_ARABIC;
  FRIBIDI_TYPE_LRE_VAL = FRIBIDI_MASK_STRONG or FRIBIDI_MASK_EXPLICIT;
  FRIBIDI_TYPE_RLE_VAL = (FRIBIDI_MASK_STRONG or FRIBIDI_MASK_EXPLICIT) or FRIBIDI_MASK_RTL;
  FRIBIDI_TYPE_LRO_VAL = (FRIBIDI_MASK_STRONG or FRIBIDI_MASK_EXPLICIT) or FRIBIDI_MASK_OVERRIDE;
  FRIBIDI_TYPE_RLO_VAL = ((FRIBIDI_MASK_STRONG or FRIBIDI_MASK_EXPLICIT) or FRIBIDI_MASK_RTL) or FRIBIDI_MASK_OVERRIDE;
  FRIBIDI_TYPE_PDF_VAL = FRIBIDI_MASK_WEAK or FRIBIDI_MASK_EXPLICIT;
  FRIBIDI_TYPE_EN_VAL = FRIBIDI_MASK_WEAK or FRIBIDI_MASK_NUMBER;
  FRIBIDI_TYPE_AN_VAL = (FRIBIDI_MASK_WEAK or FRIBIDI_MASK_NUMBER) or FRIBIDI_MASK_ARABIC;
  FRIBIDI_TYPE_ES_VAL = (FRIBIDI_MASK_WEAK or FRIBIDI_MASK_NUMSEPTER) or FRIBIDI_MASK_ES;
  FRIBIDI_TYPE_ET_VAL = (FRIBIDI_MASK_WEAK or FRIBIDI_MASK_NUMSEPTER) or FRIBIDI_MASK_ET;
  FRIBIDI_TYPE_CS_VAL = (FRIBIDI_MASK_WEAK or FRIBIDI_MASK_NUMSEPTER) or FRIBIDI_MASK_CS;
  FRIBIDI_TYPE_NSM_VAL = FRIBIDI_MASK_WEAK or FRIBIDI_MASK_NSM;
  FRIBIDI_TYPE_BN_VAL = (FRIBIDI_MASK_WEAK or FRIBIDI_MASK_SPACE) or FRIBIDI_MASK_BN;
  FRIBIDI_TYPE_BS_VAL = ((FRIBIDI_MASK_NEUTRAL or FRIBIDI_MASK_SPACE) or FRIBIDI_MASK_SEPARATOR) or FRIBIDI_MASK_BS;
  FRIBIDI_TYPE_SS_VAL = ((FRIBIDI_MASK_NEUTRAL or FRIBIDI_MASK_SPACE) or FRIBIDI_MASK_SEPARATOR) or FRIBIDI_MASK_SS;
  FRIBIDI_TYPE_WS_VAL = (FRIBIDI_MASK_NEUTRAL or FRIBIDI_MASK_SPACE) or FRIBIDI_MASK_WS;
  FRIBIDI_TYPE_ON_VAL = FRIBIDI_MASK_NEUTRAL;
  FRIBIDI_TYPE_WLTR_VAL = FRIBIDI_MASK_WEAK;
  FRIBIDI_TYPE_WRTL_VAL = FRIBIDI_MASK_WEAK or FRIBIDI_MASK_RTL;
  FRIBIDI_TYPE_SENTINEL = FRIBIDI_MASK_SENTINEL;
  FRIBIDI_TYPE_PRIVATE = FRIBIDI_MASK_PRIVATE;
  FRIBIDI_TYPE_LRI_VAL = FRIBIDI_MASK_NEUTRAL or FRIBIDI_MASK_ISOLATE;
  FRIBIDI_TYPE_RLI_VAL = (FRIBIDI_MASK_NEUTRAL or FRIBIDI_MASK_ISOLATE) or FRIBIDI_MASK_RTL;
  FRIBIDI_TYPE_FSI_VAL = (FRIBIDI_MASK_NEUTRAL or FRIBIDI_MASK_ISOLATE) or FRIBIDI_MASK_FIRST;
  FRIBIDI_TYPE_PDI_VAL = (FRIBIDI_MASK_NEUTRAL or FRIBIDI_MASK_WEAK) or FRIBIDI_MASK_ISOLATE;

type
  PFriBidiCharType = ^TFriBidiCharType;
  TFriBidiCharType = longint;

const
  _FRIBIDI_TYPE_SENTINEL = FRIBIDI_TYPE_SENTINEL;

type
  PFriBidiParType = ^TFriBidiParType;
  TFriBidiParType = longint;

const
  _FRIBIDI_PAR_SENTINEL = FRIBIDI_TYPE_SENTINEL;

const
  FRIBIDI_TYPE_LTR = FRIBIDI_TYPE_LTR_VAL;
  FRIBIDI_TYPE_RTL = FRIBIDI_TYPE_RTL_VAL;
  FRIBIDI_TYPE_AL = FRIBIDI_TYPE_AL_VAL;
  FRIBIDI_TYPE_EN = FRIBIDI_TYPE_EN_VAL;
  FRIBIDI_TYPE_AN = FRIBIDI_TYPE_AN_VAL;
  FRIBIDI_TYPE_ES = FRIBIDI_TYPE_ES_VAL;
  FRIBIDI_TYPE_ET = FRIBIDI_TYPE_ET_VAL;
  FRIBIDI_TYPE_CS = FRIBIDI_TYPE_CS_VAL;
  FRIBIDI_TYPE_NSM = FRIBIDI_TYPE_NSM_VAL;
  FRIBIDI_TYPE_BN = FRIBIDI_TYPE_BN_VAL;
  FRIBIDI_TYPE_BS = FRIBIDI_TYPE_BS_VAL;
  FRIBIDI_TYPE_SS = FRIBIDI_TYPE_SS_VAL;
  FRIBIDI_TYPE_WS = FRIBIDI_TYPE_WS_VAL;
  FRIBIDI_TYPE_ON = FRIBIDI_TYPE_ON_VAL;
  FRIBIDI_TYPE_LRE = FRIBIDI_TYPE_LRE_VAL;
  FRIBIDI_TYPE_RLE = FRIBIDI_TYPE_RLE_VAL;
  FRIBIDI_TYPE_LRO = FRIBIDI_TYPE_LRO_VAL;
  FRIBIDI_TYPE_RLO = FRIBIDI_TYPE_RLO_VAL;
  FRIBIDI_TYPE_PDF = FRIBIDI_TYPE_PDF_VAL;
  FRIBIDI_TYPE_LRI = FRIBIDI_TYPE_LRI_VAL;
  FRIBIDI_TYPE_RLI = FRIBIDI_TYPE_RLI_VAL;
  FRIBIDI_TYPE_FSI = FRIBIDI_TYPE_FSI_VAL;
  FRIBIDI_TYPE_PDI = FRIBIDI_TYPE_PDI_VAL;

const
  FRIBIDI_PAR_LTR = FRIBIDI_TYPE_LTR_VAL;
  FRIBIDI_PAR_RTL = FRIBIDI_TYPE_RTL_VAL;
  FRIBIDI_PAR_ON = FRIBIDI_TYPE_ON_VAL;
  FRIBIDI_PAR_WLTR = FRIBIDI_TYPE_WLTR_VAL;
  FRIBIDI_PAR_WRTL = FRIBIDI_TYPE_WRTL_VAL;

const
  FRIBIDI_TYPE_WLTR = FRIBIDI_PAR_WLTR;
  FRIBIDI_TYPE_WRTL = FRIBIDI_PAR_WRTL;

function FRIBIDI_LEVEL_IS_RTL(lev: DWord): DWord;
function FRIBIDI_LEVEL_TO_DIR(lev: longint): longint;
function FRIBIDI_DIR_TO_LEVEL(dir: longint): TFriBidiLevel;
function FRIBIDI_IS_RTL(p: DWord): DWord;
function FRIBIDI_IS_ARABIC(p: DWord): DWord;
function FRIBIDI_IS_STRONG(p: DWord): DWord;
function FRIBIDI_IS_WEAK(p: DWord): DWord;
function FRIBIDI_IS_NEUTRAL(p: DWord): DWord;
function FRIBIDI_IS_SENTINEL(p: DWord): DWord;
function FRIBIDI_IS_LETTER(p: DWord): DWord;
function FRIBIDI_IS_NUMBER(p: DWord): DWord;
function FRIBIDI_IS_NUMBER_SEPARATOR_OR_TERMINATOR(p: DWord): DWord;
function FRIBIDI_IS_SPACE(p: DWord): DWord;
function FRIBIDI_IS_EXPLICIT(p: DWord): DWord;
function FRIBIDI_IS_ISOLATE(p: DWord): DWord;
function FRIBIDI_IS_SEPARATOR(p: DWord): DWord;
function FRIBIDI_IS_OVERRIDE(p: DWord): DWord;
function FRIBIDI_IS_LTR_LETTER(p: DWord): boolean;
function FRIBIDI_IS_RTL_LETTER(p: DWord): boolean;
function FRIBIDI_IS_ES_OR_CS(p: DWord): DWord;
function FRIBIDI_IS_EXPLICIT_OR_BN(p: DWord): DWord;
function FRIBIDI_IS_EXPLICIT_OR_BN_OR_NSM(p: DWord): DWord;
function FRIBIDI_IS_EXPLICIT_OR_ISOLATE_OR_BN_OR_NSM(p: DWord): DWord;
function FRIBIDI_IS_EXPLICIT_OR_BN_OR_WS(p: DWord): DWord;
function FRIBIDI_IS_EXPLICIT_OR_SEPARATOR_OR_BN_OR_WS(p: DWord): DWord;
function FRIBIDI_IS_PRIVATE(p: DWord): DWord;
function FRIBIDI_CHANGE_NUMBER_TO_RTL(p: DWord): longint;
function FRIBIDI_EXPLICIT_TO_OVERRIDE_DIR(p: DWord): longint;
function FRIBIDI_WEAK_PARAGRAPH(p: DWord): longint;

function fribidi_get_bidi_type(ch: TFriBidiChar): TFriBidiCharType; cdecl; external libfribidi;
procedure fribidi_get_bidi_types(str: PFriBidiChar; len: TFriBidiStrIndex; btypes: PFriBidiCharType); cdecl; external libfribidi;
function fribidi_get_bidi_type_name(t: TFriBidiCharType): pchar; cdecl; external libfribidi;

// === Konventiert am: 31-12-25 16:08:46 ===


implementation


function FRIBIDI_LEVEL_IS_RTL(lev: DWord): DWord;
begin
  FRIBIDI_LEVEL_IS_RTL := lev and 1;
end;

function FRIBIDI_LEVEL_TO_DIR(lev: longint): longint;
begin
  if FRIBIDI_LEVEL_IS_RTL(lev) <> 0 then begin
    Result := FRIBIDI_TYPE_RTL;
  end else begin
    Result := FRIBIDI_TYPE_LTR;
  end;
end;

function FRIBIDI_DIR_TO_LEVEL(dir: longint): TFriBidiLevel;
begin
  if FRIBIDI_IS_RTL(dir) <> 0 then begin
    Result := 1;
  end else begin
    Result := 0;
  end;
end;

function FRIBIDI_IS_RTL(p: DWord): DWord;
begin
  FRIBIDI_IS_RTL := p and FRIBIDI_MASK_RTL;
end;

function FRIBIDI_IS_ARABIC(p: DWord): DWord;
begin
  FRIBIDI_IS_ARABIC := p and FRIBIDI_MASK_ARABIC;
end;

function FRIBIDI_IS_STRONG(p: DWord): DWord;
begin
  FRIBIDI_IS_STRONG := p and FRIBIDI_MASK_STRONG;
end;

function FRIBIDI_IS_WEAK(p: DWord): DWord;
begin
  FRIBIDI_IS_WEAK := p and FRIBIDI_MASK_WEAK;
end;

function FRIBIDI_IS_NEUTRAL(p: DWord): DWord;
begin
  FRIBIDI_IS_NEUTRAL := p and FRIBIDI_MASK_NEUTRAL;
end;

function FRIBIDI_IS_SENTINEL(p: DWord): DWord;
begin
  FRIBIDI_IS_SENTINEL := p and FRIBIDI_MASK_SENTINEL;
end;

function FRIBIDI_IS_LETTER(p: DWord): DWord;
begin
  FRIBIDI_IS_LETTER := p and FRIBIDI_MASK_LETTER;
end;

function FRIBIDI_IS_NUMBER(p: DWord): DWord;
begin
  FRIBIDI_IS_NUMBER := p and FRIBIDI_MASK_NUMBER;
end;

function FRIBIDI_IS_NUMBER_SEPARATOR_OR_TERMINATOR(p: DWord): DWord;
begin
  FRIBIDI_IS_NUMBER_SEPARATOR_OR_TERMINATOR := p and FRIBIDI_MASK_NUMSEPTER;
end;

function FRIBIDI_IS_SPACE(p: DWord): DWord;
begin
  FRIBIDI_IS_SPACE := p and FRIBIDI_MASK_SPACE;
end;

function FRIBIDI_IS_EXPLICIT(p: DWord): DWord;
begin
  FRIBIDI_IS_EXPLICIT := p and FRIBIDI_MASK_EXPLICIT;
end;

function FRIBIDI_IS_ISOLATE(p: DWord): DWord;
begin
  FRIBIDI_IS_ISOLATE := p and FRIBIDI_MASK_ISOLATE;
end;

function FRIBIDI_IS_SEPARATOR(p: DWord): DWord;
begin
  FRIBIDI_IS_SEPARATOR := p and FRIBIDI_MASK_SEPARATOR;
end;

function FRIBIDI_IS_OVERRIDE(p: DWord): DWord;
begin
  FRIBIDI_IS_OVERRIDE := p and FRIBIDI_MASK_OVERRIDE;
end;

function FRIBIDI_IS_LTR_LETTER(p: DWord): boolean;
begin
  FRIBIDI_IS_LTR_LETTER := p and (FRIBIDI_MASK_LETTER or FRIBIDI_MASK_RTL) = FRIBIDI_MASK_LETTER;
end;

function FRIBIDI_IS_RTL_LETTER(p: DWord): boolean;
begin
  FRIBIDI_IS_RTL_LETTER := p and (FRIBIDI_MASK_LETTER or FRIBIDI_MASK_RTL) = (FRIBIDI_MASK_LETTER or FRIBIDI_MASK_RTL);
end;

function FRIBIDI_IS_ES_OR_CS(p: DWord): DWord;
begin
  FRIBIDI_IS_ES_OR_CS := p and FRIBIDI_MASK_ES or FRIBIDI_MASK_CS;
end;

function FRIBIDI_IS_EXPLICIT_OR_BN(p: DWord): DWord;
begin
  FRIBIDI_IS_EXPLICIT_OR_BN := p and FRIBIDI_MASK_EXPLICIT or FRIBIDI_MASK_BN;
end;

function FRIBIDI_IS_EXPLICIT_OR_BN_OR_NSM(p: DWord): DWord;
begin
  FRIBIDI_IS_EXPLICIT_OR_BN_OR_NSM := p and (FRIBIDI_MASK_EXPLICIT or FRIBIDI_MASK_BN) or FRIBIDI_MASK_NSM;
end;

function FRIBIDI_IS_EXPLICIT_OR_ISOLATE_OR_BN_OR_NSM(p: DWord): DWord;
begin
  FRIBIDI_IS_EXPLICIT_OR_ISOLATE_OR_BN_OR_NSM := p and (FRIBIDI_MASK_EXPLICIT or FRIBIDI_MASK_ISOLATE or FRIBIDI_MASK_BN or FRIBIDI_MASK_NSM);
end;

function FRIBIDI_IS_EXPLICIT_OR_BN_OR_WS(p: DWord): DWord;
begin
  FRIBIDI_IS_EXPLICIT_OR_BN_OR_WS := p and (FRIBIDI_MASK_EXPLICIT or FRIBIDI_MASK_BN or FRIBIDI_MASK_WS);
end;

function FRIBIDI_IS_EXPLICIT_OR_SEPARATOR_OR_BN_OR_WS(p: DWord): DWord;
begin
  FRIBIDI_IS_EXPLICIT_OR_SEPARATOR_OR_BN_OR_WS := p and (FRIBIDI_MASK_EXPLICIT or FRIBIDI_MASK_SEPARATOR or FRIBIDI_MASK_BN or FRIBIDI_MASK_WS);
end;

function FRIBIDI_IS_PRIVATE(p: DWord): DWord;
begin
  FRIBIDI_IS_PRIVATE := p and FRIBIDI_MASK_PRIVATE;
end;

function FRIBIDI_CHANGE_NUMBER_TO_RTL(p: DWord): longint;
begin
  if FRIBIDI_IS_NUMBER(p) <> 0 then begin
    Result := FRIBIDI_TYPE_RTL;
  end else begin
    Result := p;
  end;
end;

function FRIBIDI_EXPLICIT_TO_OVERRIDE_DIR(p: DWord): longint;
begin
  if FRIBIDI_IS_OVERRIDE(p) <> 0 then begin
    Result := FRIBIDI_LEVEL_TO_DIR(FRIBIDI_DIR_TO_LEVEL(p));
  end else begin
    Result := FRIBIDI_TYPE_ON;
  end;
end;

function FRIBIDI_WEAK_PARAGRAPH(p: DWord): longint;
begin
  FRIBIDI_WEAK_PARAGRAPH := FRIBIDI_PAR_WLTR or (p and FRIBIDI_MASK_RTL);
end;


end.
