unit fribidi_unicode;

interface

uses
  fp_fribidi, fribidi_types;

  {$IFDEF FPC}
  {$PACKRECORDS C}
  {$ENDIF}


function FRIBIDI_UNICODE_CHARS: longint;

const
  FRIBIDI_UNICODE_VERSION = 'unknown';

const
  FRIBIDI_BIDI_NUM_TYPES = 19;
  FRIBIDI_BIDI_MAX_EXPLICIT_LEVEL = 125;
  FRIBIDI_BIDI_MAX_RESOLVED_LEVELS = 127;
  FRIBIDI_BIDI_MAX_NESTED_BRACKET_PAIRS = 63;

  FRIBIDI_CHAR_LRM = $200E;
  FRIBIDI_CHAR_RLM = $200F;
  FRIBIDI_CHAR_LRE = $202A;
  FRIBIDI_CHAR_RLE = $202B;
  FRIBIDI_CHAR_PDF = $202C;
  FRIBIDI_CHAR_LRO = $202D;
  FRIBIDI_CHAR_RLO = $202E;
  FRIBIDI_CHAR_LRI = $2066;
  FRIBIDI_CHAR_RLI = $2067;
  FRIBIDI_CHAR_FSI = $2068;
  FRIBIDI_CHAR_PDI = $2069;
  FRIBIDI_CHAR_LS = $2028;
  FRIBIDI_CHAR_PS = $2029;
  FRIBIDI_CHAR_ZWNJ = $200C;
  FRIBIDI_CHAR_ZWJ = $200D;
  FRIBIDI_CHAR_HEBREW_ALEF = $05D0;
  FRIBIDI_CHAR_ARABIC_ALEF = $0627;
  FRIBIDI_CHAR_ARABIC_ZERO = $0660;
  FRIBIDI_CHAR_PERSIAN_ZERO = $06F0;
  FRIBIDI_CHAR_ZWNBSP = $FEFF;
  FRIBIDI_CHAR_FILL = FRIBIDI_CHAR_ZWNBSP;

  // === Konventiert am: 31-12-25 16:09:17 ===


implementation


function FRIBIDI_UNICODE_CHARS: longint;
begin
  if sizeof(TFriBidiChar) >= 4 then begin
    Result := $110000;
  end else begin
    Result := $FFFE;
  end;
end;


end.
