
{$IFDEF read_interface}


const
  GST_DISABLE_GST_DEBUG = 1;  
  GST_DISABLE_PARSE = 1;  
  GST_DISABLE_REGISTRY = 1;  
  GST_DISABLE_PLUGIN = 1;  

const
  GST_PADDING_LARGE = 20;
  GST_DISABLE_CAST_CHECKS = 0;
  GST_DISABLE_GLIB_ASSERTS = 0;
  GST_DISABLE_GLIB_CHECKS = 0;

const
  GST_HAVE_UNALIGNED_ACCESS = 0;  
//  GST_HAVE_UNALIGNED_ACCESS = 1;

// === Konventiert am: 11-9-24 13:55:00 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}


{$ENDIF read_implementation}
