
unit pbutils_enumtypes;
interface

{
  Automatically converted by H2Pas 1.0.0 from pbutils_enumtypes.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    pbutils_enumtypes.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
(** unsupported pragma#pragma once*)
{$include <glib-object.h>}
{$include <gst/pbutils/pbutils-prelude.h>}
{ enumerations from "descriptions.h"  }

function gst_pb_utils_caps_description_flags_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GST_TYPE_PB_UTILS_CAPS_DESCRIPTION_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstaudiovisualizer.h"  }
function gst_audio_visualizer_shader_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_VISUALIZER_SHADER : longint; { return type might be wrong }

{ enumerations from "gstdiscoverer.h"  }
function gst_discoverer_result_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GST_TYPE_DISCOVERER_RESULT : longint; { return type might be wrong }

function gst_discoverer_serialize_flags_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GST_TYPE_DISCOVERER_SERIALIZE_FLAGS : longint; { return type might be wrong }

{ enumerations from "install-plugins.h"  }
function gst_install_plugins_return_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GST_TYPE_INSTALL_PLUGINS_RETURN : longint; { return type might be wrong }

{ Generated data ends here  }

implementation

{ was #define dname def_expr }
function GST_TYPE_PB_UTILS_CAPS_DESCRIPTION_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_PB_UTILS_CAPS_DESCRIPTION_FLAGS:=gst_pb_utils_caps_description_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_VISUALIZER_SHADER : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_VISUALIZER_SHADER:=gst_audio_visualizer_shader_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_DISCOVERER_RESULT : longint; { return type might be wrong }
  begin
    GST_TYPE_DISCOVERER_RESULT:=gst_discoverer_result_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_DISCOVERER_SERIALIZE_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_DISCOVERER_SERIALIZE_FLAGS:=gst_discoverer_serialize_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_INSTALL_PLUGINS_RETURN : longint; { return type might be wrong }
  begin
    GST_TYPE_INSTALL_PLUGINS_RETURN:=gst_install_plugins_return_get_type;
  end;


end.
