unit tkDecls;

interface

uses
 x,xlib, ctypes, tk_tcl_common, tcl, tk, tclPlatDecls, tkPlatDecls;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}

procedure Tk_MainLoop;cdecl;external libtkstub8_6;
function Tk_3DBorderColor(border:TTk_3DBorder):PXColor;cdecl;external libtkstub8_6;
function Tk_3DBorderGC(tkwin:TTk_Window; border:TTk_3DBorder; which:longint):TGC;cdecl;external libtkstub8_6;
procedure Tk_3DHorizontalBevel(tkwin:TTk_Window; drawable:TDrawable; border:TTk_3DBorder; x:longint; y:longint;
            width:longint; height:longint; leftIn:longint; rightIn:longint; topBevel:longint; 
            relief:longint);cdecl;external libtkstub8_6;
procedure Tk_3DVerticalBevel(tkwin:TTk_Window; drawable:TDrawable; border:TTk_3DBorder; x:longint; y:longint;
            width:longint; height:longint; leftBevel:longint; relief:longint);cdecl;external libtkstub8_6;
procedure Tk_AddOption(tkwin:TTk_Window; name:Pchar; value:Pchar; priority:longint);cdecl;external libtkstub8_6;
procedure Tk_BindEvent(bindingTable:TTk_BindingTable; eventPtr:PXEvent; tkwin:TTk_Window; numObjects:longint; objectPtr:PClientData);cdecl;external libtkstub8_6;
procedure Tk_CanvasDrawableCoords(canvas:TTk_Canvas; x:double; y:double; drawableXPtr:Psmallint; drawableYPtr:Psmallint);cdecl;external libtkstub8_6;
procedure Tk_CanvasEventuallyRedraw(canvas:TTk_Canvas; x1:longint; y1:longint; x2:longint; y2:longint);cdecl;external libtkstub8_6;
function Tk_CanvasGetCoord(interp:PTcl_Interp; canvas:TTk_Canvas; str:Pchar; doublePtr:Pdouble):longint;cdecl;external libtkstub8_6;
function Tk_CanvasGetTextInfo(canvas:TTk_Canvas):PTk_CanvasTextInfo;cdecl;external libtkstub8_6;
function Tk_CanvasPsBitmap(interp:PTcl_Interp; canvas:TTk_Canvas; bitmap:TPixmap; x:longint; y:longint;
           width:longint; height:longint):longint;cdecl;external libtkstub8_6;
function Tk_CanvasPsColor(interp:PTcl_Interp; canvas:TTk_Canvas; colorPtr:PXColor):longint;cdecl;external libtkstub8_6;
function Tk_CanvasPsFont(interp:PTcl_Interp; canvas:TTk_Canvas; font:TTk_Font):longint;cdecl;external libtkstub8_6;
procedure Tk_CanvasPsPath(interp:PTcl_Interp; canvas:TTk_Canvas; coordPtr:Pdouble; numPoints:longint);cdecl;external libtkstub8_6;
function Tk_CanvasPsStipple(interp:PTcl_Interp; canvas:TTk_Canvas; bitmap:TPixmap):longint;cdecl;external libtkstub8_6;
function Tk_CanvasPsY(canvas:TTk_Canvas; y:double):double;cdecl;external libtkstub8_6;
procedure Tk_CanvasSetStippleOrigin(canvas:TTk_Canvas; gc:TGC);cdecl;external libtkstub8_6;
function Tk_CanvasTagsParseProc(clientData:TClientData; interp:PTcl_Interp; tkwin:TTk_Window; value:Pchar; widgRec:Pchar;
           offset:longint):longint;cdecl;external libtkstub8_6;
function Tk_CanvasTagsPrintProc(clientData:TClientData; tkwin:TTk_Window; widgRec:Pchar; offset:longint; freeProcPtr:PTcl_FreeProc):Pchar;cdecl;external libtkstub8_6;
function Tk_CanvasTkwin(canvas:TTk_Canvas):TTk_Window;cdecl;external libtkstub8_6;
procedure Tk_CanvasWindowCoords(canvas:TTk_Canvas; x:double; y:double; screenXPtr:Psmallint; screenYPtr:Psmallint);cdecl;external libtkstub8_6;
procedure Tk_ChangeWindowAttributes(tkwin:TTk_Window; valueMask:dword; attsPtr:PXSetWindowAttributes);cdecl;external libtkstub8_6;
function Tk_CharBbox(layout:TTk_TextLayout; index:longint; xPtr:Plongint; yPtr:Plongint; widthPtr:Plongint;
           heightPtr:Plongint):longint;cdecl;external libtkstub8_6;
procedure Tk_ClearSelection(tkwin:TTk_Window; selection:TAtom);cdecl;external libtkstub8_6;
function Tk_ClipboardAppend(interp:PTcl_Interp; tkwin:TTk_Window; target:TAtom; format:TAtom; buffer:Pchar):longint;cdecl;external libtkstub8_6;
function Tk_ClipboardClear(interp:PTcl_Interp; tkwin:TTk_Window):longint;cdecl;external libtkstub8_6;
function Tk_ConfigureInfo(interp:PTcl_Interp; tkwin:TTk_Window; specs:PTk_ConfigSpec; widgRec:Pchar; argvName:Pchar;
           flags:longint):longint;cdecl;external libtkstub8_6;
function Tk_ConfigureValue(interp:PTcl_Interp; tkwin:TTk_Window; specs:PTk_ConfigSpec; widgRec:Pchar; argvName:Pchar;
           flags:longint):longint;cdecl;external libtkstub8_6;
function Tk_ConfigureWidget(interp:PTcl_Interp; tkwin:TTk_Window; specs:PTk_ConfigSpec; argc:longint; argv:PPchar;
           widgRec:Pchar; flags:longint):longint;cdecl;external libtkstub8_6;
procedure Tk_ConfigureWindow(tkwin:TTk_Window; valueMask:dword; valuePtr:PXWindowChanges);cdecl;external libtkstub8_6;
function Tk_ComputeTextLayout(font:TTk_Font; str:Pchar; numChars:longint; wrapLength:longint; justify:TTk_Justify;
           flags:longint; widthPtr:Plongint; heightPtr:Plongint):TTk_TextLayout;cdecl;external libtkstub8_6;
function Tk_CoordsToWindow(rootX:longint; rootY:longint; tkwin:TTk_Window):TTk_Window;cdecl;external libtkstub8_6;
function Tk_CreateBinding(interp:PTcl_Interp; bindingTable:TTk_BindingTable; obj:TClientData; eventStr:Pchar; script:Pchar;
           append:longint):dword;cdecl;external libtkstub8_6;
function Tk_CreateBindingTable(interp:PTcl_Interp):TTk_BindingTable;cdecl;external libtkstub8_6;
function Tk_CreateErrorHandler(display:PDisplay; errNum:longint; request:longint; minorCode:longint; errorProc:TTk_ErrorProc;
           clientData:TClientData):TTk_ErrorHandler;cdecl;external libtkstub8_6;
procedure Tk_CreateEventHandler(token:TTk_Window; mask:dword; proc:TTk_EventProc; clientData:TClientData);cdecl;external libtkstub8_6;
procedure Tk_CreateGenericHandler(proc:TTk_GenericProc; clientData:TClientData);cdecl;external libtkstub8_6;
procedure Tk_CreateImageType(typePtr:PTk_ImageType);cdecl;external libtkstub8_6;
procedure Tk_CreateItemType(typePtr:PTk_ItemType);cdecl;external libtkstub8_6;
procedure Tk_CreatePhotoImageFormat(formatPtr:PTk_PhotoImageFormat);cdecl;external libtkstub8_6;
procedure Tk_CreateSelHandler(tkwin:TTk_Window; selection:TAtom; target:TAtom; proc:TTk_SelectionProc; clientData:TClientData;
            format:TAtom);cdecl;external libtkstub8_6;
function Tk_CreateWindow(interp:PTcl_Interp; parent:TTk_Window; name:Pchar; screenName:Pchar):TTk_Window;cdecl;external libtkstub8_6;
function Tk_CreateWindowFromPath(interp:PTcl_Interp; tkwin:TTk_Window; pathName:Pchar; screenName:Pchar):TTk_Window;cdecl;external libtkstub8_6;
function Tk_DefineBitmap(interp:PTcl_Interp; name:Pchar; source:pointer; width:longint; height:longint):longint;cdecl;external libtkstub8_6;
procedure Tk_DefineCursor(window:TTk_Window; cursor:TTk_Cursor);cdecl;external libtkstub8_6;
procedure Tk_DeleteAllBindings(bindingTable:TTk_BindingTable; obj:TClientData);cdecl;external libtkstub8_6;
function Tk_DeleteBinding(interp:PTcl_Interp; bindingTable:TTk_BindingTable; obj:TClientData; eventStr:Pchar):longint;cdecl;external libtkstub8_6;
procedure Tk_DeleteBindingTable(bindingTable:TTk_BindingTable);cdecl;external libtkstub8_6;
procedure Tk_DeleteErrorHandler(handler:TTk_ErrorHandler);cdecl;external libtkstub8_6;
procedure Tk_DeleteEventHandler(token:TTk_Window; mask:dword; proc:TTk_EventProc; clientData:TClientData);cdecl;external libtkstub8_6;
procedure Tk_DeleteGenericHandler(proc:TTk_GenericProc; clientData:TClientData);cdecl;external libtkstub8_6;
procedure Tk_DeleteImage(interp:PTcl_Interp; name:Pchar);cdecl;external libtkstub8_6;
procedure Tk_DeleteSelHandler(tkwin:TTk_Window; selection:TAtom; target:TAtom);cdecl;external libtkstub8_6;
procedure Tk_DestroyWindow(tkwin:TTk_Window);cdecl;external libtkstub8_6;
function Tk_DisplayName(tkwin:TTk_Window):Pchar;cdecl;external libtkstub8_6;
function Tk_DistanceToTextLayout(layout:TTk_TextLayout; x:longint; y:longint):longint;cdecl;external libtkstub8_6;
procedure Tk_Draw3DPolygon(tkwin:TTk_Window; drawable:TDrawable; border:TTk_3DBorder; pointPtr:PXPoint; numPoints:longint;
            borderWidth:longint; leftRelief:longint);cdecl;external libtkstub8_6;
procedure Tk_Draw3DRectangle(tkwin:TTk_Window; drawable:TDrawable; border:TTk_3DBorder; x:longint; y:longint;
            width:longint; height:longint; borderWidth:longint; relief:longint);cdecl;external libtkstub8_6;
procedure Tk_DrawChars(display:PDisplay; drawable:TDrawable; gc:TGC; tkfont:TTk_Font; source:Pchar;
            numBytes:longint; x:longint; y:longint);cdecl;external libtkstub8_6;
procedure Tk_DrawFocusHighlight(tkwin:TTk_Window; gc:TGC; width:longint; drawable:TDrawable);cdecl;external libtkstub8_6;
procedure Tk_DrawTextLayout(display:PDisplay; drawable:TDrawable; gc:TGC; layout:TTk_TextLayout; x:longint;
            y:longint; firstChar:longint; lastChar:longint);cdecl;external libtkstub8_6;
procedure Tk_Fill3DPolygon(tkwin:TTk_Window; drawable:TDrawable; border:TTk_3DBorder; pointPtr:PXPoint; numPoints:longint;
            borderWidth:longint; leftRelief:longint);cdecl;external libtkstub8_6;
procedure Tk_Fill3DRectangle(tkwin:TTk_Window; drawable:TDrawable; border:TTk_3DBorder; x:longint; y:longint;
            width:longint; height:longint; borderWidth:longint; relief:longint);cdecl;external libtkstub8_6;
function Tk_FindPhoto(interp:PTcl_Interp; imageName:Pchar):TTk_PhotoHandle;cdecl;external libtkstub8_6;
function Tk_FontId(font:TTk_Font):TFont;cdecl;external libtkstub8_6;
procedure Tk_Free3DBorder(border:TTk_3DBorder);cdecl;external libtkstub8_6;
procedure Tk_FreeBitmap(display:PDisplay; bitmap:TPixmap);cdecl;external libtkstub8_6;
procedure Tk_FreeColor(colorPtr:PXColor);cdecl;external libtkstub8_6;
procedure Tk_FreeColormap(display:PDisplay; colormap:TColormap);cdecl;external libtkstub8_6;
procedure Tk_FreeCursor(display:PDisplay; cursor:TTk_Cursor);cdecl;external libtkstub8_6;
procedure Tk_FreeFont(f:TTk_Font);cdecl;external libtkstub8_6;
procedure Tk_FreeGC(display:PDisplay; gc:TGC);cdecl;external libtkstub8_6;
procedure Tk_FreeImage(image:TTk_Image);cdecl;external libtkstub8_6;
procedure Tk_FreeOptions(specs:PTk_ConfigSpec; widgRec:Pchar; display:PDisplay; needFlags:longint);cdecl;external libtkstub8_6;
procedure Tk_FreePixmap(display:PDisplay; pixmap:TPixmap);cdecl;external libtkstub8_6;
procedure Tk_FreeTextLayout(textLayout:TTk_TextLayout);cdecl;external libtkstub8_6;
procedure Tk_FreeXId(display:PDisplay; xid:TXID);cdecl;external libtkstub8_6;
function Tk_GCForColor(colorPtr:PXColor; drawable:TDrawable):TGC;cdecl;external libtkstub8_6;
procedure Tk_GeometryRequest(tkwin:TTk_Window; reqWidth:longint; reqHeight:longint);cdecl;external libtkstub8_6;
function Tk_Get3DBorder(interp:PTcl_Interp; tkwin:TTk_Window; colorName:TTk_Uid):TTk_3DBorder;cdecl;external libtkstub8_6;
procedure Tk_GetAllBindings(interp:PTcl_Interp; bindingTable:TTk_BindingTable; obj:TClientData);cdecl;external libtkstub8_6;
function Tk_GetAnchor(interp:PTcl_Interp; str:Pchar; anchorPtr:PTk_Anchor):longint;cdecl;external libtkstub8_6;
function Tk_GetAtomName(tkwin:TTk_Window; atom:TAtom):Pchar;cdecl;external libtkstub8_6;
function Tk_GetBinding(interp:PTcl_Interp; bindingTable:TTk_BindingTable; obj:TClientData; eventStr:Pchar):Pchar;cdecl;external libtkstub8_6;
function Tk_GetBitmap(interp:PTcl_Interp; tkwin:TTk_Window; str:Pchar):TPixmap;cdecl;external libtkstub8_6;
function Tk_GetBitmapFromData(interp:PTcl_Interp; tkwin:TTk_Window; source:pointer; width:longint; height:longint):TPixmap;cdecl;external libtkstub8_6;
function Tk_GetCapStyle(interp:PTcl_Interp; str:Pchar; capPtr:Plongint):longint;cdecl;external libtkstub8_6;
function Tk_GetColor(interp:PTcl_Interp; tkwin:TTk_Window; name:TTk_Uid):PXColor;cdecl;external libtkstub8_6;
function Tk_GetColorByValue(tkwin:TTk_Window; colorPtr:PXColor):PXColor;cdecl;external libtkstub8_6;
function Tk_GetColormap(interp:PTcl_Interp; tkwin:TTk_Window; str:Pchar):TColormap;cdecl;external libtkstub8_6;
function Tk_GetCursor(interp:PTcl_Interp; tkwin:TTk_Window; str:TTk_Uid):TTk_Cursor;cdecl;external libtkstub8_6;
function Tk_GetCursorFromData(interp:PTcl_Interp; tkwin:TTk_Window; source:Pchar; mask:Pchar; width:longint;
           height:longint; xHot:longint; yHot:longint; fg:TTk_Uid; bg:TTk_Uid):TTk_Cursor;cdecl;external libtkstub8_6;
function Tk_GetFont(interp:PTcl_Interp; tkwin:TTk_Window; str:Pchar):TTk_Font;cdecl;external libtkstub8_6;
function Tk_GetFontFromObj(tkwin:TTk_Window; objPtr:PTcl_Obj):TTk_Font;cdecl;external libtkstub8_6;
procedure Tk_GetFontMetrics(font:TTk_Font; fmPtr:PTk_FontMetrics);cdecl;external libtkstub8_6;
function Tk_GetGC(tkwin:TTk_Window; valueMask:dword; valuePtr:PXGCValues):TGC;cdecl;external libtkstub8_6;
function Tk_GetImage(interp:PTcl_Interp; tkwin:TTk_Window; name:Pchar; changeProc:TTk_ImageChangedProc; clientData:TClientData):TTk_Image;cdecl;external libtkstub8_6;
function Tk_GetImageMasterData(interp:PTcl_Interp; name:Pchar; typePtrPtr:PPTk_ImageType):TClientData;cdecl;external libtkstub8_6;
function Tk_GetItemTypes:PTk_ItemType;cdecl;external libtkstub8_6;
function Tk_GetJoinStyle(interp:PTcl_Interp; str:Pchar; joinPtr:Plongint):longint;cdecl;external libtkstub8_6;
function Tk_GetJustify(interp:PTcl_Interp; str:Pchar; justifyPtr:PTk_Justify):longint;cdecl;external libtkstub8_6;
function Tk_GetNumMainWindows:longint;cdecl;external libtkstub8_6;
function Tk_GetOption(tkwin:TTk_Window; name:Pchar; className:Pchar):TTk_Uid;cdecl;external libtkstub8_6;
function Tk_GetPixels(interp:PTcl_Interp; tkwin:TTk_Window; str:Pchar; intPtr:Plongint):longint;cdecl;external libtkstub8_6;
function Tk_GetPixmap(display:PDisplay; d:TDrawable; width:longint; height:longint; depth:longint):TPixmap;cdecl;external libtkstub8_6;
function Tk_GetRelief(interp:PTcl_Interp; name:Pchar; reliefPtr:Plongint):longint;cdecl;external libtkstub8_6;
procedure Tk_GetRootCoords(tkwin:TTk_Window; xPtr:Plongint; yPtr:Plongint);cdecl;external libtkstub8_6;
function Tk_GetScrollInfo(interp:PTcl_Interp; argc:longint; argv:PPchar; dblPtr:Pdouble; intPtr:Plongint):longint;cdecl;external libtkstub8_6;
function Tk_GetScreenMM(interp:PTcl_Interp; tkwin:TTk_Window; str:Pchar; doublePtr:Pdouble):longint;cdecl;external libtkstub8_6;
function Tk_GetSelection(interp:PTcl_Interp; tkwin:TTk_Window; selection:TAtom; target:TAtom; proc:TTk_GetSelProc;
           clientData:TClientData):longint;cdecl;external libtkstub8_6;
function Tk_GetUid(str:Pchar):TTk_Uid;cdecl;external libtkstub8_6;
function Tk_GetVisual(interp:PTcl_Interp; tkwin:TTk_Window; str:Pchar; depthPtr:Plongint; colormapPtr:PColormap):PVisual;cdecl;external libtkstub8_6;
procedure Tk_GetVRootGeometry(tkwin:TTk_Window; xPtr:Plongint; yPtr:Plongint; widthPtr:Plongint; heightPtr:Plongint);cdecl;external libtkstub8_6;
function Tk_Grab(interp:PTcl_Interp; tkwin:TTk_Window; grabGlobal:longint):longint;cdecl;external libtkstub8_6;
procedure Tk_HandleEvent(eventPtr:PXEvent);cdecl;external libtkstub8_6;
function Tk_IdToWindow(display:PDisplay; window:TWindow):TTk_Window;cdecl;external libtkstub8_6;
procedure Tk_ImageChanged(model:TTk_ImageMaster; x:longint; y:longint; width:longint; height:longint;
            imageWidth:longint; imageHeight:longint);cdecl;external libtkstub8_6;
function Tk_Init(interp:PTcl_Interp):longint;cdecl;external libtkstub8_6;
function Tk_InternAtom(tkwin:TTk_Window; name:Pchar):TAtom;cdecl;external libtkstub8_6;
function Tk_IntersectTextLayout(layout:TTk_TextLayout; x:longint; y:longint; width:longint; height:longint):longint;cdecl;external libtkstub8_6;
procedure Tk_MaintainGeometry(window:TTk_Window; container:TTk_Window; x:longint; y:longint; width:longint;
            height:longint);cdecl;external libtkstub8_6;
function Tk_MainWindow(interp:PTcl_Interp):TTk_Window;cdecl;external libtkstub8_6;
procedure Tk_MakeWindowExist(tkwin:TTk_Window);cdecl;external libtkstub8_6;
procedure Tk_ManageGeometry(tkwin:TTk_Window; mgrPtr:PTk_GeomMgr; clientData:TClientData);cdecl;external libtkstub8_6;
procedure Tk_MapWindow(tkwin:TTk_Window);cdecl;external libtkstub8_6;
function Tk_MeasureChars(tkfont:TTk_Font; source:Pchar; numBytes:longint; maxPixels:longint; flags:longint;
           lengthPtr:Plongint):longint;cdecl;external libtkstub8_6;
procedure Tk_MoveResizeWindow(tkwin:TTk_Window; x:longint; y:longint; width:longint; height:longint);cdecl;external libtkstub8_6;
procedure Tk_MoveWindow(tkwin:TTk_Window; x:longint; y:longint);cdecl;external libtkstub8_6;
procedure Tk_MoveToplevelWindow(tkwin:TTk_Window; x:longint; y:longint);cdecl;external libtkstub8_6;
function Tk_NameOf3DBorder(border:TTk_3DBorder):Pchar;cdecl;external libtkstub8_6;
function Tk_NameOfAnchor(anchor:TTk_Anchor):Pchar;cdecl;external libtkstub8_6;
function Tk_NameOfBitmap(display:PDisplay; bitmap:TPixmap):Pchar;cdecl;external libtkstub8_6;
function Tk_NameOfCapStyle(cap:longint):Pchar;cdecl;external libtkstub8_6;
function Tk_NameOfColor(colorPtr:PXColor):Pchar;cdecl;external libtkstub8_6;
function Tk_NameOfCursor(display:PDisplay; cursor:TTk_Cursor):Pchar;cdecl;external libtkstub8_6;
function Tk_NameOfFont(font:TTk_Font):Pchar;cdecl;external libtkstub8_6;
function Tk_NameOfImage(model:TTk_ImageMaster):Pchar;cdecl;external libtkstub8_6;
function Tk_NameOfJoinStyle(join:longint):Pchar;cdecl;external libtkstub8_6;
function Tk_NameOfJustify(justify:TTk_Justify):Pchar;cdecl;external libtkstub8_6;
function Tk_NameOfRelief(relief:longint):Pchar;cdecl;external libtkstub8_6;
function Tk_NameToWindow(interp:PTcl_Interp; pathName:Pchar; tkwin:TTk_Window):TTk_Window;cdecl;external libtkstub8_6;
procedure Tk_OwnSelection(tkwin:TTk_Window; selection:TAtom; proc:TTk_LostSelProc; clientData:TClientData);cdecl;external libtkstub8_6;
function Tk_ParseArgv(interp:PTcl_Interp; tkwin:TTk_Window; argcPtr:Plongint; argv:PPchar; argTable:PTk_ArgvInfo;
           flags:longint):longint;cdecl;external libtkstub8_6;
procedure Tk_PhotoPutBlock_NoComposite(handle:TTk_PhotoHandle; blockPtr:PTk_PhotoImageBlock; x:longint; y:longint; width:longint;
            height:longint);cdecl;external libtkstub8_6;
procedure Tk_PhotoPutZoomedBlock_NoComposite(handle:TTk_PhotoHandle; blockPtr:PTk_PhotoImageBlock; x:longint; y:longint; width:longint;
            height:longint; zoomX:longint; zoomY:longint; subsampleX:longint; subsampleY:longint);cdecl;external libtkstub8_6;
function Tk_PhotoGetImage(handle:TTk_PhotoHandle; blockPtr:PTk_PhotoImageBlock):longint;cdecl;external libtkstub8_6;
procedure Tk_PhotoBlank(handle:TTk_PhotoHandle);cdecl;external libtkstub8_6;
procedure Tk_PhotoExpand_Panic(handle:TTk_PhotoHandle; width:longint; height:longint);cdecl;external libtkstub8_6;
procedure Tk_PhotoGetSize(handle:TTk_PhotoHandle; widthPtr:Plongint; heightPtr:Plongint);cdecl;external libtkstub8_6;
procedure Tk_PhotoSetSize_Panic(handle:TTk_PhotoHandle; width:longint; height:longint);cdecl;external libtkstub8_6;
function Tk_PointToChar(layout:TTk_TextLayout; x:longint; y:longint):longint;cdecl;external libtkstub8_6;
function Tk_PostscriptFontName(tkfont:TTk_Font; dsPtr:PTcl_DString):longint;cdecl;external libtkstub8_6;
procedure Tk_PreserveColormap(display:PDisplay; colormap:TColormap);cdecl;external libtkstub8_6;
procedure Tk_QueueWindowEvent(eventPtr:PXEvent; position:TTcl_QueuePosition);cdecl;external libtkstub8_6;
procedure Tk_RedrawImage(image:TTk_Image; imageX:longint; imageY:longint; width:longint; height:longint;
            drawable:TDrawable; drawableX:longint; drawableY:longint);cdecl;external libtkstub8_6;
procedure Tk_ResizeWindow(tkwin:TTk_Window; width:longint; height:longint);cdecl;external libtkstub8_6;
function Tk_RestackWindow(tkwin:TTk_Window; aboveBelow:longint; other:TTk_Window):longint;cdecl;external libtkstub8_6;
function Tk_RestrictEvents(proc:TTk_RestrictProc; arg:TClientData; prevArgPtr:PClientData):TTk_RestrictProc;cdecl;external libtkstub8_6;
function Tk_SafeInit(interp:PTcl_Interp):longint;cdecl;external libtkstub8_6;
function Tk_SetAppName(tkwin:TTk_Window; name:Pchar):Pchar;cdecl;external libtkstub8_6;
procedure Tk_SetBackgroundFromBorder(tkwin:TTk_Window; border:TTk_3DBorder);cdecl;external libtkstub8_6;
procedure Tk_SetClass(tkwin:TTk_Window; className:Pchar);cdecl;external libtkstub8_6;
procedure Tk_SetGrid(tkwin:TTk_Window; reqWidth:longint; reqHeight:longint; gridWidth:longint; gridHeight:longint);cdecl;external libtkstub8_6;
procedure Tk_SetInternalBorder(tkwin:TTk_Window; width:longint);cdecl;external libtkstub8_6;
procedure Tk_SetWindowBackground(tkwin:TTk_Window; pixel:dword);cdecl;external libtkstub8_6;
procedure Tk_SetWindowBackgroundPixmap(tkwin:TTk_Window; pixmap:TPixmap);cdecl;external libtkstub8_6;
procedure Tk_SetWindowBorder(tkwin:TTk_Window; pixel:dword);cdecl;external libtkstub8_6;
procedure Tk_SetWindowBorderWidth(tkwin:TTk_Window; width:longint);cdecl;external libtkstub8_6;
procedure Tk_SetWindowBorderPixmap(tkwin:TTk_Window; pixmap:TPixmap);cdecl;external libtkstub8_6;
procedure Tk_SetWindowColormap(tkwin:TTk_Window; colormap:TColormap);cdecl;external libtkstub8_6;
function Tk_SetWindowVisual(tkwin:TTk_Window; visual:PVisual; depth:longint; colormap:TColormap):longint;cdecl;external libtkstub8_6;
procedure Tk_SizeOfBitmap(display:PDisplay; bitmap:TPixmap; widthPtr:Plongint; heightPtr:Plongint);cdecl;external libtkstub8_6;
procedure Tk_SizeOfImage(image:TTk_Image; widthPtr:Plongint; heightPtr:Plongint);cdecl;external libtkstub8_6;
function Tk_StrictMotif(tkwin:TTk_Window):longint;cdecl;external libtkstub8_6;
procedure Tk_TextLayoutToPostscript(interp:PTcl_Interp; layout:TTk_TextLayout);cdecl;external libtkstub8_6;
function Tk_TextWidth(font:TTk_Font; str:Pchar; numBytes:longint):longint;cdecl;external libtkstub8_6;
procedure Tk_UndefineCursor(window:TTk_Window);cdecl;external libtkstub8_6;
procedure Tk_UnderlineChars(display:PDisplay; drawable:TDrawable; gc:TGC; tkfont:TTk_Font; source:Pchar;
            x:longint; y:longint; firstByte:longint; lastByte:longint);cdecl;external libtkstub8_6;
procedure Tk_UnderlineTextLayout(display:PDisplay; drawable:TDrawable; gc:TGC; layout:TTk_TextLayout; x:longint;
            y:longint; underline:longint);cdecl;external libtkstub8_6;
procedure Tk_Ungrab(tkwin:TTk_Window);cdecl;external libtkstub8_6;
procedure Tk_UnmaintainGeometry(window:TTk_Window; container:TTk_Window);cdecl;external libtkstub8_6;
procedure Tk_UnmapWindow(tkwin:TTk_Window);cdecl;external libtkstub8_6;
procedure Tk_UnsetGrid(tkwin:TTk_Window);cdecl;external libtkstub8_6;
procedure Tk_UpdatePointer(tkwin:TTk_Window; x:longint; y:longint; state:longint);cdecl;external libtkstub8_6;
function Tk_AllocBitmapFromObj(interp:PTcl_Interp; tkwin:TTk_Window; objPtr:PTcl_Obj):TPixmap;cdecl;external libtkstub8_6;
function Tk_Alloc3DBorderFromObj(interp:PTcl_Interp; tkwin:TTk_Window; objPtr:PTcl_Obj):TTk_3DBorder;cdecl;external libtkstub8_6;
function Tk_AllocColorFromObj(interp:PTcl_Interp; tkwin:TTk_Window; objPtr:PTcl_Obj):PXColor;cdecl;external libtkstub8_6;
function Tk_AllocCursorFromObj(interp:PTcl_Interp; tkwin:TTk_Window; objPtr:PTcl_Obj):TTk_Cursor;cdecl;external libtkstub8_6;
function Tk_AllocFontFromObj(interp:PTcl_Interp; tkwin:TTk_Window; objPtr:PTcl_Obj):TTk_Font;cdecl;external libtkstub8_6;
function Tk_CreateOptionTable(interp:PTcl_Interp; templatePtr:PTk_OptionSpec):TTk_OptionTable;cdecl;external libtkstub8_6;
procedure Tk_DeleteOptionTable(optionTable:TTk_OptionTable);cdecl;external libtkstub8_6;
procedure Tk_Free3DBorderFromObj(tkwin:TTk_Window; objPtr:PTcl_Obj);cdecl;external libtkstub8_6;
procedure Tk_FreeBitmapFromObj(tkwin:TTk_Window; objPtr:PTcl_Obj);cdecl;external libtkstub8_6;
procedure Tk_FreeColorFromObj(tkwin:TTk_Window; objPtr:PTcl_Obj);cdecl;external libtkstub8_6;
procedure Tk_FreeConfigOptions(recordPtr:Pchar; optionToken:TTk_OptionTable; tkwin:TTk_Window);cdecl;external libtkstub8_6;
procedure Tk_FreeSavedOptions(savePtr:PTk_SavedOptions);cdecl;external libtkstub8_6;
procedure Tk_FreeCursorFromObj(tkwin:TTk_Window; objPtr:PTcl_Obj);cdecl;external libtkstub8_6;
procedure Tk_FreeFontFromObj(tkwin:TTk_Window; objPtr:PTcl_Obj);cdecl;external libtkstub8_6;
function Tk_Get3DBorderFromObj(tkwin:TTk_Window; objPtr:PTcl_Obj):TTk_3DBorder;cdecl;external libtkstub8_6;
function Tk_GetAnchorFromObj(interp:PTcl_Interp; objPtr:PTcl_Obj; anchorPtr:PTk_Anchor):longint;cdecl;external libtkstub8_6;
function Tk_GetBitmapFromObj(tkwin:TTk_Window; objPtr:PTcl_Obj):TPixmap;cdecl;external libtkstub8_6;
function Tk_GetColorFromObj(tkwin:TTk_Window; objPtr:PTcl_Obj):PXColor;cdecl;external libtkstub8_6;
function Tk_GetCursorFromObj(tkwin:TTk_Window; objPtr:PTcl_Obj):TTk_Cursor;cdecl;external libtkstub8_6;
function Tk_GetOptionInfo(interp:PTcl_Interp; recordPtr:Pchar; optionTable:TTk_OptionTable; namePtr:PTcl_Obj; tkwin:TTk_Window):PTcl_Obj;cdecl;external libtkstub8_6;
function Tk_GetOptionValue(interp:PTcl_Interp; recordPtr:Pchar; optionTable:TTk_OptionTable; namePtr:PTcl_Obj; tkwin:TTk_Window):PTcl_Obj;cdecl;external libtkstub8_6;
function Tk_GetJustifyFromObj(interp:PTcl_Interp; objPtr:PTcl_Obj; justifyPtr:PTk_Justify):longint;cdecl;external libtkstub8_6;
function Tk_GetMMFromObj(interp:PTcl_Interp; tkwin:TTk_Window; objPtr:PTcl_Obj; doublePtr:Pdouble):longint;cdecl;external libtkstub8_6;
function Tk_GetPixelsFromObj(interp:PTcl_Interp; tkwin:TTk_Window; objPtr:PTcl_Obj; intPtr:Plongint):longint;cdecl;external libtkstub8_6;
function Tk_GetReliefFromObj(interp:PTcl_Interp; objPtr:PTcl_Obj; resultPtr:Plongint):longint;cdecl;external libtkstub8_6;
function Tk_GetScrollInfoObj(interp:PTcl_Interp; objc:longint; objv:PPTcl_Obj; dblPtr:Pdouble; intPtr:Plongint):longint;cdecl;external libtkstub8_6;
function Tk_InitOptions(interp:PTcl_Interp; recordPtr:Pchar; optionToken:TTk_OptionTable; tkwin:TTk_Window):longint;cdecl;external libtkstub8_6;
procedure Tk_MainEx(argc:longint; argv:PPchar; appInitProc:TTcl_AppInitProc; interp:PTcl_Interp);cdecl;external libtkstub8_6;
procedure Tk_RestoreSavedOptions(savePtr:PTk_SavedOptions);cdecl;external libtkstub8_6;
function Tk_SetOptions(interp:PTcl_Interp; recordPtr:Pchar; optionTable:TTk_OptionTable; objc:longint; objv:PPTcl_Obj;
           tkwin:TTk_Window; savePtr:PTk_SavedOptions; maskPtr:Plongint):longint;cdecl;external libtkstub8_6;
procedure Tk_InitConsoleChannels(interp:PTcl_Interp);cdecl;external libtkstub8_6;
function Tk_CreateConsoleWindow(interp:PTcl_Interp):longint;cdecl;external libtkstub8_6;
procedure Tk_CreateSmoothMethod(interp:PTcl_Interp; method:PTk_SmoothMethod);cdecl;external libtkstub8_6;
function Tk_GetDash(interp:PTcl_Interp; value:Pchar; dash:PTk_Dash):longint;cdecl;external libtkstub8_6;
procedure Tk_CreateOutline(outline:PTk_Outline);cdecl;external libtkstub8_6;
procedure Tk_DeleteOutline(display:PDisplay; outline:PTk_Outline);cdecl;external libtkstub8_6;
function Tk_ConfigOutlineGC(gcValues:PXGCValues; canvas:TTk_Canvas; item:PTk_Item; outline:PTk_Outline):longint;cdecl;external libtkstub8_6;
function Tk_ChangeOutlineGC(canvas:TTk_Canvas; item:PTk_Item; outline:PTk_Outline):longint;cdecl;external libtkstub8_6;
function Tk_ResetOutlineGC(canvas:TTk_Canvas; item:PTk_Item; outline:PTk_Outline):longint;cdecl;external libtkstub8_6;
function Tk_CanvasPsOutline(canvas:TTk_Canvas; item:PTk_Item; outline:PTk_Outline):longint;cdecl;external libtkstub8_6;
procedure Tk_SetTSOrigin(tkwin:TTk_Window; gc:TGC; x:longint; y:longint);cdecl;external libtkstub8_6;
function Tk_CanvasGetCoordFromObj(interp:PTcl_Interp; canvas:TTk_Canvas; obj:PTcl_Obj; doublePtr:Pdouble):longint;cdecl;external libtkstub8_6;
procedure Tk_CanvasSetOffset(canvas:TTk_Canvas; gc:TGC; offset:PTk_TSOffset);cdecl;external libtkstub8_6;
procedure Tk_DitherPhoto(handle:TTk_PhotoHandle; x:longint; y:longint; width:longint; height:longint);cdecl;external libtkstub8_6;
function Tk_PostscriptBitmap(interp:PTcl_Interp; tkwin:TTk_Window; psInfo:TTk_PostscriptInfo; bitmap:TPixmap; startX:longint;
           startY:longint; width:longint; height:longint):longint;cdecl;external libtkstub8_6;
function Tk_PostscriptColor(interp:PTcl_Interp; psInfo:TTk_PostscriptInfo; colorPtr:PXColor):longint;cdecl;external libtkstub8_6;
function Tk_PostscriptFont(interp:PTcl_Interp; psInfo:TTk_PostscriptInfo; font:TTk_Font):longint;cdecl;external libtkstub8_6;
function Tk_PostscriptImage(image:TTk_Image; interp:PTcl_Interp; tkwin:TTk_Window; psinfo:TTk_PostscriptInfo; x:longint;
           y:longint; width:longint; height:longint; prepass:longint):longint;cdecl;external libtkstub8_6;
procedure Tk_PostscriptPath(interp:PTcl_Interp; psInfo:TTk_PostscriptInfo; coordPtr:Pdouble; numPoints:longint);cdecl;external libtkstub8_6;
function Tk_PostscriptStipple(interp:PTcl_Interp; tkwin:TTk_Window; psInfo:TTk_PostscriptInfo; bitmap:TPixmap):longint;cdecl;external libtkstub8_6;
function Tk_PostscriptY(y:double; psInfo:TTk_PostscriptInfo):double;cdecl;external libtkstub8_6;
function Tk_PostscriptPhoto(interp:PTcl_Interp; blockPtr:PTk_PhotoImageBlock; psInfo:TTk_PostscriptInfo; width:longint; height:longint):longint;cdecl;external libtkstub8_6;
procedure Tk_CreateClientMessageHandler(proc:TTk_ClientMessageProc);cdecl;external libtkstub8_6;
procedure Tk_DeleteClientMessageHandler(proc:TTk_ClientMessageProc);cdecl;external libtkstub8_6;
function Tk_CreateAnonymousWindow(interp:PTcl_Interp; parent:TTk_Window; screenName:Pchar):TTk_Window;cdecl;external libtkstub8_6;
procedure Tk_SetClassProcs(tkwin:TTk_Window; procs:PTk_ClassProcs; instanceData:TClientData);cdecl;external libtkstub8_6;
procedure Tk_SetInternalBorderEx(tkwin:TTk_Window; left:longint; right:longint; top:longint; bottom:longint);cdecl;external libtkstub8_6;
procedure Tk_SetMinimumRequestSize(tkwin:TTk_Window; minWidth:longint; minHeight:longint);cdecl;external libtkstub8_6;
procedure Tk_SetCaretPos(tkwin:TTk_Window; x:longint; y:longint; height:longint);cdecl;external libtkstub8_6;
procedure Tk_PhotoPutBlock_Panic(handle:TTk_PhotoHandle; blockPtr:PTk_PhotoImageBlock; x:longint; y:longint; width:longint;
            height:longint; compRule:longint);cdecl;external libtkstub8_6;
procedure Tk_PhotoPutZoomedBlock_Panic(handle:TTk_PhotoHandle; blockPtr:PTk_PhotoImageBlock; x:longint; y:longint; width:longint;
            height:longint; zoomX:longint; zoomY:longint; subsampleX:longint; subsampleY:longint; 
            compRule:longint);cdecl;external libtkstub8_6;
function Tk_CollapseMotionEvents(display:PDisplay; collapse:longint):longint;cdecl;external libtkstub8_6;
function Tk_RegisterStyleEngine(name:Pchar; parent:TTk_StyleEngine):TTk_StyleEngine;cdecl;external libtkstub8_6;
function Tk_GetStyleEngine(name:Pchar):TTk_StyleEngine;cdecl;external libtkstub8_6;
function Tk_RegisterStyledElement(engine:TTk_StyleEngine; templatePtr:PTk_ElementSpec):longint;cdecl;external libtkstub8_6;
function Tk_GetElementId(name:Pchar):longint;cdecl;external libtkstub8_6;
function Tk_CreateStyle(name:Pchar; engine:TTk_StyleEngine; clientData:TClientData):TTk_Style;cdecl;external libtkstub8_6;
function Tk_GetStyle(interp:PTcl_Interp; name:Pchar):TTk_Style;cdecl;external libtkstub8_6;
procedure Tk_FreeStyle(style:TTk_Style);cdecl;external libtkstub8_6;
function Tk_NameOfStyle(style:TTk_Style):Pchar;cdecl;external libtkstub8_6;
function Tk_AllocStyleFromObj(interp:PTcl_Interp; objPtr:PTcl_Obj):TTk_Style;cdecl;external libtkstub8_6;
function Tk_GetStyleFromObj(objPtr:PTcl_Obj):TTk_Style;cdecl;external libtkstub8_6;
procedure Tk_FreeStyleFromObj(objPtr:PTcl_Obj);cdecl;external libtkstub8_6;
function Tk_GetStyledElement(style:TTk_Style; elementId:longint; optionTable:TTk_OptionTable):TTk_StyledElement;cdecl;external libtkstub8_6;
procedure Tk_GetElementSize(style:TTk_Style; element:TTk_StyledElement; recordPtr:Pchar; tkwin:TTk_Window; width:longint;
            height:longint; inner:longint; widthPtr:Plongint; heightPtr:Plongint);cdecl;external libtkstub8_6;
procedure Tk_GetElementBox(style:TTk_Style; element:TTk_StyledElement; recordPtr:Pchar; tkwin:TTk_Window; x:longint;
            y:longint; width:longint; height:longint; inner:longint; xPtr:Plongint; 
            yPtr:Plongint; widthPtr:Plongint; heightPtr:Plongint);cdecl;external libtkstub8_6;
function Tk_GetElementBorderWidth(style:TTk_Style; element:TTk_StyledElement; recordPtr:Pchar; tkwin:TTk_Window):longint;cdecl;external libtkstub8_6;
procedure Tk_DrawElement(style:TTk_Style; element:TTk_StyledElement; recordPtr:Pchar; tkwin:TTk_Window; d:TDrawable;
            x:longint; y:longint; width:longint; height:longint; state:longint);cdecl;external libtkstub8_6;
function Tk_PhotoExpand(interp:PTcl_Interp; handle:TTk_PhotoHandle; width:longint; height:longint):longint;cdecl;external libtkstub8_6;
function Tk_PhotoPutBlock(interp:PTcl_Interp; handle:TTk_PhotoHandle; blockPtr:PTk_PhotoImageBlock; x:longint; y:longint;
           width:longint; height:longint; compRule:longint):longint;cdecl;external libtkstub8_6;
function Tk_PhotoPutZoomedBlock(interp:PTcl_Interp; handle:TTk_PhotoHandle; blockPtr:PTk_PhotoImageBlock; x:longint; y:longint;
           width:longint; height:longint; zoomX:longint; zoomY:longint; subsampleX:longint; 
           subsampleY:longint; compRule:longint):longint;cdecl;external libtkstub8_6;
function Tk_PhotoSetSize(interp:PTcl_Interp; handle:TTk_PhotoHandle; width:longint; height:longint):longint;cdecl;external libtkstub8_6;
function Tk_GetUserInactiveTime(dpy:PDisplay):longint;cdecl;external libtkstub8_6;
procedure Tk_ResetUserInactiveTime(dpy:PDisplay);cdecl;external libtkstub8_6;
function Tk_Interp(tkwin:TTk_Window):PTcl_Interp;cdecl;external libtkstub8_6;
procedure Tk_CreateOldImageType(typePtr:PTk_ImageType);cdecl;external libtkstub8_6;
procedure Tk_CreateOldPhotoImageFormat(formatPtr:PTk_PhotoImageFormat);cdecl;external libtkstub8_6;
procedure TkUnusedStubEntry;cdecl;external libtkstub8_6;

type
  PTkStubHooks = ^TTkStubHooks;
  TTkStubHooks = record
    end;

  PTkStubs = ^TTkStubs;
  TTkStubs = record
    end;
  var
    tkStubsPtr : PTkStubs;cvar;external libtkstub8_6;


procedure Tk_MainExW(argc:longint; argv:PPwchar_t; appInitProc:TTcl_AppInitProc; interp:PTcl_Interp);cdecl;external libtkstub8_6;

function Tk_FreeStyleFromObj(objPtr : longint) : pointer;


// === Konventiert am: 15-4-25 13:26:52 ===


implementation


function Tk_FreeStyleFromObj(objPtr : longint) : pointer;
begin
  Tk_FreeStyleFromObj:=pointer(objPtr);
end;


end.
