

{$include cbor/configuration.inc}
{$include cbor/data.inc}
{$include cbor/common.inc}
{$include cbor/callbacks.inc}
{$include cbor/arrays.inc}
{$include cbor/bytestrings.inc}
{$include cbor/encoding.inc}
{$include cbor/floats_ctrls.inc}
{$include cbor/ints.inc}
{$include cbor/maps.inc}
{$include cbor/serialization.inc}
{$include cbor/streaming.inc}
{$include cbor/strings.inc}
{$include cbor/tags.inc}
{$include cbor/cbor.inc}

