

{$include colord/cd_version.inc}
{$include colord/cd_enum.inc}
{$include colord/cd_color.inc}
{$include colord/cd_math.inc}
{$include colord/cd_spectrum.inc}
{$include colord/cd_buffer.inc}
{$include colord/cd_edid.inc}               // cd_color
{$include colord/cd_icc.inc}                // cd_color, cd_edid,
{$include colord/cd_icc_store.inc}          // cd_icc
{$include colord/cd_icc_utils.inc}          // cd_icc, cd_math
{$include colord/cd_profile.inc}            // cd_icc
{$include colord/cd_profile_sync.inc}
{$include colord/cd_device.inc}
{$include colord/cd_device_sync.inc}        // cd_device
{$include colord/cd_sensor.inc}             // cd_color, cd_spectrum,
{$include colord/cd_client.inc}             // cd_sensor, cd_device
{$include colord/cd_client_sync.inc}        // cd_client, cd_icc, cd_device, cd_icc, cd_sensor
{$include colord/cd_dom.inc}
{$include colord/cd_interp.inc}
{$include colord/cd_interp_akima.inc}       // cd_interp
{$include colord/cd_interp_linear.inc}      // cd_interp
{$include colord/cd_it8.inc}                // cd_color, cd_math, cd_spectrum
{$include colord/cd_it8_utils.inc}          // cd_it8, cd_spectrum, cd_color
{$include colord/cd_quirk.inc}
{$include colord/cd_sensor_sync.inc}        // cd_sensor, cd_color, cd_spectrum
{$include colord/cd_transform.inc}



