

{$include fribidi/fribidi_common.inc}
{$include fribidi/fribidi_config.inc}
{$include fribidi/fribidi_types.inc}
{$include fribidi/fribidi_bidi_types.inc}
{$include fribidi/fribidi_joining_types.inc}
{$include fribidi/fribidi_flags.inc}
{$include fribidi/fribidi_arabic.inc}
{$include fribidi/fribidi.inc}
{$include fribidi/fribidi_bidi.inc}
{$include fribidi/fribidi_brackets.inc}
{$include fribidi/fribidi_char_sets.inc}
{$include fribidi/fribidi_joining.inc}
{$include fribidi/fribidi_mirroring.inc}
{$include fribidi/fribidi_shape.inc}
{$include fribidi/fribidi_unicode.inc}
{$include fribidi/fribidi_unicode_version.inc}
{$include fribidi/fribidi_deprecated.inc}

