
unit magick_config;
interface

{
  Automatically converted by H2Pas 1.0.0 from magick_config.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    magick_config.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{
  Copyright 1999 ImageMagick Studio LLC, a non-profit organization
  dedicated to making software imaging solutions freely available.

  You may not use this file except in compliance with the License.  You may
  obtain a copy of the License at

    https://imagemagick.org/script/license.php

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  MagickConfig not autogenerated (fixed stuff)
 }
{$ifndef MAGICKCORE_MAGICK_CONFIG_H}
{$define MAGICKCORE_MAGICK_CONFIG_H}
{$include "magick/magick-baseconfig.h"}
{ some path game  }
{$if !defined __CYGWIN__}
{$if defined (_WIN32) || defined (_WIN64) || defined (__MSDOS__) || defined (__DJGPP__) || defined (__OS2__)}
{ Use Windows separators on all _WIN32 defining
      environments, except Cygwin.  }

const
  MAGICKCORE_DIR_SEPARATOR_CHAR = '\\';  
  MAGICKCORE_DIR_SEPARATOR = '\\';  
  MAGICKCORE_PATH_SEPARATOR_CHAR = ';';  
  MAGICKCORE_PATH_SEPARATOR = ';';  
{$endif}
{$endif}
{ posix  }
{$ifndef MAGICKCORE_DIR_SEPARATOR_CHAR}
{ Assume that not having this is an indicator that all
      are missing.  }

const
  MAGICKCORE_DIR_SEPARATOR_CHAR = '/';  
  MAGICKCORE_DIR_SEPARATOR = '/';  
  MAGICKCORE_PATH_SEPARATOR_CHAR = ':';  
  MAGICKCORE_PATH_SEPARATOR = ':';  
{$endif}
{ !DIR_SEPARATOR_CHAR  }
{$endif}

implementation


end.
