unit version_major;

interface

uses
  fp_ffmpeg;

  {$IFDEF FPC}
  {$PACKRECORDS C}
  {$ENDIF}


const
  LIBAVFORMAT_VERSION_MAJOR = 60;

  FF_API_COMPUTE_PKT_FIELDS2 = LIBAVFORMAT_VERSION_MAJOR < 61;
  FF_API_GET_END_PTS = LIBAVFORMAT_VERSION_MAJOR < 61;
  FF_API_AVIODIRCONTEXT = LIBAVFORMAT_VERSION_MAJOR < 61;
  FF_API_AVFORMAT_IO_CLOSE = LIBAVFORMAT_VERSION_MAJOR < 61;
  FF_API_AVIO_WRITE_NONCONST = LIBAVFORMAT_VERSION_MAJOR < 61;
  FF_API_LAVF_SHORTEST = LIBAVFORMAT_VERSION_MAJOR < 61;
  FF_API_ALLOW_FLUSH = LIBAVFORMAT_VERSION_MAJOR < 61;
  FF_API_AVSTREAM_SIDE_DATA = LIBAVFORMAT_VERSION_MAJOR < 61;
  FF_API_R_FRAME_RATE = 1;

  // === Konventiert am: 14-12-25 15:21:29 ===


implementation



end.
