unit console_types;

interface

uses
  fp_tcod;

  {$IFDEF FPC}
  {$PACKRECORDS C}
  {$ENDIF}


type
  PTCOD_keycode_t = ^TTCOD_keycode_t;
  TTCOD_keycode_t = longint;

const
  TCODK_NONE = 0;
  TCODK_ESCAPE = 1;
  TCODK_BACKSPACE = 2;
  TCODK_TAB = 3;
  TCODK_ENTER = 4;
  TCODK_SHIFT = 5;
  TCODK_CONTROL = 6;
  TCODK_ALT = 7;
  TCODK_PAUSE = 8;
  TCODK_CAPSLOCK = 9;
  TCODK_PAGEUP = 10;
  TCODK_PAGEDOWN = 11;
  TCODK_END = 12;
  TCODK_HOME = 13;
  TCODK_UP = 14;
  TCODK_LEFT = 15;
  TCODK_RIGHT = 16;
  TCODK_DOWN = 17;
  TCODK_PRINTSCREEN = 18;
  TCODK_INSERT = 19;
  TCODK_DELETE = 20;
  TCODK_LWIN = 21;
  TCODK_RWIN = 22;
  TCODK_APPS = 23;
  TCODK_0 = 24;
  TCODK_1 = 25;
  TCODK_2 = 26;
  TCODK_3 = 27;
  TCODK_4 = 28;
  TCODK_5 = 29;
  TCODK_6 = 30;
  TCODK_7 = 31;
  TCODK_8 = 32;
  TCODK_9 = 33;
  TCODK_KP0 = 34;
  TCODK_KP1 = 35;
  TCODK_KP2 = 36;
  TCODK_KP3 = 37;
  TCODK_KP4 = 38;
  TCODK_KP5 = 39;
  TCODK_KP6 = 40;
  TCODK_KP7 = 41;
  TCODK_KP8 = 42;
  TCODK_KP9 = 43;
  TCODK_KPADD = 44;
  TCODK_KPSUB = 45;
  TCODK_KPDIV = 46;
  TCODK_KPMUL = 47;
  TCODK_KPDEC = 48;
  TCODK_KPENTER = 49;
  TCODK_F1 = 50;
  TCODK_F2 = 51;
  TCODK_F3 = 52;
  TCODK_F4 = 53;
  TCODK_F5 = 54;
  TCODK_F6 = 55;
  TCODK_F7 = 56;
  TCODK_F8 = 57;
  TCODK_F9 = 58;
  TCODK_F10 = 59;
  TCODK_F11 = 60;
  TCODK_F12 = 61;
  TCODK_NUMLOCK = 62;
  TCODK_SCROLLLOCK = 63;
  TCODK_SPACE = 64;
  TCODK_CHAR = 65;
  TCODK_TEXT = 66;

const
  TCOD_KEY_TEXT_SIZE = 32;

type
  TTCOD_key_t = record
    vk: TTCOD_keycode_t;
    c: char;
    text: array[0..(TCOD_KEY_TEXT_SIZE) - 1] of char;
    pressed: Tbool;
    lalt: Tbool;
    lctrl: Tbool;
    lmeta: Tbool;
    ralt: Tbool;
    rctrl: Tbool;
    rmeta: Tbool;
    shift: Tbool;
  end;
  PTCOD_key_t = ^TTCOD_key_t;

type
  PTCOD_chars_t = ^TTCOD_chars_t;
  TTCOD_chars_t = longint;

const
  TCOD_CHAR_HLINE = 196;
  TCOD_CHAR_VLINE = 179;
  TCOD_CHAR_NE = 191;
  TCOD_CHAR_NW = 218;
  TCOD_CHAR_SE = 217;
  TCOD_CHAR_SW = 192;
  TCOD_CHAR_TEEW = 180;
  TCOD_CHAR_TEEE = 195;
  TCOD_CHAR_TEEN = 193;
  TCOD_CHAR_TEES = 194;
  TCOD_CHAR_CROSS = 197;
  TCOD_CHAR_DHLINE = 205;
  TCOD_CHAR_DVLINE = 186;
  TCOD_CHAR_DNE = 187;
  TCOD_CHAR_DNW = 201;
  TCOD_CHAR_DSE = 188;
  TCOD_CHAR_DSW = 200;
  TCOD_CHAR_DTEEW = 185;
  TCOD_CHAR_DTEEE = 204;
  TCOD_CHAR_DTEEN = 202;
  TCOD_CHAR_DTEES = 203;
  TCOD_CHAR_DCROSS = 206;
  TCOD_CHAR_BLOCK1 = 176;
  TCOD_CHAR_BLOCK2 = 177;
  TCOD_CHAR_BLOCK3 = 178;
  TCOD_CHAR_ARROW_N = 24;
  TCOD_CHAR_ARROW_S = 25;
  TCOD_CHAR_ARROW_E = 26;
  TCOD_CHAR_ARROW_W = 27;
  TCOD_CHAR_ARROW2_N = 30;
  TCOD_CHAR_ARROW2_S = 31;
  TCOD_CHAR_ARROW2_E = 16;
  TCOD_CHAR_ARROW2_W = 17;
  TCOD_CHAR_DARROW_H = 29;
  TCOD_CHAR_DARROW_V = 18;
  TCOD_CHAR_CHECKBOX_UNSET = 224;
  TCOD_CHAR_CHECKBOX_SET = 225;
  TCOD_CHAR_RADIO_UNSET = 9;
  TCOD_CHAR_RADIO_SET = 10;
  TCOD_CHAR_SUBP_NW = 226;
  TCOD_CHAR_SUBP_NE = 227;
  TCOD_CHAR_SUBP_N = 228;
  TCOD_CHAR_SUBP_SE = 229;
  TCOD_CHAR_SUBP_DIAG = 230;
  TCOD_CHAR_SUBP_E = 231;
  TCOD_CHAR_SUBP_SW = 232;
  TCOD_CHAR_SMILIE = 1;
  TCOD_CHAR_SMILIE_INV = 2;
  TCOD_CHAR_HEART = 3;
  TCOD_CHAR_DIAMOND = 4;
  TCOD_CHAR_CLUB = 5;
  TCOD_CHAR_SPADE = 6;
  TCOD_CHAR_BULLET = 7;
  TCOD_CHAR_BULLET_INV = 8;
  TCOD_CHAR_MALE = 11;
  TCOD_CHAR_FEMALE = 12;
  TCOD_CHAR_NOTE = 13;
  TCOD_CHAR_NOTE_DOUBLE = 14;
  TCOD_CHAR_LIGHT = 15;
  TCOD_CHAR_EXCLAM_DOUBLE = 19;
  TCOD_CHAR_PILCROW = 20;
  TCOD_CHAR_SECTION = 21;
  TCOD_CHAR_POUND = 156;
  TCOD_CHAR_MULTIPLICATION = 158;
  TCOD_CHAR_FUNCTION = 159;
  TCOD_CHAR_RESERVED = 169;
  TCOD_CHAR_HALF = 171;
  TCOD_CHAR_ONE_QUARTER = 172;
  TCOD_CHAR_COPYRIGHT = 184;
  TCOD_CHAR_CENT = 189;
  TCOD_CHAR_YEN = 190;
  TCOD_CHAR_CURRENCY = 207;
  TCOD_CHAR_THREE_QUARTERS = 243;
  TCOD_CHAR_DIVISION = 246;
  TCOD_CHAR_GRADE = 248;
  TCOD_CHAR_UMLAUT = 249;
  TCOD_CHAR_POW1 = 251;
  TCOD_CHAR_POW3 = 252;
  TCOD_CHAR_POW2 = 253;
  TCOD_CHAR_BULLET_SQUARE = 254;

type
  PTCOD_key_status_t = ^TTCOD_key_status_t;
  TTCOD_key_status_t = longint;

const
  TCOD_KEY_PRESSED = 1;
  TCOD_KEY_RELEASED = 2;

type
  PTCOD_font_flags_t = ^TTCOD_font_flags_t;
  TTCOD_font_flags_t = longint;

const
  TCOD_FONT_LAYOUT_ASCII_INCOL = 1;
  TCOD_FONT_LAYOUT_ASCII_INROW = 2;
  TCOD_FONT_TYPE_GREYSCALE = 4;
  TCOD_FONT_TYPE_GRAYSCALE = 4;
  TCOD_FONT_LAYOUT_TCOD = 8;
  TCOD_FONT_LAYOUT_CP437 = 16;

type
  PTCOD_renderer_t = ^TTCOD_renderer_t;
  TTCOD_renderer_t = longint;

const
  TCOD_RENDERER_GLSL = 0;
  TCOD_RENDERER_OPENGL = 1;
  TCOD_RENDERER_SDL = 2;
  TCOD_RENDERER_SDL2 = 3;
  TCOD_RENDERER_OPENGL2 = 4;
  TCOD_NB_RENDERERS = 5;

  // === Konventiert am: 6-9-25 15:48:11 ===


implementation



end.
