

{$include vlc/libvlc_.inc}
{$include vlc/libvlc_version.inc}
{$include vlc/libvlc_renderer_discoverer.inc}
{$include vlc/libvlc_media.inc}
{$include vlc/libvlc_events.inc}
{$include vlc/libvlc_media_list.inc}
{$include vlc/libvlc_media_player.inc}
{$include vlc/libvlc_media_list_player.inc}
{$include vlc/libvlc_media_library.inc}
{$include vlc/libvlc_dialog.inc}
{$include vlc/libvlc_vlm.inc}
{$include vlc/libvlc_media_discoverer.inc}
{$include vlc/deprecated.inc}





