
unit gskenumtypes;
interface

{
  Automatically converted by H2Pas 1.0.0 from gskenumtypes.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    gskenumtypes.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
{$ifndef __GSK_ENUM_TYPES_H__}
{$define __GSK_ENUM_TYPES_H__}
{$include <gdk/gdk.h>}
{ enumerations from "gskenums.h"  }

function gsk_render_node_type_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_RENDER_NODE_TYPE : longint; { return type might be wrong }

function gsk_scaling_filter_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_SCALING_FILTER : longint; { return type might be wrong }

function gsk_blend_mode_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_BLEND_MODE : longint; { return type might be wrong }

function gsk_porter_duff_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_PORTER_DUFF : longint; { return type might be wrong }

function gsk_corner_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_CORNER : longint; { return type might be wrong }

function gsk_fill_rule_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_FILL_RULE : longint; { return type might be wrong }

function gsk_isolation_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_ISOLATION : longint; { return type might be wrong }

function gsk_line_cap_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_LINE_CAP : longint; { return type might be wrong }

function gsk_line_join_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_LINE_JOIN : longint; { return type might be wrong }

function gsk_path_operation_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_PATH_OPERATION : longint; { return type might be wrong }

function gsk_path_direction_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_PATH_DIRECTION : longint; { return type might be wrong }

function gsk_serialization_error_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_SERIALIZATION_ERROR : longint; { return type might be wrong }

function gsk_transform_category_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_TRANSFORM_CATEGORY : longint; { return type might be wrong }

function gsk_gl_uniform_type_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_GL_UNIFORM_TYPE : longint; { return type might be wrong }

function gsk_mask_mode_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_MASK_MODE : longint; { return type might be wrong }

{ enumerations from "gskpath.h"  }
function gsk_path_foreach_flags_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_PATH_FOREACH_FLAGS : longint; { return type might be wrong }

function gsk_path_intersection_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GSK_TYPE_PATH_INTERSECTION : longint; { return type might be wrong }

{$endif}
{ __GSK_ENUM_TYPES_H__  }
{ Generated data ends here  }

implementation

{ was #define dname def_expr }
function GSK_TYPE_RENDER_NODE_TYPE : longint; { return type might be wrong }
  begin
    GSK_TYPE_RENDER_NODE_TYPE:=gsk_render_node_type_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_SCALING_FILTER : longint; { return type might be wrong }
  begin
    GSK_TYPE_SCALING_FILTER:=gsk_scaling_filter_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_BLEND_MODE : longint; { return type might be wrong }
  begin
    GSK_TYPE_BLEND_MODE:=gsk_blend_mode_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_PORTER_DUFF : longint; { return type might be wrong }
  begin
    GSK_TYPE_PORTER_DUFF:=gsk_porter_duff_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_CORNER : longint; { return type might be wrong }
  begin
    GSK_TYPE_CORNER:=gsk_corner_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_FILL_RULE : longint; { return type might be wrong }
  begin
    GSK_TYPE_FILL_RULE:=gsk_fill_rule_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_ISOLATION : longint; { return type might be wrong }
  begin
    GSK_TYPE_ISOLATION:=gsk_isolation_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_LINE_CAP : longint; { return type might be wrong }
  begin
    GSK_TYPE_LINE_CAP:=gsk_line_cap_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_LINE_JOIN : longint; { return type might be wrong }
  begin
    GSK_TYPE_LINE_JOIN:=gsk_line_join_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_PATH_OPERATION : longint; { return type might be wrong }
  begin
    GSK_TYPE_PATH_OPERATION:=gsk_path_operation_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_PATH_DIRECTION : longint; { return type might be wrong }
  begin
    GSK_TYPE_PATH_DIRECTION:=gsk_path_direction_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_SERIALIZATION_ERROR : longint; { return type might be wrong }
  begin
    GSK_TYPE_SERIALIZATION_ERROR:=gsk_serialization_error_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_TRANSFORM_CATEGORY : longint; { return type might be wrong }
  begin
    GSK_TYPE_TRANSFORM_CATEGORY:=gsk_transform_category_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_GL_UNIFORM_TYPE : longint; { return type might be wrong }
  begin
    GSK_TYPE_GL_UNIFORM_TYPE:=gsk_gl_uniform_type_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_MASK_MODE : longint; { return type might be wrong }
  begin
    GSK_TYPE_MASK_MODE:=gsk_mask_mode_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_PATH_FOREACH_FLAGS : longint; { return type might be wrong }
  begin
    GSK_TYPE_PATH_FOREACH_FLAGS:=gsk_path_foreach_flags_get_type;
  end;

{ was #define dname def_expr }
function GSK_TYPE_PATH_INTERSECTION : longint; { return type might be wrong }
  begin
    GSK_TYPE_PATH_INTERSECTION:=gsk_path_intersection_get_type;
  end;


end.
