unit magick_image;

interface

uses
  fp_magiccore, fp_magicwand, MagickWand, drawing_wand, pixel_wand;

  {$IFDEF FPC}
  {$PACKRECORDS C}
  {$ENDIF}


function MagickGetImageChannelFeatures(para1: PMagickWand; para2: Tsize_t): PChannelFeatures; cdecl; external libmagickwand;
function MagickGetImageChannelStatistics(para1: PMagickWand): PChannelStatistics; cdecl; external libmagickwand;
function MagickGetImageFilename(para1: PMagickWand): pchar; cdecl; external libmagickwand;
function MagickGetImageFormat(para1: PMagickWand): pchar; cdecl; external libmagickwand;
function MagickGetImageSignature(para1: PMagickWand): pchar; cdecl; external libmagickwand;
function MagickIdentifyImage(para1: PMagickWand): pchar; cdecl; external libmagickwand;
function MagickGetImageColorspace(para1: PMagickWand): TColorspaceType; cdecl; external libmagickwand;
function MagickGetImageCompose(para1: PMagickWand): TCompositeOperator; cdecl; external libmagickwand;
function MagickGetImageCompression(para1: PMagickWand): TCompressionType; cdecl; external libmagickwand;
function MagickGetImageDispose(para1: PMagickWand): TDisposeType; cdecl; external libmagickwand;
function MagickGetImageChannelDistortions(para1: PMagickWand; para2: PMagickWand; para3: TMetricType): Pdouble; cdecl; external libmagickwand;
function MagickGetImageFuzz(para1: PMagickWand): double; cdecl; external libmagickwand;
function MagickGetImageGamma(para1: PMagickWand): double; cdecl; external libmagickwand;
function MagickGetImageTotalInkDensity(para1: PMagickWand): double; cdecl; external libmagickwand;
function MagickGetImageEndian(para1: PMagickWand): TEndianType; cdecl; external libmagickwand;
function MagickGetImageGravity(para1: PMagickWand): TGravityType; cdecl; external libmagickwand;
function MagickDestroyImage(para1: PImage): PImage; cdecl; external libmagickwand;
function GetImageFromMagickWand(para1: PMagickWand): PImage; cdecl; external libmagickwand;
function MagickGetImageType(para1: PMagickWand): TImageType; cdecl; external libmagickwand;
function MagickGetImageInterlaceScheme(para1: PMagickWand): TInterlaceType; cdecl; external libmagickwand;
function MagickGetImageInterpolateMethod(para1: PMagickWand): TInterpolatePixelMethod; cdecl; external libmagickwand;
function MagickAdaptiveBlurImage(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAdaptiveBlurImageChannel(para1: PMagickWand; para2: TChannelType; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAdaptiveResizeImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAdaptiveSharpenImage(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAdaptiveSharpenImageChannel(para1: PMagickWand; para2: TChannelType; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAdaptiveThresholdImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t; para4: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAddImage(para1: PMagickWand; para2: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAddNoiseImage(para1: PMagickWand; para2: TNoiseType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAddNoiseImageChannel(para1: PMagickWand; para2: TChannelType; para3: TNoiseType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAffineTransformImage(para1: PMagickWand; para2: PDrawingWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAnnotateImage(para1: PMagickWand; para2: PDrawingWand; para3: double; para4: double; para5: double;
  para6: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAnimateImages(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAutoGammaImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAutoGammaImageChannel(para1: PMagickWand; para2: TChannelType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAutoLevelImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAutoLevelImageChannel(para1: PMagickWand; para2: TChannelType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickAutoOrientImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickBlackThresholdImage(para1: PMagickWand; para2: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickBlueShiftImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickBlurImage(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickBlurImageChannel(para1: PMagickWand; para2: TChannelType; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickBorderImage(para1: PMagickWand; para2: PPixelWand; para3: Tsize_t; para4: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickBrightnessContrastImage(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickBrightnessContrastImageChannel(para1: PMagickWand; para2: TChannelType; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickCharcoalImage(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickChopImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t; para4: Tssize_t; para5: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickClampImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickClampImageChannel(para1: PMagickWand; para2: TChannelType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickClipImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickClipImagePath(para1: PMagickWand; para2: pchar; para3: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickClutImage(para1: PMagickWand; para2: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickClutImageChannel(para1: PMagickWand; para2: TChannelType; para3: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickColorDecisionListImage(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickColorizeImage(para1: PMagickWand; para2: PPixelWand; para3: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickColorMatrixImage(para1: PMagickWand; para2: PKernelInfo): TMagickBooleanType; cdecl; external libmagickwand;
function MagickCommentImage(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickCompositeImage(para1: PMagickWand; para2: PMagickWand; para3: TCompositeOperator; para4: Tssize_t; para5: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickCompositeImageChannel(para1: PMagickWand; para2: TChannelType; para3: PMagickWand; para4: TCompositeOperator; para5: Tssize_t;
  para6: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickCompositeImageGravity(para1: PMagickWand; para2: PMagickWand; para3: TCompositeOperator; para4: TGravityType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickCompositeLayers(para1: PMagickWand; para2: PMagickWand; para3: TCompositeOperator; para4: Tssize_t; para5: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickConstituteImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t; para4: pchar; para5: TStorageType;
  para6: pointer): TMagickBooleanType; cdecl; external libmagickwand;
function MagickContrastImage(para1: PMagickWand; para2: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickContrastStretchImage(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickContrastStretchImageChannel(para1: PMagickWand; para2: TChannelType; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickConvolveImage(para1: PMagickWand; para2: Tsize_t; para3: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickConvolveImageChannel(para1: PMagickWand; para2: TChannelType; para3: Tsize_t; para4: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickCropImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t; para4: Tssize_t; para5: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickCycleColormapImage(para1: PMagickWand; para2: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickDecipherImage(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickDeskewImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickDespeckleImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickDisplayImage(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickDisplayImages(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickDistortImage(para1: PMagickWand; para2: TDistortImageMethod; para3: Tsize_t; para4: Pdouble; para5: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickDrawImage(para1: PMagickWand; para2: PDrawingWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickEdgeImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickEmbossImage(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickEncipherImage(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickEnhanceImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickEqualizeImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickEqualizeImageChannel(para1: PMagickWand; para2: TChannelType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickEvaluateImage(para1: PMagickWand; para2: TMagickEvaluateOperator; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickEvaluateImageChannel(para1: PMagickWand; para2: TChannelType; para3: TMagickEvaluateOperator; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickExportImagePixels(para1: PMagickWand; para2: Tssize_t; para3: Tssize_t; para4: Tsize_t; para5: Tsize_t;
  para6: pchar; para7: TStorageType; para8: pointer): TMagickBooleanType; cdecl; external libmagickwand;
function MagickExtentImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t; para4: Tssize_t; para5: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickFilterImage(para1: PMagickWand; para2: PKernelInfo): TMagickBooleanType; cdecl; external libmagickwand;
function MagickFilterImageChannel(para1: PMagickWand; para2: TChannelType; para3: PKernelInfo): TMagickBooleanType; cdecl; external libmagickwand;
function MagickFlipImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickFloodfillPaintImage(para1: PMagickWand; para2: TChannelType; para3: PPixelWand; para4: double; para5: PPixelWand;
  para6: Tssize_t; para7: Tssize_t; para8: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickFlopImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickForwardFourierTransformImage(para1: PMagickWand; para2: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickFrameImage(para1: PMagickWand; para2: PPixelWand; para3: Tsize_t; para4: Tsize_t; para5: Tssize_t;
  para6: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickFunctionImage(para1: PMagickWand; para2: TMagickFunction; para3: Tsize_t; para4: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickFunctionImageChannel(para1: PMagickWand; para2: TChannelType; para3: TMagickFunction; para4: Tsize_t; para5: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGammaImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGammaImageChannel(para1: PMagickWand; para2: TChannelType; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGaussianBlurImage(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGaussianBlurImageChannel(para1: PMagickWand; para2: TChannelType; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageAlphaChannel(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageBackgroundColor(para1: PMagickWand; para2: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageBluePrimary(para1: PMagickWand; para2: Pdouble; para3: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageBorderColor(para1: PMagickWand; para2: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageChannelDistortion(para1: PMagickWand; para2: PMagickWand; para3: TChannelType; para4: TMetricType; para5: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageChannelKurtosis(para1: PMagickWand; para2: TChannelType; para3: Pdouble; para4: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageChannelMean(para1: PMagickWand; para2: TChannelType; para3: Pdouble; para4: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageChannelRange(para1: PMagickWand; para2: TChannelType; para3: Pdouble; para4: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageColormapColor(para1: PMagickWand; para2: Tsize_t; para3: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageDistortion(para1: PMagickWand; para2: PMagickWand; para3: TMetricType; para4: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageGreenPrimary(para1: PMagickWand; para2: Pdouble; para3: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageMatteColor(para1: PMagickWand; para2: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageLength(para1: PMagickWand; para2: PMagickSizeType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImagePage(para1: PMagickWand; para2: Psize_t; para3: Psize_t; para4: Pssize_t; para5: Pssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImagePixelColor(para1: PMagickWand; para2: Tssize_t; para3: Tssize_t; para4: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageRange(para1: PMagickWand; para2: Pdouble; para3: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageRedPrimary(para1: PMagickWand; para2: Pdouble; para3: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageResolution(para1: PMagickWand; para2: Pdouble; para3: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageWhitePoint(para1: PMagickWand; para2: Pdouble; para3: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickHaldClutImage(para1: PMagickWand; para2: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickHaldClutImageChannel(para1: PMagickWand; para2: TChannelType; para3: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickHasNextImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickHasPreviousImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickImplodeImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickImportImagePixels(para1: PMagickWand; para2: Tssize_t; para3: Tssize_t; para4: Tsize_t; para5: Tsize_t;
  para6: pchar; para7: TStorageType; para8: pointer): TMagickBooleanType; cdecl; external libmagickwand;
function MagickInverseFourierTransformImage(para1: PMagickWand; para2: PMagickWand; para3: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickLabelImage(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickLevelImage(para1: PMagickWand; para2: double; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickLevelImageChannel(para1: PMagickWand; para2: TChannelType; para3: double; para4: double; para5: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickLevelImageColors(para1: PMagickWand; para2: PPixelWand; para3: PPixelWand; para4: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickLevelImageColorsChannel(para1: PMagickWand; para2: TChannelType; para3: PPixelWand; para4: PPixelWand; para5: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickLevelizeImage(para1: PMagickWand; para2: double; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickLevelizeImageChannel(para1: PMagickWand; para2: TChannelType; para3: double; para4: double; para5: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickLinearStretchImage(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickLiquidRescaleImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t; para4: double; para5: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickLocalContrastImage(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickMagnifyImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickMedianFilterImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickMinifyImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickModeImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickModulateImage(para1: PMagickWand; para2: double; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickMorphologyImage(para1: PMagickWand; para2: TMorphologyMethod; para3: Tssize_t; para4: PKernelInfo): TMagickBooleanType; cdecl; external libmagickwand;
function MagickMorphologyImageChannel(para1: PMagickWand; para2: TChannelType; para3: TMorphologyMethod; para4: Tssize_t; para5: PKernelInfo): TMagickBooleanType; cdecl; external libmagickwand;
function MagickMotionBlurImage(para1: PMagickWand; para2: double; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickMotionBlurImageChannel(para1: PMagickWand; para2: TChannelType; para3: double; para4: double; para5: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickNegateImage(para1: PMagickWand; para2: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickNegateImageChannel(para1: PMagickWand; para2: TChannelType; para3: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickNewImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t; para4: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickNextImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickNormalizeImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickNormalizeImageChannel(para1: PMagickWand; para2: TChannelType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickOilPaintImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickOpaquePaintImage(para1: PMagickWand; para2: PPixelWand; para3: PPixelWand; para4: double; para5: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickOpaquePaintImageChannel(para1: PMagickWand; para2: TChannelType; para3: PPixelWand; para4: PPixelWand; para5: double;
  para6: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickOrderedPosterizeImage(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickOrderedPosterizeImageChannel(para1: PMagickWand; para2: TChannelType; para3: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickOptimizeImageTransparency(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickTransparentPaintImage(para1: PMagickWand; para2: PPixelWand; para3: double; para4: double; invert: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickPingImage(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickPingImageBlob(para1: PMagickWand; para2: pointer; para3: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickPingImageFile(para1: PMagickWand; para2: PFILE): TMagickBooleanType; cdecl; external libmagickwand;
function MagickPolaroidImage(para1: PMagickWand; para2: PDrawingWand; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickPosterizeImage(para1: PMagickWand; para2: Tsize_t; para3: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickPreviousImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickQuantizeImage(para1: PMagickWand; para2: Tsize_t; para3: TColorspaceType; para4: Tsize_t; para5: TMagickBooleanType;
  para6: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickQuantizeImages(para1: PMagickWand; para2: Tsize_t; para3: TColorspaceType; para4: Tsize_t; para5: TMagickBooleanType;
  para6: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickRaiseImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t; para4: Tssize_t; para5: Tssize_t;
  para6: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickRandomThresholdImage(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickRandomThresholdImageChannel(para1: PMagickWand; para2: TChannelType; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickReadImage(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickReadImageBlob(para1: PMagickWand; para2: pointer; para3: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickReadImageFile(para1: PMagickWand; para2: PFILE): TMagickBooleanType; cdecl; external libmagickwand;
function MagickReduceNoiseImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickRemapImage(para1: PMagickWand; para2: PMagickWand; para3: TDitherMethod): TMagickBooleanType; cdecl; external libmagickwand;
function MagickRemoveImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickResampleImage(para1: PMagickWand; para2: double; para3: double; para4: TFilterTypes; para5: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickResetImagePage(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickResizeImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t; para4: TFilterTypes; para5: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickRollImage(para1: PMagickWand; para2: Tssize_t; para3: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickRotateImage(para1: PMagickWand; para2: PPixelWand; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickRotationalBlurImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickRotationalBlurImageChannel(para1: PMagickWand; para2: TChannelType; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSampleImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickScaleImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSegmentImage(para1: PMagickWand; para2: TColorspaceType; para3: TMagickBooleanType; para4: double; para5: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSelectiveBlurImage(para1: PMagickWand; para2: double; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSelectiveBlurImageChannel(para1: PMagickWand; para2: TChannelType; para3: double; para4: double; para5: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSeparateImageChannel(para1: PMagickWand; para2: TChannelType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSepiaToneImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImage(para1: PMagickWand; para2: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageAlphaChannel(para1: PMagickWand; para2: TAlphaChannelType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageBackgroundColor(para1: PMagickWand; para2: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageBias(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageBluePrimary(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageBorderColor(para1: PMagickWand; para2: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageChannelDepth(para1: PMagickWand; para2: TChannelType; para3: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageClipMask(para1: PMagickWand; para2: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageColor(para1: PMagickWand; para2: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageColormapColor(para1: PMagickWand; para2: Tsize_t; para3: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageColorspace(para1: PMagickWand; para2: TColorspaceType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageCompose(para1: PMagickWand; para2: TCompositeOperator): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageCompression(para1: PMagickWand; para2: TCompressionType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageDelay(para1: PMagickWand; para2: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageDepth(para1: PMagickWand; para2: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageDispose(para1: PMagickWand; para2: TDisposeType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageCompressionQuality(para1: PMagickWand; para2: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageEndian(para1: PMagickWand; para2: TEndianType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageExtent(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageFilename(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageFormat(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageFuzz(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageGamma(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageGravity(para1: PMagickWand; para2: TGravityType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageGreenPrimary(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageInterlaceScheme(para1: PMagickWand; para2: TInterlaceType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageInterpolateMethod(para1: PMagickWand; para2: TInterpolatePixelMethod): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageIterations(para1: PMagickWand; para2: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageMatte(para1: PMagickWand; para2: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageMatteColor(para1: PMagickWand; para2: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageOpacity(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageOrientation(para1: PMagickWand; para2: TOrientationType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImagePage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t; para4: Tssize_t; para5: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageRedPrimary(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageRenderingIntent(para1: PMagickWand; para2: TRenderingIntent): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageResolution(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageScene(para1: PMagickWand; para2: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImagePixelColor(para1: PMagickWand; para2: Tssize_t; para3: Tssize_t; para4: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageTicksPerSecond(para1: PMagickWand; para2: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageType(para1: PMagickWand; para2: TImageType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageUnits(para1: PMagickWand; para2: TResolutionType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageWhitePoint(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickShadeImage(para1: PMagickWand; para2: TMagickBooleanType; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickShadowImage(para1: PMagickWand; para2: double; para3: double; para4: Tssize_t; para5: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSharpenImage(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSharpenImageChannel(para1: PMagickWand; para2: TChannelType; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickShaveImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickShearImage(para1: PMagickWand; para2: PPixelWand; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSigmoidalContrastImage(para1: PMagickWand; para2: TMagickBooleanType; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSigmoidalContrastImageChannel(para1: PMagickWand; para2: TChannelType; para3: TMagickBooleanType; para4: double; para5: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSketchImage(para1: PMagickWand; para2: double; para3: double; para4: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSolarizeImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSolarizeImageChannel(para1: PMagickWand; para2: TChannelType; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSparseColorImage(para1: PMagickWand; para2: TChannelType; para3: TSparseColorMethod; para4: Tsize_t; para5: Pdouble): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSpliceImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t; para4: Tssize_t; para5: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSpreadImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickStatisticImage(para1: PMagickWand; para2: TStatisticType; para3: Tsize_t; para4: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickStatisticImageChannel(para1: PMagickWand; para2: TChannelType; para3: TStatisticType; para4: Tsize_t; para5: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickStripImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSwirlImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickTintImage(para1: PMagickWand; para2: PPixelWand; para3: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickTransformImageColorspace(para1: PMagickWand; para2: TColorspaceType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickTransposeImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickTransverseImage(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickThresholdImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickThresholdImageChannel(para1: PMagickWand; para2: TChannelType; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickThumbnailImage(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickTrimImage(para1: PMagickWand; para2: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickUniqueImageColors(para1: PMagickWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickUnsharpMaskImage(para1: PMagickWand; para2: double; para3: double; para4: double; para5: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickUnsharpMaskImageChannel(para1: PMagickWand; para2: TChannelType; para3: double; para4: double; para5: double;
  para6: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickVignetteImage(para1: PMagickWand; para2: double; para3: double; para4: Tssize_t; para5: Tssize_t): TMagickBooleanType; cdecl; external libmagickwand;
function MagickWaveImage(para1: PMagickWand; para2: double; para3: double): TMagickBooleanType; cdecl; external libmagickwand;
function MagickWhiteThresholdImage(para1: PMagickWand; para2: PPixelWand): TMagickBooleanType; cdecl; external libmagickwand;
function MagickWriteImage(para1: PMagickWand; para2: pchar): TMagickBooleanType; cdecl; external libmagickwand;
function MagickWriteImageFile(para1: PMagickWand; para2: PFILE): TMagickBooleanType; cdecl; external libmagickwand;
function MagickWriteImages(para1: PMagickWand; para2: pchar; para3: TMagickBooleanType): TMagickBooleanType; cdecl; external libmagickwand;
function MagickWriteImagesFile(para1: PMagickWand; para2: PFILE): TMagickBooleanType; cdecl; external libmagickwand;
function MagickSetImageProgressMonitor(para1: PMagickWand; para2: TMagickProgressMonitor; para3: pointer): TMagickProgressMonitor; cdecl; external libmagickwand;
function MagickAppendImages(para1: PMagickWand; para2: TMagickBooleanType): PMagickWand; cdecl; external libmagickwand;
function MagickCoalesceImages(para1: PMagickWand): PMagickBooleanType; cdecl; external libmagickwand;
function MagickCombineImages(para1: PMagickWand; para2: TChannelType): PMagickBooleanType; cdecl; external libmagickwand;
function MagickCompareImageChannels(para1: PMagickWand; para2: PMagickWand; para3: TChannelType; para4: TMetricType; para5: Pdouble): PMagickBooleanType; cdecl; external libmagickwand;
function MagickCompareImages(para1: PMagickWand; para2: PMagickWand; para3: TMetricType; para4: Pdouble): PMagickBooleanType; cdecl; external libmagickwand;
function MagickCompareImageLayers(para1: PMagickWand; para2: TImageLayerMethod): PMagickBooleanType; cdecl; external libmagickwand;
function MagickDeconstructImages(para1: PMagickWand): PMagickBooleanType; cdecl; external libmagickwand;
function MagickEvaluateImages(para1: PMagickWand; para2: TMagickEvaluateOperator): PMagickBooleanType; cdecl; external libmagickwand;
function MagickFxImage(para1: PMagickWand; para2: pchar): PMagickBooleanType; cdecl; external libmagickwand;
function MagickFxImageChannel(para1: PMagickWand; para2: TChannelType; para3: pchar): PMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImage(para1: PMagickWand): PMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageClipMask(para1: PMagickWand): PMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageRegion(para1: PMagickWand; para2: Tsize_t; para3: Tsize_t; para4: Tssize_t; para5: Tssize_t): PMagickBooleanType; cdecl; external libmagickwand;
function MagickMergeImageLayers(para1: PMagickWand; para2: TImageLayerMethod): PMagickBooleanType; cdecl; external libmagickwand;
function MagickMorphImages(para1: PMagickWand; para2: Tsize_t): PMagickBooleanType; cdecl; external libmagickwand;
function MagickMontageImage(para1: PMagickWand; para2: PDrawingWand; para3: pchar; para4: pchar; para5: TMontageMode;
  para6: pchar): PMagickBooleanType; cdecl; external libmagickwand;
function MagickOptimizeImageLayers(para1: PMagickWand): PMagickBooleanType; cdecl; external libmagickwand;
function MagickPreviewImages(wand: PMagickWand; para2: TPreviewType): PMagickBooleanType; cdecl; external libmagickwand;
function MagickSimilarityImage(para1: PMagickWand; para2: PMagickWand; para3: PRectangleInfo; para4: Pdouble): PMagickBooleanType; cdecl; external libmagickwand;
function MagickSmushImages(para1: PMagickWand; para2: TMagickBooleanType; para3: Tssize_t): PMagickBooleanType; cdecl; external libmagickwand;
function MagickSteganoImage(para1: PMagickWand; para2: PMagickWand; para3: Tssize_t): PMagickBooleanType; cdecl; external libmagickwand;
function MagickStereoImage(para1: PMagickWand; para2: PMagickWand): PMagickBooleanType; cdecl; external libmagickwand;
function MagickTextureImage(para1: PMagickWand; para2: PMagickWand): PMagickBooleanType; cdecl; external libmagickwand;
function MagickTransformImage(para1: PMagickWand; para2: pchar; para3: pchar): PMagickBooleanType; cdecl; external libmagickwand;
function MagickGetImageOrientation(para1: PMagickWand): TOrientationType; cdecl; external libmagickwand;
function MagickGetImageHistogram(para1: PMagickWand; para2: Psize_t): PPPixelWand; cdecl; external libmagickwand;
function MagickGetImageRenderingIntent(para1: PMagickWand): TRenderingIntent; cdecl; external libmagickwand;
function MagickGetImageUnits(para1: PMagickWand): TResolutionType; cdecl; external libmagickwand;
function MagickGetImageColors(para1: PMagickWand): Tsize_t; cdecl; external libmagickwand;
function MagickGetImageCompressionQuality(para1: PMagickWand): Tsize_t; cdecl; external libmagickwand;
function MagickGetImageDelay(para1: PMagickWand): Tsize_t; cdecl; external libmagickwand;
function MagickGetImageChannelDepth(para1: PMagickWand; para2: TChannelType): Tsize_t; cdecl; external libmagickwand;
function MagickGetImageDepth(para1: PMagickWand): Tsize_t; cdecl; external libmagickwand;
function MagickGetImageHeight(para1: PMagickWand): Tsize_t; cdecl; external libmagickwand;
function MagickGetImageIterations(para1: PMagickWand): Tsize_t; cdecl; external libmagickwand;
function MagickGetImageScene(para1: PMagickWand): Tsize_t; cdecl; external libmagickwand;
function MagickGetImageTicksPerSecond(para1: PMagickWand): Tsize_t; cdecl; external libmagickwand;
function MagickGetImageWidth(para1: PMagickWand): Tsize_t; cdecl; external libmagickwand;
function MagickGetNumberImages(para1: PMagickWand): Tsize_t; cdecl; external libmagickwand;
function MagickGetImageBlob(para1: PMagickWand; para2: Psize_t): pbyte; cdecl; external libmagickwand;
function MagickGetImagesBlob(para1: PMagickWand; para2: Psize_t): Pdouble; cdecl; external libmagickwand;
function MagickGetImageVirtualPixelMethod(para1: PMagickWand): TVirtualPixelMethod; cdecl; external libmagickwand;
function MagickSetImageVirtualPixelMethod(para1: PMagickWand; para2: TVirtualPixelMethod): TVirtualPixelMethod; cdecl; external libmagickwand;

// === Konventiert am: 5-1-26 19:40:03 ===


implementation



end.
