{$include avformat/buffer.inc}
{$include avformat/dict.inc}
{$include avformat/rational.inc}
{$include avformat/frame.inc}                           // dict, buffer, rational
{$include avformat/uuid.inc}
{$include avformat/version.inc}
{$include avformat/video_enc_params.inc}                // frame
{$include avformat/video_hint.inc}                      // frame
{$include avformat/xtea.inc}
{$include avformat/twofish.inc}
{$include avformat/tx.inc}
{$include avformat/tree.inc}
{$include avformat/timecode.inc}
{$include avformat/timestamp.inc}                       // rational
{$include avformat/pixelutils.inc}
{$include avformat/pixfmt.inc}
{$include avformat/pixdesc.inc}                         // pixfmt
{$include avformat/random_seed.inc}
{$include avformat/rc4.inc}
{$include avformat/replaygain.inc}
{$include avformat/ripemd.inc}
{$include avformat/samplefmt.inc}
{$include avformat/sha.inc}
{$include avformat/sha512.inc}
{$include avformat/spherical.inc}
{$include avformat/stereo3d.inc}                        // frame
{$include avformat/tea.inc}
{$include avformat/threadmessage.inc}
{$include avformat/time.inc}
{$include avformat/channel_layout.inc}
{$include avformat/log.inc}
{$include avformat/opt.inc}                             // rational, dict, pixfmt, samplefmt, channel_layout, log
{$include avformat/parseutils.inc}                      // rational, log
{$include avformat/imgutils.inc}                        // pixfmt, pixdesc, rational
{$include avformat/intreadwrite.inc}
{$include avformat/lfg.inc}
{$include avformat/lzo.inc}
{$include avformat/mastering_display_metadata.inc}      // rational, frame
{$include avformat/intfloat.inc}
{$include avformat/mathematics.inc}                     // rational
{$include avformat/md5.inc}
{$include avformat/mem.inc}
{$include avformat/motion_vector.inc}
{$include avformat/murmur3.inc}
{$include avformat/hdr_dynamic_metadata.inc}           // rational, frame
{$include avformat/hdr_dynamic_vivid_metadata.inc}     // rational, frame
{$include avformat/hmac.inc}
{$include avformat/adler32.inc}
{$include avformat/aes.inc}
{$include avformat/aes_ctr.inc}
{$include avformat/ambient_viewing_environment.inc}
{$include avformat/audio_fifo.inc}
{$include avformat/avassert.inc}
{$include avformat/avutil.inc}
{$include avformat/base64.inc}
{$include avformat/blowfish.inc}
{$include avformat/avstring.inc}
{$include avformat/bprint.inc}                         // avstring
{$include avformat/camellia.inc}
{$include avformat/cast5.inc}
{$include avformat/common.inc}
{$include avformat/cpu.inc}
{$include avformat/crc.inc}
{$include avformat/csp.inc}
{$include avformat/des.inc}
{$include avformat/detection_bbox.inc}
{$include avformat/display.inc}
{$include avformat/dovi_meta.inc}
{$include avformat/downmix_info.inc}
{$include avformat/encryption_info.inc}
{$include avformat/error.inc}
{$include avformat/eval.inc}
{$include avformat/executor.inc}
{$include avformat/ffversion.inc}
{$include avformat/fifo.inc}
{$include avformat/file_.inc}
{$include avformat/film_grain_params.inc}             // pixfmt, frame
{$include avformat/hash.inc}
{$include avformat/hwcontext.inc}
{$include avformat/hwcontext_cuda.inc}
{$include avformat/hwcontext_d3d11va.inc}
{$include avformat/hwcontext_drm.inc}
{$include avformat/hwcontext_dxva2.inc}
{$include avformat/hwcontext_mediacodec.inc}
{$include avformat/hwcontext_opencl.inc}
{$include avformat/hwcontext_qsv.inc}
{$include avformat/hwcontext_vaapi.inc}
{$include avformat/hwcontext_vdpau.inc}
{$include avformat/hwcontext_videotoolbox.inc}
{$include avformat/hwcontext_vulkan.inc}

