unit ldap_features;

interface

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


const
  LDAP_VENDOR_VERSION = 20607;
  LDAP_VENDOR_VERSION_MAJOR = 2;
  LDAP_VENDOR_VERSION_MINOR = 6;
  LDAP_VENDOR_VERSION_PATCH = 7;
  LDAP_API_FEATURE_X_OPENLDAP_REENTRANT = 1;
  LDAP_API_FEATURE_X_OPENLDAP_THREAD_SAFE = 1;

  // === Konventiert am: 10-12-25 16:58:19 ===


implementation



end.
