{$include core/version.inc}
{$include core/magick_type.inc}
{$include core/method_attribute.inc}
{$include core/string_.inc}
{$include core/profile.inc}              // string_
{$include core/splay_tree.inc}
{$include core/xml_tree.inc}             // splay_tree
{$include core/semaphore.inc}
{$include core/exception.inc}            // semaphore
{$include core/colorspace.inc}
{$include core/constitute.inc}
{$include core/geometry.inc}
{$include core/morphology.inc}           // geometry
{$include core/pixel.inc}                // colorspace, constitute
{$include core/cache_view.inc}
{$include core/cache.inc}                // pixel, cache_view
{$include core/quantum.inc}              // cache_view
{$include core/quantize.inc}             // colorspace
{$include core/resample.inc}             // pixel, cache_view
{$include core/composite.inc}
{$include core/compress.inc}
{$include core/effect.inc}
{$include core/monitor.inc}
{$include core/stream.inc}
{$include core/image.inc}                // exception, pixel, geometry, cache_view     -- struct verkleinert
{$include core/draw.inc}                 //                                            -- struct verkleinert
{$include core/visual_effects.inc}       // pixel, morphology, draw, image
{$include core/registry.inc}
{$include core/random_.inc}
{$include core/pixel_accessor.inc}       // quantum, pixel
{$include core/animate.inc}
{$include core/annotate.inc}
{$include core/artifact.inc}
{$include core/attribute.inc}            // image, geometry
{$include core/blob.inc}                 // stream
{$include core/channel.inc}              // image
{$include core/cipher.inc}
{$include core/client.inc}
{$include core/coder.inc}
{$include core/color.inc}
{$include core/colormap.inc}
{$include core/compare.inc}
{$include core/hashmap.inc}
{$include core/configure.inc}             // hashmap
{$include core/decorate.inc}
{$include core/delegate.inc}
{$include core/display.inc}
{$include core/distort.inc}
{$include core/distribute_cache.inc}
{$include core/enhance.inc}
{$include core/feature.inc}
{$include core/fourier.inc}
{$include core/fx.inc}
{$include core/gem.inc}
{$include core/histogram.inc}
{$include core/identify.inc}
{$include core/image_view.inc}
{$include core/layer.inc}
{$include core/list.inc}
{$include core/locale_.inc}
{$include core/log.inc}
{$include core/magic.inc}
{$include core/magick.inc}
{$include core/magick_config.inc}
{$include core/matrix.inc}
{$include core/memory_.inc}
{$include core/mime.inc}
{$include core/module.inc}
{$include core/montage.inc}
{$include core/opencl.inc}
{$include core/option.inc}
{$include core/paint.inc}
{$include core/policy.inc}
{$include core/prepress.inc}
{$include core/property_.inc}
{$include core/resize.inc}
{$include core/resource_.inc}
{$include core/segment.inc}
{$include core/shear.inc}
{$include core/signature.inc}
{$include core/static.inc}
{$include core/statistic.inc}
{$include core/threshold.inc}
{$include core/timer.inc}
{$include core/token.inc}
{$include core/transform.inc}
{$include core/type_.inc}
{$include core/utility.inc}
{$include core/vision.inc}
{$include core/deprecate.inc}

