unit _pam_compat;

interface

uses
  ctypes;

  {$IFDEF FPC}
  {$PACKRECORDS C}
  {$ENDIF}



const
  PAM_PRELIM_CHECK = $1;
  PAM_UPDATE_AUTHTOK = $2;

const
  PAM_SILENT = $80000000;
  PAM_CHANGE_EXPIRED_AUTHTOK = $4;
  PAM_ESTABLISH_CRED = $1;
  PAM_DELETE_CRED = $2;
  PAM_REINITIALIZE_CRED = $4;
  PAM_REFRESH_CRED = $8;
  PAM_CONV_ERR = 6;
  PAM_PERM_DENIED = 7;
  PAM_MAXTRIES = 8;
  PAM_AUTH_ERR = 9;
  PAM_NEW_AUTHTOK_REQD = 10;
  PAM_CRED_INSUFFICIENT = 11;
  PAM_AUTHINFO_UNAVAIL = 12;
  PAM_USER_UNKNOWN = 13;
  PAM_CRED_UNAVAIL = 14;
  PAM_CRED_EXPIRED = 15;
  PAM_CRED_ERR = 16;
  PAM_ACCT_EXPIRED = 17;
  PAM_AUTHTOK_EXPIRED = 18;
  PAM_SESSION_ERR = 19;
  PAM_AUTHTOK_ERR = 20;
  PAM_AUTHTOK_RECOVERY_ERR = 21;
  PAM_AUTHTOK_LOCK_BUSY = 22;
  PAM_AUTHTOK_DISABLE_AGING = 23;
  PAM_NO_MODULE_DATA = 24;
  PAM_IGNORE = 25;
  PAM_ABORT = 26;
  PAM_TRY_AGAIN = 27;

const
  PAM_AUTHTOK_RECOVER_ERR = PAM_AUTHTOK_RECOVERY_ERR;

  // === Konventiert am: 13-7-25 15:31:30 ===


implementation



end.
