{$IFDEF read_interface}


// Doppelt !
//procedure glibtop_init_p(server: Pglibtop; features: dword; flags: dword); cdecl; external libgtop2;
//procedure glibtop_open_p(server: Pglibtop; program_name: pchar; features: dword; flags: dword); cdecl; external libgtop2;

// === Konventiert am: 23-10-25 19:36:01 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
