

{$include gtop2/libgtopconfig.inc}
{$include gtop2/glibtop_machine.inc}
{$include gtop2/glibtop_server.inc}
{$include gtop2/glibtop.inc}
{$include gtop2/glibtop_suid.inc}

{$include gtop2/glibtop/sysdeps.inc}
{$include gtop2/glibtop/close.inc}
{$include gtop2/glibtop/cpu.inc}
{$include gtop2/glibtop/disk.inc}
{$include gtop2/glibtop/fsusage.inc}
{$include gtop2/glibtop/loadavg.inc}
{$include gtop2/glibtop/mem.inc}
{$include gtop2/glibtop/mountlist.inc}
{$include gtop2/glibtop/msg_limits.inc}
{$include gtop2/glibtop/netlist.inc}
{$include gtop2/glibtop/netload.inc}
{$include gtop2/glibtop/ppp.inc}
{$include gtop2/glibtop/procaffinity.inc}
{$include gtop2/glibtop/procargs.inc}
{$include gtop2/glibtop/procio.inc}
{$include gtop2/glibtop/prockernel.inc}
{$include gtop2/glibtop/proclist.inc}
{$include gtop2/glibtop/procmap.inc}
{$include gtop2/glibtop/procmem.inc}
{$include gtop2/glibtop/procopenfiles.inc}
{$include gtop2/glibtop/procsegment.inc}
{$include gtop2/glibtop/procsignal.inc}
{$include gtop2/glibtop/procstate.inc}
{$include gtop2/glibtop/proctime.inc}           // cp.inc
{$include gtop2/glibtop/procuid.inc}
{$include gtop2/glibtop/procwd.inc}
{$include gtop2/glibtop/sem_limits.inc}
{$include gtop2/glibtop/shm_limits.inc}
{$include gtop2/glibtop/swap.inc}
{$include gtop2/glibtop/uptime.inc}
{$include gtop2/glibtop/union.inc}              // cpu, disk, ...inc}
{$include gtop2/glibtop/command.inc}            // unio.inc}
{$include gtop2/glibtop/global.inc}
{$include gtop2/glibtop/open.inc}
{$include gtop2/glibtop/parameter.inc}
{$include gtop2/glibtop/signal.inc}
{$include gtop2/glibtop/sysinfo.inc}
{$include gtop2/glibtop/gnuserv.inc}



