unit rdf_log;

interface

uses
  ctypes;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ -*- Mode: c; c-basic-offset: 2 -*-
 *
 * rdf_log.h - RDF logging interfaces
 *
 * Copyright (C) 2004-2008, David Beckett http://www.dajobe.org/
 * Copyright (C) 2004-2005, University of Bristol, UK http://www.bristol.ac.uk/
 * 
 * This package is Free Software and part of Redland http://librdf.org/
 * 
 * It is licensed under the following three licenses as alternatives:
 *   1. GNU Lesser General Public License (LGPL) V2.1 or any newer version
 *   2. GNU General Public License (GPL) V2 or any newer version
 *   3. Apache License, V2.0 or any newer version
 * 
 * You may not use this file except in compliance with at least one of
 * the above three licenses.
 * 
 * See LICENSE.html or LICENSE.txt at the top of this package for the
 * complete terms and further detail along with the license texts for
 * the licenses in COPYING.LIB, COPYING and LICENSE-2.0.txt respectively.
 * 
 * 
  }
{$ifndef LIBRDF_LOG_H}
{$define LIBRDF_LOG_H}
{ C++ extern C conditionnal removed }
{$include <raptor2.h>}
{*
 * librdf_log_level:
 * @LIBRDF_LOG_NONE: No level
 * @LIBRDF_LOG_DEBUG: Debug.
 * @LIBRDF_LOG_INFO: Information.
 * @LIBRDF_LOG_WARN: Warning.
 * @LIBRDF_LOG_ERROR: Recoverable error.  Program can continue.
 * @LIBRDF_LOG_FATAL: Fatal error.  Program will abort if this is not caught.
 * @LIBRDF_LOG_LAST: Internal, never returned.
 *
 * Indicates the level of the log message.
  }
type
  Plibrdf_log_level = ^Tlibrdf_log_level;
  Tlibrdf_log_level =  Longint;
  Const
    LIBRDF_LOG_NONE = 0;
    LIBRDF_LOG_DEBUG = 1;
    LIBRDF_LOG_INFO = 2;
    LIBRDF_LOG_WARN = 3;
    LIBRDF_LOG_ERROR = 4;
    LIBRDF_LOG_FATAL = 5;
    LIBRDF_LOG_LAST = LIBRDF_LOG_FATAL;
;
{*
 * librdf_log_facility:
 * @LIBRDF_FROM_CONCEPTS: Concepts
 * @LIBRDF_FROM_DIGEST: Digest
 * @LIBRDF_FROM_FILES: Files
 * @LIBRDF_FROM_HASH: Hash
 * @LIBRDF_FROM_INIT: Init
 * @LIBRDF_FROM_ITERATOR: Iterator
 * @LIBRDF_FROM_LIST: List
 * @LIBRDF_FROM_MODEL: Model
 * @LIBRDF_FROM_NODE: Node
 * @LIBRDF_FROM_PARSER: Parser
 * @LIBRDF_FROM_QUERY: Query
 * @LIBRDF_FROM_SERIALIZER: Serializer
 * @LIBRDF_FROM_STATEMENT: Statement
 * @LIBRDF_FROM_STORAGE: Storage
 * @LIBRDF_FROM_STREAM: Stream
 * @LIBRDF_FROM_URI: URI
 * @LIBRDF_FROM_UTF8: UTF8
 * @LIBRDF_FROM_MEMORY: Memory
 * @LIBRDF_FROM_NONE: Associated with no part.
 * @LIBRDF_FROM_RAPTOR: Raptor library (parser or serializer; Raptor 2.0.0+).
 * @LIBRDF_FROM_LAST: Internal, never returned.
 *
 * Indicates the part of the system that generated the log message.
  }
type
  Plibrdf_log_facility = ^Tlibrdf_log_facility;
  Tlibrdf_log_facility =  Longint;
  Const
    LIBRDF_FROM_NONE = 0;
    LIBRDF_FROM_CONCEPTS = 1;
    LIBRDF_FROM_DIGEST = 2;
    LIBRDF_FROM_FILES = 3;
    LIBRDF_FROM_HASH = 4;
    LIBRDF_FROM_INIT = 5;
    LIBRDF_FROM_ITERATOR = 6;
    LIBRDF_FROM_LIST = 7;
    LIBRDF_FROM_MODEL = 8;
    LIBRDF_FROM_NODE = 9;
    LIBRDF_FROM_PARSER = 10;
    LIBRDF_FROM_QUERY = 11;
    LIBRDF_FROM_SERIALIZER = 12;
    LIBRDF_FROM_STATEMENT = 13;
    LIBRDF_FROM_STORAGE = 14;
    LIBRDF_FROM_STREAM = 15;
    LIBRDF_FROM_URI = 16;
    LIBRDF_FROM_UTF8 = 17;
    LIBRDF_FROM_MEMORY = 18;
    LIBRDF_FROM_RAPTOR = 19;
    LIBRDF_FROM_LAST = LIBRDF_FROM_RAPTOR;
;
{*
 * librdf_log_message:
 *
 * Structure for storing parts of a log message generated by Redland.
  }
{ The error code  }
{ valid for certain facilities such as LIBRDF_FROM_PARSER  }
type
  Plibrdf_log_message = ^Tlibrdf_log_message;
  Tlibrdf_log_message = record
      code : longint;
      level : Tlibrdf_log_level;
      facility : Tlibrdf_log_facility;
      message : Pchar;
      locator : Praptor_locator;
    end;
{*
 * librdf_log_level_func:
 * @user_data: User data pointer
 * @message: Log message.
 * @arguments: Message arguments.
 *
 * Handler for one log level, for the warning and error levels ONLY.
 * Used by #librdf_world_set_warning and #librdf_world_set_error.
 *
 * Return value: non-zero to indicate log message has been handled 
  }

  Tlibrdf_log_level_func = function (user_data:pointer; message:Pchar; arguments:Tva_list):longint;cdecl;
{*
 * librdf_log_func:
 * @user_data: User data pointer
 * @message: Log message structure pointer.
 *
 * Handler for all log levels.
 *
 * Return value: non-zero to indicate log message has been handled 
  }

  Tlibrdf_log_func = function (user_data:pointer; message:Plibrdf_log_message):longint;cdecl;
{$ifdef LIBRDF_INTERNAL}
{$include <rdf_log_internal.h>}
{$endif}
{ log message accessors  }

function librdf_log_message_code(message:Plibrdf_log_message):longint;cdecl;external librdf;
function librdf_log_message_level(message:Plibrdf_log_message):Tlibrdf_log_level;cdecl;external librdf;
function librdf_log_message_facility(message:Plibrdf_log_message):Tlibrdf_log_facility;cdecl;external librdf;
function librdf_log_message_message(message:Plibrdf_log_message):Pchar;cdecl;external librdf;
function librdf_log_message_locator(message:Plibrdf_log_message):Praptor_locator;cdecl;external librdf;
{ logging functions  }
procedure librdf_log_simple(world:Plibrdf_world; code:longint; level:Tlibrdf_log_level; facility:Tlibrdf_log_facility; locator:pointer; 
            message:Pchar);cdecl;external librdf;
procedure librdf_log(world:Plibrdf_world; code:longint; level:Tlibrdf_log_level; facility:Tlibrdf_log_facility; locator:pointer; 
            message:Pchar; args:array of const);cdecl;external librdf;
procedure librdf_log(world:Plibrdf_world; code:longint; level:Tlibrdf_log_level; facility:Tlibrdf_log_facility; locator:pointer; 
            message:Pchar);cdecl;external librdf;
{ C++ end of extern C conditionnal removed }
{$endif}

// === Konventiert am: 27-11-25 17:39:30 ===


implementation



end.
