


{$include csfml/Config.inc}
//{$include csfml/xxxxxxxxxxxxxxxxxx.inc}
{$include csfml/System/System_Types.inc}
{$include csfml/System/Buffer.inc}
{$include csfml/System/InputStream.inc}
{$include csfml/System/Mutex.inc}
{$include csfml/System/Thread.inc}
{$include csfml/System/Time.inc}
{$include csfml/System/Clock.inc}
{$include csfml/System/Sleep.inc}
{$include csfml/System/Vector2.inc}
{$include csfml/System/Vector3.inc}
//{$include csfml/xxxxxxxxxxxxxxxxxx.inc}
{$include csfml/Window/Window_Types.inc}
{$include csfml/Window/WindowHandle.inc}
{$include csfml/Window/Vulkan.inc}
{$include csfml/Window/Keyboard.inc}
{$include csfml/Window/Mouse.inc}                             // Vector2, Window_Types
{$include csfml/Window/JoystickIdentification.inc}
{$include csfml/Window/Joystick.inc}                          // JoystickIdentification
{$include csfml/Window/Sensor.inc}                            // Vector3
{$include csfml/Window/Event.inc}                             // Keyboard, Mouse, Joystick, Sensor
{$include csfml/Window/VideoMode.inc}
{$include csfml/Window/Clipboard.inc}
{$include csfml/Window/Cursor.inc}                            // Vector2, Window_Types
{$include csfml/Window/Touch.inc}                             // System_Types, Vector2, Window_Types
{$include csfml/Window/Window.inc}                            // Window_Types, WindowHandle, VideoMode, Event, Vector2
{$include csfml/Window/Context.inc}                           // Window_Types, Window
{$include csfml/Window/WindowBase.inc}                        // VideoMode, WindowHandle, Event, Vector2, Vulkan
//{$include csfml/xxxxxxxxxxxxxxxxxx.inc}
{$include csfml/Audio/Audio_Types.inc}
{$include csfml/Audio/SoundStatus.inc}
{$include csfml/Audio/Listener.inc}
{$include csfml/Audio/Music.inc}
{$include csfml/Audio/Sound.inc}
{$include csfml/Audio/SoundBuffer.inc}
{$include csfml/Audio/SoundBufferRecorder.inc}
{$include csfml/Audio/SoundRecorder.inc}
{$include csfml/Audio/SoundStream.inc}
//{$include csfml/xxxxxxxxxxxxxxxxxx.inc}
{$include csfml/Network/Network_Types.inc}
{$include csfml/Network/SocketStatus.inc}
{$include csfml/Network/IpAddress.inc}
{$include csfml/Network/Ftp.inc}                               // IpAddress
{$include csfml/Network/Http.inc}
{$include csfml/Network/Packet.inc}
{$include csfml/Network/SocketSelector.inc}
{$include csfml/Network/TcpListener.inc}                       // IpAddress, SocketStatus
{$include csfml/Network/TcpSocket.inc}                         // SocketStatus, IpAddress
{$include csfml/Network/UdpSocket.inc}                         // IpAddress, SocketStatus
//{$include csfml/xxxxxxxxxxxxxxxxxx.inc}
{$include csfml/Graphics/Graphics_Types.inc}
{$include csfml/Graphics/PrimitiveType.inc}
{$include csfml/Graphics/Rect.inc}
{$include csfml/Graphics/Glyph.inc}
{$include csfml/Graphics/Color.inc}
{$include csfml/Graphics/Transform.inc}
{$include csfml/Graphics/Transformable.inc}
{$include csfml/Graphics/BlendMode.inc}
{$include csfml/Graphics/CircleShape.inc}
{$include csfml/Graphics/ConvexShape.inc}
{$include csfml/Graphics/FontInfo.inc}
{$include csfml/Graphics/Font.inc}
{$include csfml/Graphics/Glsl.inc}
{$include csfml/Graphics/Image.inc}
{$include csfml/Graphics/RectangleShape.inc}
{$include csfml/Graphics/Shader.inc}
{$include csfml/Graphics/Shape.inc}
{$include csfml/Graphics/Sprite.inc}
{$include csfml/Graphics/Texture.inc}
{$include csfml/Graphics/Text.inc}
{$include csfml/Graphics/Vertex.inc}
{$include csfml/Graphics/VertexArray.inc}
{$include csfml/Graphics/VertexBuffer.inc}
{$include csfml/Graphics/View.inc}
{$include csfml/Graphics/RenderStates.inc}
{$include csfml/Graphics/RenderTexture.inc}
{$include csfml/Graphics/RenderWindow.inc}


