

{$include tcl/tcl.inc}
{$include tcl/tclDecls.inc}        // -> tcl
{$include tcl/tclPlatDecls.inc}    // -> tcl
{$include tcl/tclOO.inc}           // -> tcl
{$include tcl/tclOODecls.inc}      // -> tk, tclOO
{$include tcl/tclTomMath.inc}      // -> tcl
{$include tcl/tclTomMathDecls.inc} // -> tcl, tclTomMath
{$include tcl/tk.inc}              // -> tcl
{$include tcl/tkPlatDecls.inc}     // -> tcl, tk
{$include tcl/tkDecls.inc}         // -> tcl, tk


