
unit gspell_enum_types;
interface

{
  Automatically converted by H2Pas 1.0.0 from gspell_enum_types.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    gspell_enum_types.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
{$ifndef GSPELL_ENUM_TYPES_H}
{$define GSPELL_ENUM_TYPES_H}
{$if !defined (GSPELL_H_INSIDE) && !defined (GSPELL_COMPILATION)}
{$error "Only <gspell/gspell.h> can be included directly."}
{$endif}
{$include <glib-object.h>}
{$include <gmodule.h>}
{ Enumerations from "gspell-checker.h"  }

{ was #define dname def_expr }
function GSPELL_TYPE_CHECKER_ERROR : longint; { return type might be wrong }

function gspell_checker_error_get_type:TGType;cdecl;external;
{$endif}
{ GSPELL_ENUM_TYPES_H  }
{ Generated data ends here  }

implementation

{ was #define dname def_expr }
function GSPELL_TYPE_CHECKER_ERROR : longint; { return type might be wrong }
  begin
    GSPELL_TYPE_CHECKER_ERROR:=gspell_checker_error_get_type;
  end;


end.
