unit glibtop_server;

interface

uses
  fp_glib2, fp_libgtop2;

  {$IFDEF FPC}
  {$PACKRECORDS C}
  {$ENDIF}

const
  GLIBTOP_SUID_CPU = 0;
  GLIBTOP_SUID_DISK = 0;
  GLIBTOP_SUID_MEM = 0;
  GLIBTOP_SUID_SWAP = 0;
  GLIBTOP_SUID_UPTIME = 0;
  GLIBTOP_SUID_LOADAVG = 0;
  GLIBTOP_SUID_SHM_LIMITS = 0;
  GLIBTOP_SUID_MSG_LIMITS = 0;
  GLIBTOP_SUID_SEM_LIMITS = 0;
  GLIBTOP_SUID_PROCLIST = 0;
  GLIBTOP_SUID_PROC_STATE = 0;
  GLIBTOP_SUID_PROC_UID = 0;
  GLIBTOP_SUID_PROC_MEM = 0;
  GLIBTOP_SUID_PROC_TIME = 0;
  GLIBTOP_SUID_PROC_SIGNAL = 0;
  GLIBTOP_SUID_PROC_KERNEL = 0;
  GLIBTOP_SUID_PROC_SEGMENT = 0;
  GLIBTOP_SUID_PROC_ARGS = 0;
  GLIBTOP_SUID_PROC_MAP = 0;
  GLIBTOP_SUID_NETLOAD = 0;
  GLIBTOP_SUID_NETLIST = 0;
  GLIBTOP_SUID_PROC_WD = 0;
  GLIBTOP_SUID_PROC_AFFINITY = 0;
  GLIBTOP_SUID_PPP = 0;
  GLIBTOP_SUID_PROC_OPEN_FILES = 0;
  GLIBTOP_SUID_PROC_IO = 0;

  // === Konventiert am: 23-10-25 19:35:56 ===


implementation



end.
