
unit gdk_pixbuf_marshal;
interface

{
  Automatically converted by H2Pas 1.0.0 from gdk_pixbuf_marshal.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    gdk_pixbuf_marshal.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

Type
PGClosure  = ^GClosure;
PGValue  = ^GValue;
{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
(** unsupported pragma#pragma once*)
{$include <glib-object.h>}
{ VOID:VOID (../gdk-pixbuf/gdk-pixbuf-marshal.list:25)  }

const
  _gdk_pixbuf_marshal_VOID__VOID = g_cclosure_marshal_VOID__VOID;  
{ VOID:INT,INT (../gdk-pixbuf/gdk-pixbuf-marshal.list:26)  }
(* Const before type ignored *)

procedure _gdk_pixbuf_marshal_VOID__INT_INT(closure:PGClosure; return_value:PGValue; n_param_values:Tguint; param_values:PGValue; invocation_hint:Tgpointer; 
            marshal_data:Tgpointer);cdecl;external;
{ VOID:INT,INT,INT,INT (../gdk-pixbuf/gdk-pixbuf-marshal.list:27)  }
(* Const before type ignored *)
procedure _gdk_pixbuf_marshal_VOID__INT_INT_INT_INT(closure:PGClosure; return_value:PGValue; n_param_values:Tguint; param_values:PGValue; invocation_hint:Tgpointer; 
            marshal_data:Tgpointer);cdecl;external;
{ VOID:POINTER (../gdk-pixbuf/gdk-pixbuf-marshal.list:28)  }
const
  _gdk_pixbuf_marshal_VOID__POINTER = g_cclosure_marshal_VOID__POINTER;  

implementation


end.
