unit plstrm;

interface

uses
  fp_plplot, plplot, disptab, pdf;

  {$IFDEF FPC}
  {$PACKRECORDS C}
  {$ENDIF}

type
  TPLDev = record
    pxlx: TPLFLT;
    pxly: TPLFLT;
    xold: TPLINT;
    yold: TPLINT;
    xmin: TPLINT;
    xmax: TPLINT;
    xlen: TPLINT;
    ymin: TPLINT;
    ymax: TPLINT;
    ylen: TPLINT;
    xmin_dev: TPLINT;
    xmax_dev: TPLINT;
    xlen_dev: TPLINT;
    ymin_dev: TPLINT;
    ymax_dev: TPLINT;
    ylen_dev: TPLINT;
    xscale_dev: TPLFLT;
    yscale_dev: TPLFLT;
  end;
  PPLDev = ^TPLDev;

const
  PL_MAX_CMAP1CP = 256;

type
  //TPLStream = record
  //  ipls: TPLINT;
  //  level: TPLINT;
  //  verbose: TPLINT;
  //  debug: TPLINT;
  //  initialized: TPLINT;
  //  dev_initialized: TPLINT;
  //  prg: pchar;
  //  coordinate_transform: TPLTRANSFORM_callback;
  //  coordinate_transform_data: TPLPointer;
  //  icol0: TPLINT;
  //  ncol0: TPLINT;
  //  icol1: TPLINT;
  //  ncol1: TPLINT;
  //  ncp1: TPLINT;
  //  curcmap: TPLINT;
  //  cmap1_min: TPLFLT;
  //  cmap1_max: TPLFLT;
  //  curcolor: TPLColor;
  //  tmpcolor: TPLColor;
  //  cmap0: PPLColor;
  //  cmap1: PPLColor;
  //  cmap1cp: array[0..(PL_MAX_CMAP1CP) - 1] of TPLControlPt;
  //  cmap1cp_is_rgb: TPLBOOL;
  //  width: TPLFLT;
  //  widthset: TPLINT;
  //  widthlock: TPLINT;
  //  arrow_x: PPLFLT;
  //  arrow_y: PPLFLT;
  //  arrow_npts: TPLINT;
  //  arrow_fill: TPLINT;
  //  dispatch_table: PPLDispatchTable;
  //  plbuf_read: TPLINT;
  //  plbuf_write: TPLINT;
  //  device: TPLINT;
  //  dev_minor: TPLINT;
  //  termin: TPLINT;
  //  graphx: TPLINT;
  //  nopause: TPLINT;
  //  color: TPLINT;
  //  colorset: TPLINT;
  //  family: TPLINT;
  //  member: TPLINT;
  //  finc: TPLINT;
  //  fflen: TPLINT;
  //  bytemax: TPLINT;
  //  famadv: TPLINT;
  //  dev_fill0: TPLINT;
  //  dev_fill1: TPLINT;
  //  dev_dash: TPLINT;
  //  dev_di: TPLINT;
  //  dev_flush: TPLINT;
  //  dev_swin: TPLINT;
  //  dev_text: TPLINT;
  //  dev_xor: TPLINT;
  //  dev_clear: TPLINT;
  //  dev_fastimg: TPLINT;
  //  dev_arc: TPLINT;
  //  DevName: array[0..79] of char;
  //  OutFile: PFILE;
  //  BaseName: pchar;
  //  FileName: pchar;
  //  output_type: longint;
  //  bytecnt: TPLINT;
  //  page: TPLINT;
  //  linepos: TPLINT;
  //  pdfs: PPDFstrm;
  //  dev_npts: TPLINT;
  //  dev_x: Psmallint;
  //  dev_y: Psmallint;
  //  dev_nptsX: TPLINT;
  //  dev_nptsY: TPLINT;
  //  dev_ix: Psmallint;
  //  dev_iy: Psmallint;
  //  dev_z: Pword;
  //  dev_zmin: word;
  //  dev_zmax: word;
  //  imclxmin: TPLINT;
  //  imclxmax: TPLINT;
  //  imclymin: TPLINT;
  //  imclymax: TPLINT;
  //  dev: pointer;
  //  dev_data: pointer;
  //  KeyEH: procedure(gin: PPLGraphicsIn; KeyEH_data: pointer; exit_eventloop: Plongint); cdecl;
  //  KeyEH_data: pointer;
  //  ButtonEH: procedure(gin: PPLGraphicsIn; ButtonEH_data: pointer; exit_eventloop: Plongint); cdecl;
  //  ButtonEH_data: pointer;
  //  LocateEH: procedure(gin: PPLGraphicsIn; LocateEH_data: pointer; locate_mode: Plongint); cdecl;
  //  LocateEH_data: pointer;
  //  bop_handler: procedure(bop_data: pointer; skip_driver_bop: Plongint); cdecl;
  //  bop_data: pointer;
  //  eop_handler: procedure(eop_data: pointer; skip_driver_eop: Plongint); cdecl;
  //  eop_data: pointer;
  //  xdpi: TPLFLT;
  //  ydpi: TPLFLT;
  //  xlength: TPLINT;
  //  ylength: TPLINT;
  //  xoffset: TPLINT;
  //  yoffset: TPLINT;
  //  hack: TPLINT;
  //  tidy: procedure(para1: pointer); cdecl;
  //  tidy_data: pointer;
  //  errcode: PPLINT;
  //  errmsg: pchar;
  //  geometry: pchar;
  //  window_id: longint;
  //  nopixmap: longint;
  //  db: longint;
  //  ext_resize_draw: longint;
  //  server_name: pchar;
  //  server_host: pchar;
  //  server_port: pchar;
  //  user: pchar;
  //  plserver: pchar;
  //  plwindow: pchar;
  //  auto_path: pchar;
  //  tk_file: pchar;
  //  bufmax: longint;
  //  dp: longint;
  //  server_nokill: longint;
  //  plbuf_buffer_grow: Tsize_t;
  //  plbuf_buffer_size: Tsize_t;
  //  plbuf_buffer: pointer;
  //  plbuf_top: Tsize_t;
  //  plbuf_readpos: Tsize_t;
  //  plbufOwner: longint;
  //  difilt: TPLINT;
  //  diclpxmi: TPLINT;
  //  diclpxma: TPLINT;
  //  diclpymi: TPLINT;
  //  diclpyma: TPLINT;
  //  dipxmin: TPLFLT;
  //  dipymin: TPLFLT;
  //  dipxmax: TPLFLT;
  //  dipymax: TPLFLT;
  //  dipxax: TPLFLT;
  //  dipxb: TPLFLT;
  //  dipyay: TPLFLT;
  //  dipyb: TPLFLT;
  //  aspdev: TPLFLT;
  //  aspect: TPLFLT;
  //  aspori: TPLFLT;
  //  caspfactor: TPLFLT;
  //  mar: TPLFLT;
  //  jx: TPLFLT;
  //  jy: TPLFLT;
  //  didxax: TPLFLT;
  //  didxb: TPLFLT;
  //  didyay: TPLFLT;
  //  didyb: TPLFLT;
  //  diorot: TPLFLT;
  //  dioxax: TPLFLT;
  //  dioxay: TPLFLT;
  //  dioxb: TPLFLT;
  //  dioyax: TPLFLT;
  //  dioyay: TPLFLT;
  //  dioyb: TPLFLT;
  //  dimxax: TPLFLT;
  //  dimxb: TPLFLT;
  //  dimyay: TPLFLT;
  //  dimyb: TPLFLT;
  //  dimxmin: TPLFLT;
  //  dimymin: TPLFLT;
  //  dimxmax: TPLFLT;
  //  dimymax: TPLFLT;
  //  dimxpmm: TPLFLT;
  //  dimypmm: TPLFLT;
  //  page_status: TPLINT;
  //  freeaspect: TPLINT;
  //  portrait: TPLINT;
  //  patt: TPLINT;
  //  inclin: array[0..1] of TPLINT;
  //  delta: array[0..1] of TPLINT;
  //  nps: TPLINT;
  //  currx: TPLINT;
  //  curry: TPLINT;
  //  mark: array[0..9] of TPLINT;
  //  space: array[0..9] of TPLINT;
  //  nms: TPLINT;
  //  timecnt: TPLINT;
  //  alarm: TPLINT;
  //  pendn: TPLINT;
  //  curel: TPLINT;
  //  esc: char;
  //  scale: TPLFLT;
  //  chrdef: TPLFLT;
  //  chrht: TPLFLT;
  //  symdef: TPLFLT;
  //  symht: TPLFLT;
  //  majdef: TPLFLT;
  //  majht: TPLFLT;
  //  mindef: TPLFLT;
  //  minht: TPLFLT;
  //  setpre: TPLINT;
  //  precis: TPLINT;
  //  xdigmax: TPLINT;
  //  ydigmax: TPLINT;
  //  zdigmax: TPLINT;
  //  xdigits: TPLINT;
  //  ydigits: TPLINT;
  //  zdigits: TPLINT;
  //  timefmt: pchar;
  //  label_func: TPLLABEL_FUNC_callback;
  //  label_data: TPLPointer;
  //  vppxmi: TPLINT;
  //  vppxma: TPLINT;
  //  vppymi: TPLINT;
  //  vppyma: TPLINT;
  //  sppxmi: TPLINT;
  //  sppxma: TPLINT;
  //  sppymi: TPLINT;
  //  sppyma: TPLINT;
  //  clpxmi: TPLINT;
  //  clpxma: TPLINT;
  //  clpymi: TPLINT;
  //  clpyma: TPLINT;
  //  phyxmi: TPLINT;
  //  phyxma: TPLINT;
  //  phyxlen: TPLINT;
  //  phyymi: TPLINT;
  //  phyyma: TPLINT;
  //  phyylen: TPLINT;
  //  umx: TPLINT;
  //  umy: TPLINT;
  //  xpmm: TPLFLT;
  //  ypmm: TPLFLT;
  //  base3x: TPLFLT;
  //  base3y: TPLFLT;
  //  basecx: TPLFLT;
  //  basecy: TPLFLT;
  //  domxmi: TPLFLT;
  //  domxma: TPLFLT;
  //  domymi: TPLFLT;
  //  domyma: TPLFLT;
  //  zzscl: TPLFLT;
  //  ranmi: TPLFLT;
  //  ranma: TPLFLT;
  //  cxx: TPLFLT;
  //  cxy: TPLFLT;
  //  cyx: TPLFLT;
  //  cyy: TPLFLT;
  //  cyz: TPLFLT;
  //  czx: TPLFLT;
  //  czy: TPLFLT;
  //  czz: TPLFLT;
  //  nplwin: longint;
  //  plwin: array[0..(PL_MAXWINDOWS) - 1] of TPLWindow;
  //  nsubx: TPLINT;
  //  nsuby: TPLINT;
  //  cursub: TPLINT;
  //  spdxmi: TPLFLT;
  //  spdxma: TPLFLT;
  //  spdymi: TPLFLT;
  //  spdyma: TPLFLT;
  //  vpdxmi: TPLFLT;
  //  vpdxma: TPLFLT;
  //  vpdymi: TPLFLT;
  //  vpdyma: TPLFLT;
  //  vpwxmi: TPLFLT;
  //  vpwxma: TPLFLT;
  //  vpwymi: TPLFLT;
  //  vpwyma: TPLFLT;
  //  wpxscl: TPLFLT;
  //  wpxoff: TPLFLT;
  //  wpyscl: TPLFLT;
  //  wpyoff: TPLFLT;
  //  wmxscl: TPLFLT;
  //  wmxoff: TPLFLT;
  //  wmyscl: TPLFLT;
  //  wmyoff: TPLFLT;
  //  wdxscl: TPLFLT;
  //  wdxoff: TPLFLT;
  //  wdyscl: TPLFLT;
  //  wdyoff: TPLFLT;
  //  dev_compression: TPLINT;
  //  cfont: TPLINT;
  //  FT: pointer;
  //  plPlotterPtr: PPlPlotter;
  //  dev_unicode: TPLINT;
  //  alt_unicode: TPLINT;
  //  fci: TPLUNICODE;
  //  dev_hrshsym: TPLINT;
  //  original_chrdef: TPLFLT;
  //  original_chrht: TPLFLT;
  //  psdoc: pointer;
  //  qsasconfig: PQSASConfig;
  //  dev_gradient: TPLINT;
  //  ngradient: TPLINT;
  //  xgradient: PPLINT;
  //  ygradient: PPLINT;
  //  n_polygon: TPLINT;
  //  x_polygon: PPLFLT;
  //  y_polygon: PPLFLT;
  //  stream_closed: TPLBOOL;
  //  line_style: TPLINT;
  //  dev_mem_alpha: TPLINT;
  //  has_string_length: TPLINT;
  //  string_length: TPLFLT;
  //  get_string_length: TPLINT;
  //  dev_eofill: TPLINT;
  //  dev_modeset: TPLINT;
  //  if_boxbb: TPLBOOL;
  //  boxbb_xmin: TPLFLT;
  //  boxbb_xmax: TPLFLT;
  //  boxbb_ymin: TPLFLT;
  //  boxbb_ymax: TPLFLT;
  //  mf_infile: pchar;
  //  mf_outfile: pchar;
  //end;
  PPLStream = type Pointer;
  PPPLStream = ^PPLStream;

procedure plgpls(p_pls: PPPLStream); cdecl; external libplplot;
procedure plcol_interp(pls: PPLStream; newcolor: PPLColor; i: longint; ncol: longint); cdecl; external libplplot;
procedure plOpenFile(pls: PPLStream); cdecl; external libplplot;
procedure plCloseFile(pls: PPLStream); cdecl; external libplplot;
procedure plP_getmember(pls: PPLStream); cdecl; external libplplot;
procedure plP_sfnam(pls: PPLStream; fnam: pchar); cdecl; external libplplot;
procedure plFamInit(pls: PPLStream); cdecl; external libplplot;
procedure plGetFam(pls: PPLStream); cdecl; external libplplot;
procedure plRotPhy(orient: TPLINT; xmin: TPLINT; ymin: TPLINT; xmax: TPLINT; ymax: TPLINT; px: PPLINT; py: PPLINT); cdecl; external libplplot;
function plAllocDev(pls: PPLStream): PPLDev; cdecl; external libplplot;
procedure plGinInit(gin: PPLGraphicsIn); cdecl; external libplplot;

// === Konventiert am: 31-3-26 20:05:18 ===


implementation



end.
