
unit Elementary_Options;
interface

{
  Automatically converted by H2Pas 1.0.0 from Elementary_Options.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    Elementary_Options.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
  }
(** unsupported pragma#pragma once*)

const
  ELM_ALLOCA_H = 1;  
  ELM_DIRENT_H = 1;  
  ELM_EFREET = 1;  
  ELM_UNIX = 1;  

implementation


end.
