
unit fexpr_builtin;
interface

{
  Automatically converted by H2Pas 1.0.0 from fexpr_builtin.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    fexpr_builtin.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

Type
Pchar  = ^char;
Pfexpr_builtin_symbol  = ^fexpr_builtin_symbol;
Pfexpr_symbol_info  = ^fexpr_symbol_info;
{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{
    Copyright (C) 2021 Fredrik Johansson

    This file is part of Calcium.

    Calcium is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 2.1 of the License, or
    (at your option) any later version.  See <http://www.gnu.org/licenses/>.
 }
type
  Pfexpr_builtin_symbol = ^Tfexpr_builtin_symbol;
  Tfexpr_builtin_symbol =  Longint;
  Const
    FEXPR_AGM = 0;
    FEXPR_AGMSequence = 1;
    FEXPR_Abs = 2;
    FEXPR_Acos = 3;
    FEXPR_Acosh = 4;
    FEXPR_Acot = 5;
    FEXPR_Acoth = 6;
    FEXPR_Acsc = 7;
    FEXPR_Acsch = 8;
    FEXPR_Add = 9;
    FEXPR_AiryAi = 10;
    FEXPR_AiryAiZero = 11;
    FEXPR_AiryBi = 12;
    FEXPR_AiryBiZero = 13;
    FEXPR_AlgebraicNumberSerialized = 14;
    FEXPR_AlgebraicNumbers = 15;
    FEXPR_All = 16;
    FEXPR_AnalyticContinuation = 17;
    FEXPR_And = 18;
    FEXPR_AngleBrackets = 19;
    FEXPR_Approximation = 20;
    FEXPR_Arg = 21;
    FEXPR_ArgMax = 22;
    FEXPR_ArgMaxUnique = 23;
    FEXPR_ArgMin = 24;
    FEXPR_ArgMinUnique = 25;
    FEXPR_Asec = 26;
    FEXPR_Asech = 27;
    FEXPR_Asin = 28;
    FEXPR_Asinh = 29;
    FEXPR_AsymptoticTo = 30;
    FEXPR_Atan = 31;
    FEXPR_Atan2 = 32;
    FEXPR_Atanh = 33;
    FEXPR_BarnesG = 34;
    FEXPR_BellNumber = 35;
    FEXPR_BernoulliB = 36;
    FEXPR_BernoulliPolynomial = 37;
    FEXPR_BernsteinEllipse = 38;
    FEXPR_BesselI = 39;
    FEXPR_BesselJ = 40;
    FEXPR_BesselJZero = 41;
    FEXPR_BesselK = 42;
    FEXPR_BesselY = 43;
    FEXPR_BesselYZero = 44;
    FEXPR_BetaFunction = 45;
    FEXPR_Binomial = 46;
    FEXPR_Braces = 47;
    FEXPR_Brackets = 48;
    FEXPR_CC = 49;
    FEXPR_Call = 50;
    FEXPR_CallIndeterminate = 51;
    FEXPR_Cardinality = 52;
    FEXPR_CarlsonHypergeometricR = 53;
    FEXPR_CarlsonHypergeometricT = 54;
    FEXPR_CarlsonRC = 55;
    FEXPR_CarlsonRD = 56;
    FEXPR_CarlsonRF = 57;
    FEXPR_CarlsonRG = 58;
    FEXPR_CarlsonRJ = 59;
    FEXPR_CartesianPower = 60;
    FEXPR_CartesianProduct = 61;
    FEXPR_Case = 62;
    FEXPR_Cases = 63;
    FEXPR_CatalanConstant = 64;
    FEXPR_Ceil = 65;
    FEXPR_Characteristic = 66;
    FEXPR_ChebyshevT = 67;
    FEXPR_ChebyshevU = 68;
    FEXPR_ClosedComplexDisk = 69;
    FEXPR_ClosedOpenInterval = 70;
    FEXPR_Coefficient = 71;
    FEXPR_Column = 72;
    FEXPR_ColumnMatrix = 73;
    FEXPR_CommutativeRings = 74;
    FEXPR_ComplexBranchDerivative = 75;
    FEXPR_ComplexDerivative = 76;
    FEXPR_ComplexInfinities = 77;
    FEXPR_ComplexLimit = 78;
    FEXPR_ComplexSignedInfinities = 79;
    FEXPR_ComplexSingularityClosure = 80;
    FEXPR_ComplexZeroMultiplicity = 81;
    FEXPR_Concatenation = 82;
    FEXPR_CongruentMod = 83;
    FEXPR_Conjugate = 84;
    FEXPR_ConreyGenerator = 85;
    FEXPR_Cos = 86;
    FEXPR_CosIntegral = 87;
    FEXPR_Cosh = 88;
    FEXPR_CoshIntegral = 89;
    FEXPR_Cot = 90;
    FEXPR_Coth = 91;
    FEXPR_CoulombC = 92;
    FEXPR_CoulombF = 93;
    FEXPR_CoulombG = 94;
    FEXPR_CoulombH = 95;
    FEXPR_CoulombSigma = 96;
    FEXPR_Csc = 97;
    FEXPR_Csch = 98;
    FEXPR_Csgn = 99;
    FEXPR_CurvePath = 100;
    FEXPR_Cyclotomic = 101;
    FEXPR_Decimal = 102;
    FEXPR_DedekindEta = 103;
    FEXPR_DedekindEtaEpsilon = 104;
    FEXPR_DedekindSum = 105;
    FEXPR_Def = 106;
    FEXPR_Delta = 107;
    FEXPR_Delta_ = 108;
    FEXPR_Derivative = 109;
    FEXPR_Det = 110;
    FEXPR_DiagonalMatrix = 111;
    FEXPR_DigammaFunction = 112;
    FEXPR_DigammaFunctionZero = 113;
    FEXPR_DirichletCharacter = 114;
    FEXPR_DirichletGroup = 115;
    FEXPR_DirichletL = 116;
    FEXPR_DirichletLZero = 117;
    FEXPR_DirichletLambda = 118;
    FEXPR_DiscreteLog = 119;
    FEXPR_Div = 120;
    FEXPR_Divides = 121;
    FEXPR_DivisorProduct = 122;
    FEXPR_DivisorSigma = 123;
    FEXPR_DivisorSum = 124;
    FEXPR_DoubleFactorial = 125;
    FEXPR_EisensteinE = 126;
    FEXPR_EisensteinG = 127;
    FEXPR_Element = 128;
    FEXPR_Ellipsis = 129;
    FEXPR_EllipticE = 130;
    FEXPR_EllipticK = 131;
    FEXPR_EllipticPi = 132;
    FEXPR_EllipticRootE = 133;
    FEXPR_Enclosure = 134;
    FEXPR_Equal = 135;
    FEXPR_EqualAndElement = 136;
    FEXPR_EqualNearestDecimal = 137;
    FEXPR_EqualQSeriesEllipsis = 138;
    FEXPR_Equivalent = 139;
    FEXPR_Erf = 140;
    FEXPR_Erfc = 141;
    FEXPR_Erfi = 142;
    FEXPR_Euler = 143;
    FEXPR_EulerE = 144;
    FEXPR_EulerPhi = 145;
    FEXPR_EulerPolynomial = 146;
    FEXPR_EulerQSeries = 147;
    FEXPR_Exists = 148;
    FEXPR_Exp = 149;
    FEXPR_ExpIntegralE = 150;
    FEXPR_ExpIntegralEi = 151;
    FEXPR_ExtendedRealNumbers = 152;
    FEXPR_Factorial = 153;
    FEXPR_FallingFactorial = 154;
    FEXPR_False = 155;
    FEXPR_Fibonacci = 156;
    FEXPR_Fields = 157;
    FEXPR_FiniteField = 158;
    FEXPR_Floor = 159;
    FEXPR_For = 160;
    FEXPR_FormalLaurentSeries = 161;
    FEXPR_FormalPowerSeries = 162;
    FEXPR_FormalPuiseuxSeries = 163;
    FEXPR_FresnelC = 164;
    FEXPR_FresnelS = 165;
    FEXPR_Fun = 166;
    FEXPR_GCD = 167;
    FEXPR_Gamma = 168;
    FEXPR_GaussLegendreWeight = 169;
    FEXPR_GaussSum = 170;
    FEXPR_GegenbauerC = 171;
    FEXPR_GeneralLinearGroup = 172;
    FEXPR_GeneralizedBernoulliB = 173;
    FEXPR_GeneralizedRiemannHypothesis = 174;
    FEXPR_GlaisherConstant = 175;
    FEXPR_GoldenRatio = 176;
    FEXPR_Greater = 177;
    FEXPR_GreaterEqual = 178;
    FEXPR_GreekGamma = 179;
    FEXPR_GreekGamma_ = 180;
    FEXPR_GreekPi = 181;
    FEXPR_GreekPi_ = 182;
    FEXPR_Guess = 183;
    FEXPR_HankelH1 = 184;
    FEXPR_HankelH2 = 185;
    FEXPR_HarmonicNumber = 186;
    FEXPR_HermiteH = 187;
    FEXPR_HilbertClassPolynomial = 188;
    FEXPR_HilbertMatrix = 189;
    FEXPR_HurwitzZeta = 190;
    FEXPR_Hypergeometric0F1 = 191;
    FEXPR_Hypergeometric0F1Regularized = 192;
    FEXPR_Hypergeometric1F1 = 193;
    FEXPR_Hypergeometric1F1Regularized = 194;
    FEXPR_Hypergeometric1F2 = 195;
    FEXPR_Hypergeometric1F2Regularized = 196;
    FEXPR_Hypergeometric2F0 = 197;
    FEXPR_Hypergeometric2F1 = 198;
    FEXPR_Hypergeometric2F1Regularized = 199;
    FEXPR_Hypergeometric2F2 = 200;
    FEXPR_Hypergeometric2F2Regularized = 201;
    FEXPR_Hypergeometric3F2 = 202;
    FEXPR_Hypergeometric3F2Regularized = 203;
    FEXPR_HypergeometricU = 204;
    FEXPR_HypergeometricUStar = 205;
    FEXPR_HypergeometricUStarRemainder = 206;
    FEXPR_IdentityMatrix = 207;
    FEXPR_Im = 208;
    FEXPR_Implies = 209;
    FEXPR_IncompleteBeta = 210;
    FEXPR_IncompleteBetaRegularized = 211;
    FEXPR_IncompleteEllipticE = 212;
    FEXPR_IncompleteEllipticF = 213;
    FEXPR_IncompleteEllipticPi = 214;
    FEXPR_IndefiniteIntegralEqual = 215;
    FEXPR_Infimum = 216;
    FEXPR_Infinity = 217;
    FEXPR_IntegersGreaterEqual = 218;
    FEXPR_IntegersLessEqual = 219;
    FEXPR_Integral = 220;
    FEXPR_Intersection = 221;
    FEXPR_Interval = 222;
    FEXPR_IsEven = 223;
    FEXPR_IsHolomorphicOn = 224;
    FEXPR_IsMeromorphicOn = 225;
    FEXPR_IsOdd = 226;
    FEXPR_IsPrime = 227;
    FEXPR_Item = 228;
    FEXPR_JacobiP = 229;
    FEXPR_JacobiSymbol = 230;
    FEXPR_JacobiTheta = 231;
    FEXPR_JacobiThetaEpsilon = 232;
    FEXPR_JacobiThetaPermutation = 233;
    FEXPR_JacobiThetaQ = 234;
    FEXPR_KeiperLiLambda = 235;
    FEXPR_KhinchinConstant = 236;
    FEXPR_KroneckerDelta = 237;
    FEXPR_KroneckerSymbol = 238;
    FEXPR_LCM = 239;
    FEXPR_LaguerreL = 240;
    FEXPR_LambertW = 241;
    FEXPR_Lamda = 242;
    FEXPR_Lamda_ = 243;
    FEXPR_LandauG = 244;
    FEXPR_Lattice = 245;
    FEXPR_LeftLimit = 246;
    FEXPR_LegendreP = 247;
    FEXPR_LegendrePolynomialZero = 248;
    FEXPR_LegendreSymbol = 249;
    FEXPR_Length = 250;
    FEXPR_LerchPhi = 251;
    FEXPR_Less = 252;
    FEXPR_LessEqual = 253;
    FEXPR_Limit = 254;
    FEXPR_LiouvilleLambda = 255;
    FEXPR_List = 256;
    FEXPR_Log = 257;
    FEXPR_LogBarnesG = 258;
    FEXPR_LogBarnesGRemainder = 259;
    FEXPR_LogGamma = 260;
    FEXPR_LogIntegral = 261;
    FEXPR_Logic = 262;
    FEXPR_LowerGamma = 263;
    FEXPR_Matrices = 264;
    FEXPR_Matrix = 265;
    FEXPR_Matrix2x2 = 266;
    FEXPR_Max = 267;
    FEXPR_Maximum = 268;
    FEXPR_MeromorphicDerivative = 269;
    FEXPR_MeromorphicLimit = 270;
    FEXPR_Min = 271;
    FEXPR_Minimum = 272;
    FEXPR_Mod = 273;
    FEXPR_ModularGroupAction = 274;
    FEXPR_ModularGroupFundamentalDomain = 275;
    FEXPR_ModularJ = 276;
    FEXPR_ModularLambda = 277;
    FEXPR_ModularLambdaFundamentalDomain = 278;
    FEXPR_MoebiusMu = 279;
    FEXPR_Mul = 280;
    FEXPR_MultiZetaValue = 281;
    FEXPR_NN = 282;
    FEXPR_Neg = 283;
    FEXPR_Not = 284;
    FEXPR_NotElement = 285;
    FEXPR_NotEqual = 286;
    FEXPR_NumberE = 287;
    FEXPR_NumberI = 288;
    FEXPR_Omega = 289;
    FEXPR_Omega_ = 290;
    FEXPR_One = 291;
    FEXPR_OpenClosedInterval = 292;
    FEXPR_OpenComplexDisk = 293;
    FEXPR_OpenInterval = 294;
    FEXPR_OpenRealBall = 295;
    FEXPR_Or = 296;
    FEXPR_Otherwise = 297;
    FEXPR_PSL2Z = 298;
    FEXPR_Parentheses = 299;
    FEXPR_PartitionsP = 300;
    FEXPR_Path = 301;
    FEXPR_Phi = 302;
    FEXPR_Phi_ = 303;
    FEXPR_Pi = 304;
    FEXPR_Pol = 305;
    FEXPR_Poles = 306;
    FEXPR_PolyLog = 307;
    FEXPR_Polynomial = 308;
    FEXPR_PolynomialDegree = 309;
    FEXPR_PolynomialFractions = 310;
    FEXPR_PolynomialRootIndexed = 311;
    FEXPR_PolynomialRootNearest = 312;
    FEXPR_Polynomials = 313;
    FEXPR_Pos = 314;
    FEXPR_Pow = 315;
    FEXPR_Prime = 316;
    FEXPR_PrimePi = 317;
    FEXPR_PrimeProduct = 318;
    FEXPR_PrimeSum = 319;
    FEXPR_Primes = 320;
    FEXPR_PrimitiveDirichletCharacters = 321;
    FEXPR_PrimitiveReducedPositiveIntegralBinaryQuadraticForms = 322;
    FEXPR_Product = 323;
    FEXPR_ProjectiveComplexNumbers = 324;
    FEXPR_ProjectiveRealNumbers = 325;
    FEXPR_Psi = 326;
    FEXPR_Psi_ = 327;
    FEXPR_QQ = 328;
    FEXPR_QSeriesCoefficient = 329;
    FEXPR_QuotientRing = 330;
    FEXPR_RR = 331;
    FEXPR_Range = 332;
    FEXPR_Re = 333;
    FEXPR_RealAbs = 334;
    FEXPR_RealAlgebraicNumbers = 335;
    FEXPR_RealBall = 336;
    FEXPR_RealDerivative = 337;
    FEXPR_RealInfinities = 338;
    FEXPR_RealLimit = 339;
    FEXPR_RealSignedInfinities = 340;
    FEXPR_RealSingularityClosure = 341;
    FEXPR_Repeat = 342;
    FEXPR_Residue = 343;
    FEXPR_RiemannHypothesis = 344;
    FEXPR_RiemannXi = 345;
    FEXPR_RiemannZeta = 346;
    FEXPR_RiemannZetaZero = 347;
    FEXPR_RightLimit = 348;
    FEXPR_Rings = 349;
    FEXPR_RisingFactorial = 350;
    FEXPR_Root = 351;
    FEXPR_RootOfUnity = 352;
    FEXPR_Row = 353;
    FEXPR_RowMatrix = 354;
    FEXPR_SL2Z = 355;
    FEXPR_Same = 356;
    FEXPR_Sec = 357;
    FEXPR_Sech = 358;
    FEXPR_SequenceLimit = 359;
    FEXPR_SequenceLimitInferior = 360;
    FEXPR_SequenceLimitSuperior = 361;
    FEXPR_Ser = 362;
    FEXPR_Set = 363;
    FEXPR_SetMinus = 364;
    FEXPR_Sets = 365;
    FEXPR_ShowExpandedNormalForm = 366;
    FEXPR_Sigma = 367;
    FEXPR_Sigma_ = 368;
    FEXPR_Sign = 369;
    FEXPR_SignExtendedComplexNumbers = 370;
    FEXPR_Sin = 371;
    FEXPR_SinIntegral = 372;
    FEXPR_Sinc = 373;
    FEXPR_SingularValues = 374;
    FEXPR_Sinh = 375;
    FEXPR_SinhIntegral = 376;
    FEXPR_SloaneA = 377;
    FEXPR_Solutions = 378;
    FEXPR_SpecialLinearGroup = 379;
    FEXPR_Spectrum = 380;
    FEXPR_SphericalHarmonicY = 381;
    FEXPR_Sqrt = 382;
    FEXPR_SquaresR = 383;
    FEXPR_Step = 384;
    FEXPR_StieltjesGamma = 385;
    FEXPR_StirlingCycle = 386;
    FEXPR_StirlingS1 = 387;
    FEXPR_StirlingS2 = 388;
    FEXPR_StirlingSeriesRemainder = 389;
    FEXPR_Sub = 390;
    FEXPR_Subscript = 391;
    FEXPR_Subset = 392;
    FEXPR_SubsetEqual = 393;
    FEXPR_Subsets = 394;
    FEXPR_Sum = 395;
    FEXPR_Supremum = 396;
    FEXPR_SymmetricPolynomial = 397;
    FEXPR_Tan = 398;
    FEXPR_Tanh = 399;
    FEXPR_Theta = 400;
    FEXPR_Theta_ = 401;
    FEXPR_True = 402;
    FEXPR_Tuple = 403;
    FEXPR_Tuples = 404;
    FEXPR_Undefined = 405;
    FEXPR_Union = 406;
    FEXPR_UniqueSolution = 407;
    FEXPR_UniqueZero = 408;
    FEXPR_UnitCircle = 409;
    FEXPR_Unknown = 410;
    FEXPR_UnsignedInfinity = 411;
    FEXPR_UpperGamma = 412;
    FEXPR_UpperHalfPlane = 413;
    FEXPR_WeierstrassP = 414;
    FEXPR_WeierstrassSigma = 415;
    FEXPR_WeierstrassZeta = 416;
    FEXPR_Where = 417;
    FEXPR_XGCD = 418;
    FEXPR_XX = 419;
    FEXPR_Xi = 420;
    FEXPR_Xi_ = 421;
    FEXPR_ZZ = 422;
    FEXPR_Zero = 423;
    FEXPR_ZeroMatrix = 424;
    FEXPR_Zeros = 425;
    FEXPR_alpha = 426;
    FEXPR_alpha_ = 427;
    FEXPR_beta = 428;
    FEXPR_beta_ = 429;
    FEXPR_chi = 430;
    FEXPR_chi_ = 431;
    FEXPR_delta = 432;
    FEXPR_delta_ = 433;
    FEXPR_ell = 434;
    FEXPR_ell_ = 435;
    FEXPR_epsilon = 436;
    FEXPR_epsilon_ = 437;
    FEXPR_eta = 438;
    FEXPR_eta_ = 439;
    FEXPR_gamma = 440;
    FEXPR_gamma_ = 441;
    FEXPR_iota = 442;
    FEXPR_iota_ = 443;
    FEXPR_kappa = 444;
    FEXPR_kappa_ = 445;
    FEXPR_lamda = 446;
    FEXPR_lamda_ = 447;
    FEXPR_mu = 448;
    FEXPR_mu_ = 449;
    FEXPR_nu = 450;
    FEXPR_nu_ = 451;
    FEXPR_omega = 452;
    FEXPR_omega_ = 453;
    FEXPR_phi = 454;
    FEXPR_phi_ = 455;
    FEXPR_pi = 456;
    FEXPR_pi_ = 457;
    FEXPR_rho = 458;
    FEXPR_rho_ = 459;
    FEXPR_sigma = 460;
    FEXPR_sigma_ = 461;
    FEXPR_tau = 462;
    FEXPR_tau_ = 463;
    FEXPR_theta = 464;
    FEXPR_theta_ = 465;
    FEXPR_varphi = 466;
    FEXPR_varphi_ = 467;
    FEXPR_vartheta = 468;
    FEXPR_vartheta_ = 469;
    FEXPR_xi = 470;
    FEXPR_xi_ = 471;
    FEXPR_zeta = 472;
    FEXPR_zeta_ = 473;
    FEXPR_BUILTIN_LENGTH = 474;
;
(* Const before type ignored *)
type

  Tfexpr_latex_writer = procedure (para1:Tcalcium_stream_t; para2:Tfexpr_t; para3:Tulong);cdecl;
(* Const before type ignored *)
(* Const before type ignored *)

  Pfexpr_symbol_info = ^Tfexpr_symbol_info;
  Tfexpr_symbol_info = record
      symbol : Tfexpr_builtin_symbol;
      _string : Pchar;
      latex_string : Pchar;
      latex_writer : Tfexpr_latex_writer;
    end;
(* Const before type ignored *)
  var
    fexpr_builtin_table : array[0..(FEXPR_BUILTIN_LENGTH)-1] of Tfexpr_symbol_info;cvar;external;

const
  FEXPR_SYMBOL_Pos = FEXPR_TYPE_SMALL_SYMBOL or (FEXPR_Pos shl 16);  
  FEXPR_SYMBOL_Neg = FEXPR_TYPE_SMALL_SYMBOL or (FEXPR_Neg shl 16);  
  FEXPR_SYMBOL_Add = FEXPR_TYPE_SMALL_SYMBOL or (FEXPR_Add shl 16);  
  FEXPR_SYMBOL_Sub = FEXPR_TYPE_SMALL_SYMBOL or (FEXPR_Sub shl 16);  
  FEXPR_SYMBOL_Mul = FEXPR_TYPE_SMALL_SYMBOL or (FEXPR_Mul shl 16);  
  FEXPR_SYMBOL_Div = FEXPR_TYPE_SMALL_SYMBOL or (FEXPR_Div shl 16);  
  FEXPR_SYMBOL_Pow = FEXPR_TYPE_SMALL_SYMBOL or (FEXPR_Pow shl 16);  
(* Const before type ignored *)

function fexpr_builtin_lookup(s:Pchar):Tslong;cdecl;external;
(* Const before type ignored *)
function fexpr_builtin_name(n:Tslong):Pchar;cdecl;external;
function fexpr_builtin_length:Tslong;cdecl;external;
{$endif}

implementation


end.
