

{$include gobject/gtype.inc}
{$include gobject/gtypeplugin.inc}
{$include gobject/gvalue.inc}
{$include gobject/genums.inc}
{$include gobject/gparam.inc}
{$include gobject/gparamspecs.inc}
{$include gobject/gclosure.inc}
{$include gobject/gsignal.inc}
{$include gobject/gobject.inc}
{$include gobject/gbinding.inc}
{$include gobject/gbindinggroup.inc}
{$include gobject/gboxed.inc}
{$include gobject/glib_enumtypes.inc}
{$include gobject/glib_types.inc}
{$include gobject/gmarshal.inc}
{$include gobject/gsignalgroup.inc}
{$include gobject/gsourceclosure.inc}
{$include gobject/gtypemodule.inc}
{$include gobject/gvaluearray.inc}
{$include gobject/gvaluecollector.inc}
{$include gobject/gvaluetypes.inc}

