

{$include suitesparse/SuiteSparse_config.inc}       // Viele Makros entfernt
{$include suitesparse/camd.inc}
{$include suitesparse/ccolamd.inc}
{$include suitesparse/colamd.inc}
{$include suitesparse/amd.inc}
{$include suitesparse/umfpack.inc}                           // amd
{$include suitesparse/cholmod.inc}
{$include suitesparse/btf.inc}
{$include suitesparse/cs.inc}
{$include suitesparse/klu.inc}
{$include suitesparse/klu_cholmod.inc}
{$include suitesparse/ldl.inc}
{$include suitesparse/ParU_definitions.inc}
{$include suitesparse/ParU_C.inc}
{$include suitesparse/RBio.inc}
{$include suitesparse/SPEX.inc}
{$include suitesparse/SuiteSparseQR_definitions.inc}
{$include suitesparse/SuiteSparseQR_C.inc}         // cholmod

