
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

            #include <glib-object.h>
            #if !defined(_ADAPTA_INSIDE) && !defined(ADAPTA_COMPILATION)
#error "Only <adapta.h> can be included directly."
#endif

#include "adap-version.h"


            

/* enumerations from "adap-alert-dialog.h" */

extern
GType adap_response_appearance_get_type (void);
#define ADAP_TYPE_RESPONSE_APPEARANCE (adap_response_appearance_get_type())

/* enumerations from "adap-animation.h" */

extern
GType adap_animation_state_get_type (void);
#define ADAP_TYPE_ANIMATION_STATE (adap_animation_state_get_type())

/* enumerations from "adap-breakpoint.h" */

extern
GType adap_breakpoint_condition_length_type_get_type (void);
#define ADAP_TYPE_BREAKPOINT_CONDITION_LENGTH_TYPE (adap_breakpoint_condition_length_type_get_type())

extern
GType adap_breakpoint_condition_ratio_type_get_type (void);
#define ADAP_TYPE_BREAKPOINT_CONDITION_RATIO_TYPE (adap_breakpoint_condition_ratio_type_get_type())

/* enumerations from "adap-dialog.h" */

extern
GType adap_dialog_presentation_mode_get_type (void);
#define ADAP_TYPE_DIALOG_PRESENTATION_MODE (adap_dialog_presentation_mode_get_type())

/* enumerations from "adap-easing.h" */

extern
GType adap_easing_get_type (void);
#define ADAP_TYPE_EASING (adap_easing_get_type())

/* enumerations from "adap-flap.h" */

extern
GType adap_flap_fold_policy_get_type (void);
#define ADAP_TYPE_FLAP_FOLD_POLICY (adap_flap_fold_policy_get_type())

extern
GType adap_flap_transition_type_get_type (void);
#define ADAP_TYPE_FLAP_TRANSITION_TYPE (adap_flap_transition_type_get_type())

/* enumerations from "adap-fold-threshold-policy.h" */

extern
GType adap_fold_threshold_policy_get_type (void);
#define ADAP_TYPE_FOLD_THRESHOLD_POLICY (adap_fold_threshold_policy_get_type())

/* enumerations from "adap-header-bar.h" */

extern
GType adap_centering_policy_get_type (void);
#define ADAP_TYPE_CENTERING_POLICY (adap_centering_policy_get_type())

/* enumerations from "adap-leaflet.h" */

extern
GType adap_leaflet_transition_type_get_type (void);
#define ADAP_TYPE_LEAFLET_TRANSITION_TYPE (adap_leaflet_transition_type_get_type())

/* enumerations from "adap-length-unit.h" */

extern
GType adap_length_unit_get_type (void);
#define ADAP_TYPE_LENGTH_UNIT (adap_length_unit_get_type())

/* enumerations from "adap-navigation-direction.h" */

extern
GType adap_navigation_direction_get_type (void);
#define ADAP_TYPE_NAVIGATION_DIRECTION (adap_navigation_direction_get_type())

/* enumerations from "adap-squeezer.h" */

extern
GType adap_squeezer_transition_type_get_type (void);
#define ADAP_TYPE_SQUEEZER_TRANSITION_TYPE (adap_squeezer_transition_type_get_type())

/* enumerations from "adap-style-manager.h" */

extern
GType adap_color_scheme_get_type (void);
#define ADAP_TYPE_COLOR_SCHEME (adap_color_scheme_get_type())

/* enumerations from "adap-tab-view.h" */

extern
GType adap_tab_view_shortcuts_get_type (void);
#define ADAP_TYPE_TAB_VIEW_SHORTCUTS (adap_tab_view_shortcuts_get_type())

/* enumerations from "adap-toast.h" */

extern
GType adap_toast_priority_get_type (void);
#define ADAP_TYPE_TOAST_PRIORITY (adap_toast_priority_get_type())

/* enumerations from "adap-toolbar-view.h" */

extern
GType adap_toolbar_style_get_type (void);
#define ADAP_TYPE_TOOLBAR_STYLE (adap_toolbar_style_get_type())

/* enumerations from "adap-view-switcher.h" */

extern
GType adap_view_switcher_policy_get_type (void);
#define ADAP_TYPE_VIEW_SWITCHER_POLICY (adap_view_switcher_policy_get_type())



/* Generated data ends here */

