
unit adap_enums;
interface

{
  Automatically converted by H2Pas 1.0.0 from adap_enums.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    adap_enums.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
(** unsupported pragma#pragma once*)
{$include <glib-object.h>}
{$if !defined(_ADAPTA_INSIDE) && !defined(ADAPTA_COMPILATION)}
{$error "Only <adapta.h> can be included directly."}
{$endif}
{$include "adap-version.h"}
{ enumerations from "adap-alert-dialog.h"  }

function adap_response_appearance_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_RESPONSE_APPEARANCE : longint; { return type might be wrong }

{ enumerations from "adap-animation.h"  }
function adap_animation_state_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_ANIMATION_STATE : longint; { return type might be wrong }

{ enumerations from "adap-breakpoint.h"  }
function adap_breakpoint_condition_length_type_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_BREAKPOINT_CONDITION_LENGTH_TYPE : longint; { return type might be wrong }

function adap_breakpoint_condition_ratio_type_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_BREAKPOINT_CONDITION_RATIO_TYPE : longint; { return type might be wrong }

{ enumerations from "adap-dialog.h"  }
function adap_dialog_presentation_mode_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_DIALOG_PRESENTATION_MODE : longint; { return type might be wrong }

{ enumerations from "adap-easing.h"  }
function adap_easing_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_EASING : longint; { return type might be wrong }

{ enumerations from "adap-flap.h"  }
function adap_flap_fold_policy_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_FLAP_FOLD_POLICY : longint; { return type might be wrong }

function adap_flap_transition_type_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_FLAP_TRANSITION_TYPE : longint; { return type might be wrong }

{ enumerations from "adap-fold-threshold-policy.h"  }
function adap_fold_threshold_policy_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_FOLD_THRESHOLD_POLICY : longint; { return type might be wrong }

{ enumerations from "adap-header-bar.h"  }
function adap_centering_policy_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_CENTERING_POLICY : longint; { return type might be wrong }

{ enumerations from "adap-leaflet.h"  }
function adap_leaflet_transition_type_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_LEAFLET_TRANSITION_TYPE : longint; { return type might be wrong }

{ enumerations from "adap-length-unit.h"  }
function adap_length_unit_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_LENGTH_UNIT : longint; { return type might be wrong }

{ enumerations from "adap-navigation-direction.h"  }
function adap_navigation_direction_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_NAVIGATION_DIRECTION : longint; { return type might be wrong }

{ enumerations from "adap-squeezer.h"  }
function adap_squeezer_transition_type_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_SQUEEZER_TRANSITION_TYPE : longint; { return type might be wrong }

{ enumerations from "adap-style-manager.h"  }
function adap_color_scheme_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_COLOR_SCHEME : longint; { return type might be wrong }

{ enumerations from "adap-tab-view.h"  }
function adap_tab_view_shortcuts_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_TAB_VIEW_SHORTCUTS : longint; { return type might be wrong }

{ enumerations from "adap-toast.h"  }
function adap_toast_priority_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_TOAST_PRIORITY : longint; { return type might be wrong }

{ enumerations from "adap-toolbar-view.h"  }
function adap_toolbar_style_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_TOOLBAR_STYLE : longint; { return type might be wrong }

{ enumerations from "adap-view-switcher.h"  }
function adap_view_switcher_policy_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function ADAP_TYPE_VIEW_SWITCHER_POLICY : longint; { return type might be wrong }

{ Generated data ends here  }

implementation

{ was #define dname def_expr }
function ADAP_TYPE_RESPONSE_APPEARANCE : longint; { return type might be wrong }
  begin
    ADAP_TYPE_RESPONSE_APPEARANCE:=adap_response_appearance_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_ANIMATION_STATE : longint; { return type might be wrong }
  begin
    ADAP_TYPE_ANIMATION_STATE:=adap_animation_state_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_BREAKPOINT_CONDITION_LENGTH_TYPE : longint; { return type might be wrong }
  begin
    ADAP_TYPE_BREAKPOINT_CONDITION_LENGTH_TYPE:=adap_breakpoint_condition_length_type_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_BREAKPOINT_CONDITION_RATIO_TYPE : longint; { return type might be wrong }
  begin
    ADAP_TYPE_BREAKPOINT_CONDITION_RATIO_TYPE:=adap_breakpoint_condition_ratio_type_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_DIALOG_PRESENTATION_MODE : longint; { return type might be wrong }
  begin
    ADAP_TYPE_DIALOG_PRESENTATION_MODE:=adap_dialog_presentation_mode_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_EASING : longint; { return type might be wrong }
  begin
    ADAP_TYPE_EASING:=adap_easing_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_FLAP_FOLD_POLICY : longint; { return type might be wrong }
  begin
    ADAP_TYPE_FLAP_FOLD_POLICY:=adap_flap_fold_policy_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_FLAP_TRANSITION_TYPE : longint; { return type might be wrong }
  begin
    ADAP_TYPE_FLAP_TRANSITION_TYPE:=adap_flap_transition_type_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_FOLD_THRESHOLD_POLICY : longint; { return type might be wrong }
  begin
    ADAP_TYPE_FOLD_THRESHOLD_POLICY:=adap_fold_threshold_policy_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_CENTERING_POLICY : longint; { return type might be wrong }
  begin
    ADAP_TYPE_CENTERING_POLICY:=adap_centering_policy_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_LEAFLET_TRANSITION_TYPE : longint; { return type might be wrong }
  begin
    ADAP_TYPE_LEAFLET_TRANSITION_TYPE:=adap_leaflet_transition_type_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_LENGTH_UNIT : longint; { return type might be wrong }
  begin
    ADAP_TYPE_LENGTH_UNIT:=adap_length_unit_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_NAVIGATION_DIRECTION : longint; { return type might be wrong }
  begin
    ADAP_TYPE_NAVIGATION_DIRECTION:=adap_navigation_direction_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_SQUEEZER_TRANSITION_TYPE : longint; { return type might be wrong }
  begin
    ADAP_TYPE_SQUEEZER_TRANSITION_TYPE:=adap_squeezer_transition_type_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_COLOR_SCHEME : longint; { return type might be wrong }
  begin
    ADAP_TYPE_COLOR_SCHEME:=adap_color_scheme_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_TAB_VIEW_SHORTCUTS : longint; { return type might be wrong }
  begin
    ADAP_TYPE_TAB_VIEW_SHORTCUTS:=adap_tab_view_shortcuts_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_TOAST_PRIORITY : longint; { return type might be wrong }
  begin
    ADAP_TYPE_TOAST_PRIORITY:=adap_toast_priority_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_TOOLBAR_STYLE : longint; { return type might be wrong }
  begin
    ADAP_TYPE_TOOLBAR_STYLE:=adap_toolbar_style_get_type;
  end;

{ was #define dname def_expr }
function ADAP_TYPE_VIEW_SWITCHER_POLICY : longint; { return type might be wrong }
  begin
    ADAP_TYPE_VIEW_SWITCHER_POLICY:=adap_view_switcher_policy_get_type;
  end;


end.
