unit static;

interface

uses
  fp_magiccore, magick_type;

  {$IFDEF FPC}
  {$PACKRECORDS C}
  {$ENDIF}


function InvokeStaticImageFilter(para1: pchar; para2: PPImage; para3: longint; para4: PPchar; para5: PExceptionInfo): TMagickBooleanType; cdecl; external libmagickcore;
function RegisterStaticModule(para1: pchar; exception: PExceptionInfo): TMagickBooleanType; cdecl; external libmagickcore;
function UnregisterStaticModule(para1: pchar): TMagickBooleanType; cdecl; external libmagickcore;
function RegisterAAIImage: Tsize_t; cdecl; external libmagickcore;
function RegisterARTImage: Tsize_t; cdecl; external libmagickcore;
function RegisterAVIImage: Tsize_t; cdecl; external libmagickcore;
function RegisterAVSImage: Tsize_t; cdecl; external libmagickcore;
function RegisterBIEImage: Tsize_t; cdecl; external libmagickcore;
function RegisterBGRImage: Tsize_t; cdecl; external libmagickcore;
function RegisterBMPImage: Tsize_t; cdecl; external libmagickcore;
function RegisterBRAILLEImage: Tsize_t; cdecl; external libmagickcore;
function RegisterCALSImage: Tsize_t; cdecl; external libmagickcore;
function RegisterCAPTIONImage: Tsize_t; cdecl; external libmagickcore;
function RegisterCINImage: Tsize_t; cdecl; external libmagickcore;
function RegisterCIPImage: Tsize_t; cdecl; external libmagickcore;
function RegisterCLIPImage: Tsize_t; cdecl; external libmagickcore;
function RegisterCLIPBOARDImage: Tsize_t; cdecl; external libmagickcore;
function RegisterCMYKImage: Tsize_t; cdecl; external libmagickcore;
function RegisterCUTImage: Tsize_t; cdecl; external libmagickcore;
function RegisterDCMImage: Tsize_t; cdecl; external libmagickcore;
function RegisterDCXImage: Tsize_t; cdecl; external libmagickcore;
function RegisterDDSImage: Tsize_t; cdecl; external libmagickcore;
function RegisterDEBUGImage: Tsize_t; cdecl; external libmagickcore;
function RegisterDIBImage: Tsize_t; cdecl; external libmagickcore;
function RegisterDJVUImage: Tsize_t; cdecl; external libmagickcore;
function RegisterDNGImage: Tsize_t; cdecl; external libmagickcore;
function RegisterDOTImage: Tsize_t; cdecl; external libmagickcore;
function RegisterDPSImage: Tsize_t; cdecl; external libmagickcore;
function RegisterDPXImage: Tsize_t; cdecl; external libmagickcore;
function RegisterEMFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterEPDFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterEPIImage: Tsize_t; cdecl; external libmagickcore;
function RegisterEPSImage: Tsize_t; cdecl; external libmagickcore;
function RegisterEPS2Image: Tsize_t; cdecl; external libmagickcore;
function RegisterEPSFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterEPSIImage: Tsize_t; cdecl; external libmagickcore;
function RegisterEPTImage: Tsize_t; cdecl; external libmagickcore;
function RegisterEXRImage: Tsize_t; cdecl; external libmagickcore;
function RegisterFAXImage: Tsize_t; cdecl; external libmagickcore;
function RegisterFITSImage: Tsize_t; cdecl; external libmagickcore;
function RegisterFLIFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterFPXImage: Tsize_t; cdecl; external libmagickcore;
function RegisterG3Image: Tsize_t; cdecl; external libmagickcore;
function RegisterGIFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterGIF87Image: Tsize_t; cdecl; external libmagickcore;
function RegisterGRADIENTImage: Tsize_t; cdecl; external libmagickcore;
function RegisterGRANITEImage: Tsize_t; cdecl; external libmagickcore;
function RegisterGRAYImage: Tsize_t; cdecl; external libmagickcore;
function RegisterHALDImage: Tsize_t; cdecl; external libmagickcore;
function RegisterHDRImage: Tsize_t; cdecl; external libmagickcore;
function RegisterHEICImage: Tsize_t; cdecl; external libmagickcore;
function RegisterHImage: Tsize_t; cdecl; external libmagickcore;
function RegisterHISTOGRAMImage: Tsize_t; cdecl; external libmagickcore;
function RegisterHRZImage: Tsize_t; cdecl; external libmagickcore;
function RegisterHTMLImage: Tsize_t; cdecl; external libmagickcore;
function RegisterICBImage: Tsize_t; cdecl; external libmagickcore;
function RegisterICONImage: Tsize_t; cdecl; external libmagickcore;
function RegisterINFOImage: Tsize_t; cdecl; external libmagickcore;
function RegisterINLINEImage: Tsize_t; cdecl; external libmagickcore;
function RegisterIPLImage: Tsize_t; cdecl; external libmagickcore;
function RegisterJBGImage: Tsize_t; cdecl; external libmagickcore;
function RegisterJBIGImage: Tsize_t; cdecl; external libmagickcore;
function RegisterJNXImage: Tsize_t; cdecl; external libmagickcore;
function RegisterJPEGImage: Tsize_t; cdecl; external libmagickcore;
function RegisterJP2Image: Tsize_t; cdecl; external libmagickcore;
function RegisterJSONImage: Tsize_t; cdecl; external libmagickcore;
function RegisterLABELImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMACImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMAGICKImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMAPImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMASKImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMATImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMATTEImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMETAImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMIFFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMNGImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMONOImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMPCImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMPRImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMSLImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMTVImage: Tsize_t; cdecl; external libmagickcore;
function RegisterMVGImage: Tsize_t; cdecl; external libmagickcore;
function RegisterNETSCAPEImage: Tsize_t; cdecl; external libmagickcore;
function RegisterNULLImage: Tsize_t; cdecl; external libmagickcore;
function RegisterP7Image: Tsize_t; cdecl; external libmagickcore;
function RegisterPBMImage: Tsize_t; cdecl; external libmagickcore;
function RegisterOTBImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPALMImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPANGOImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPATTERNImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPCDImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPCDSImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPCLImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPCTImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPCXImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPDBImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPDFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPESImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPGXImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPICImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPICTImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPIXImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPGMImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPLASMAImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPMImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPNGImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPNMImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPPMImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPREVIEWImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPSImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPS2Image: Tsize_t; cdecl; external libmagickcore;
function RegisterPS3Image: Tsize_t; cdecl; external libmagickcore;
function RegisterPSDImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPTIFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterPWPImage: Tsize_t; cdecl; external libmagickcore;
function RegisterRASImage: Tsize_t; cdecl; external libmagickcore;
function RegisterRAWImage: Tsize_t; cdecl; external libmagickcore;
function RegisterRGBImage: Tsize_t; cdecl; external libmagickcore;
function RegisterRGBAImage: Tsize_t; cdecl; external libmagickcore;
function RegisterRGFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterRLAImage: Tsize_t; cdecl; external libmagickcore;
function RegisterRLEImage: Tsize_t; cdecl; external libmagickcore;
function RegisterSCRImage: Tsize_t; cdecl; external libmagickcore;
function RegisterSCREENSHOTImage: Tsize_t; cdecl; external libmagickcore;
function RegisterSCTImage: Tsize_t; cdecl; external libmagickcore;
function RegisterSFWImage: Tsize_t; cdecl; external libmagickcore;
function RegisterSGIImage: Tsize_t; cdecl; external libmagickcore;
function RegisterSHTMLImage: Tsize_t; cdecl; external libmagickcore;
function RegisterSIXELImage: Tsize_t; cdecl; external libmagickcore;
function RegisterSTEGANOImage: Tsize_t; cdecl; external libmagickcore;
function RegisterSUNImage: Tsize_t; cdecl; external libmagickcore;
function RegisterSVGImage: Tsize_t; cdecl; external libmagickcore;
function RegisterTEXTImage: Tsize_t; cdecl; external libmagickcore;
function RegisterTGAImage: Tsize_t; cdecl; external libmagickcore;
function RegisterTHUMBNAILImage: Tsize_t; cdecl; external libmagickcore;
function RegisterTIFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterTIFFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterTILEImage: Tsize_t; cdecl; external libmagickcore;
function RegisterTIMImage: Tsize_t; cdecl; external libmagickcore;
function RegisterTTFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterTXTImage: Tsize_t; cdecl; external libmagickcore;
function RegisterUILImage: Tsize_t; cdecl; external libmagickcore;
function RegisterURLImage: Tsize_t; cdecl; external libmagickcore;
function RegisterUYVYImage: Tsize_t; cdecl; external libmagickcore;
function RegisterVDAImage: Tsize_t; cdecl; external libmagickcore;
function RegisterVICARImage: Tsize_t; cdecl; external libmagickcore;
function RegisterVIDImage: Tsize_t; cdecl; external libmagickcore;
function RegisterVIDEOImage: Tsize_t; cdecl; external libmagickcore;
function RegisterVIFFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterVIPSImage: Tsize_t; cdecl; external libmagickcore;
function RegisterVSTImage: Tsize_t; cdecl; external libmagickcore;
function RegisterWBMPImage: Tsize_t; cdecl; external libmagickcore;
function RegisterWEBPImage: Tsize_t; cdecl; external libmagickcore;
function RegisterWMFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterWPGImage: Tsize_t; cdecl; external libmagickcore;
function RegisterXImage: Tsize_t; cdecl; external libmagickcore;
function RegisterXBMImage: Tsize_t; cdecl; external libmagickcore;
function RegisterXCImage: Tsize_t; cdecl; external libmagickcore;
function RegisterXCFImage: Tsize_t; cdecl; external libmagickcore;
function RegisterXPMImage: Tsize_t; cdecl; external libmagickcore;
function RegisterXPSImage: Tsize_t; cdecl; external libmagickcore;
function RegisterXVImage: Tsize_t; cdecl; external libmagickcore;
function RegisterXWDImage: Tsize_t; cdecl; external libmagickcore;
function RegisterYCBCRImage: Tsize_t; cdecl; external libmagickcore;
function RegisterYUVImage: Tsize_t; cdecl; external libmagickcore;
procedure UnregisterAAIImage; cdecl; external libmagickcore;
procedure UnregisterARTImage; cdecl; external libmagickcore;
procedure UnregisterAVIImage; cdecl; external libmagickcore;
procedure UnregisterAVSImage; cdecl; external libmagickcore;
procedure UnregisterBIEImage; cdecl; external libmagickcore;
procedure UnregisterBGRImage; cdecl; external libmagickcore;
procedure UnregisterBMPImage; cdecl; external libmagickcore;
procedure UnregisterBRAILLEImage; cdecl; external libmagickcore;
procedure UnregisterCALSImage; cdecl; external libmagickcore;
procedure UnregisterCAPTIONImage; cdecl; external libmagickcore;
procedure UnregisterCINImage; cdecl; external libmagickcore;
procedure UnregisterCIPImage; cdecl; external libmagickcore;
procedure UnregisterCLIPImage; cdecl; external libmagickcore;
procedure UnregisterCLIPBOARDImage; cdecl; external libmagickcore;
procedure UnregisterCMYKImage; cdecl; external libmagickcore;
procedure UnregisterCUTImage; cdecl; external libmagickcore;
procedure UnregisterDCMImage; cdecl; external libmagickcore;
procedure UnregisterDCXImage; cdecl; external libmagickcore;
procedure UnregisterDDSImage; cdecl; external libmagickcore;
procedure UnregisterDEBUGImage; cdecl; external libmagickcore;
procedure UnregisterDIBImage; cdecl; external libmagickcore;
procedure UnregisterDJVUImage; cdecl; external libmagickcore;
procedure UnregisterDNGImage; cdecl; external libmagickcore;
procedure UnregisterDOTImage; cdecl; external libmagickcore;
procedure UnregisterDPSImage; cdecl; external libmagickcore;
procedure UnregisterDPXImage; cdecl; external libmagickcore;
procedure UnregisterEMFImage; cdecl; external libmagickcore;
procedure UnregisterEPDFImage; cdecl; external libmagickcore;
procedure UnregisterEPIImage; cdecl; external libmagickcore;
procedure UnregisterEPSImage; cdecl; external libmagickcore;
procedure UnregisterEPS2Image; cdecl; external libmagickcore;
procedure UnregisterEPSFImage; cdecl; external libmagickcore;
procedure UnregisterEPSIImage; cdecl; external libmagickcore;
procedure UnregisterEPTImage; cdecl; external libmagickcore;
procedure UnregisterEXRImage; cdecl; external libmagickcore;
procedure UnregisterFAXImage; cdecl; external libmagickcore;
procedure UnregisterFITSImage; cdecl; external libmagickcore;
procedure UnregisterFLIFImage; cdecl; external libmagickcore;
procedure UnregisterFPXImage; cdecl; external libmagickcore;
procedure UnregisterG3Image; cdecl; external libmagickcore;
procedure UnregisterGIFImage; cdecl; external libmagickcore;
procedure UnregisterGIF87Image; cdecl; external libmagickcore;
procedure UnregisterGRADIENTImage; cdecl; external libmagickcore;
procedure UnregisterGRANITEImage; cdecl; external libmagickcore;
procedure UnregisterGRAYImage; cdecl; external libmagickcore;
procedure UnregisterHALDImage; cdecl; external libmagickcore;
procedure UnregisterHDRImage; cdecl; external libmagickcore;
procedure UnregisterHEICImage; cdecl; external libmagickcore;
procedure UnregisterHImage; cdecl; external libmagickcore;
procedure UnregisterHISTOGRAMImage; cdecl; external libmagickcore;
procedure UnregisterHRZImage; cdecl; external libmagickcore;
procedure UnregisterHTMLImage; cdecl; external libmagickcore;
procedure UnregisterICBImage; cdecl; external libmagickcore;
procedure UnregisterICONImage; cdecl; external libmagickcore;
procedure UnregisterINFOImage; cdecl; external libmagickcore;
procedure UnregisterINLINEImage; cdecl; external libmagickcore;
procedure UnregisterIPLImage; cdecl; external libmagickcore;
procedure UnregisterJBGImage; cdecl; external libmagickcore;
procedure UnregisterJBIGImage; cdecl; external libmagickcore;
procedure UnregisterJNXImage; cdecl; external libmagickcore;
procedure UnregisterJPEGImage; cdecl; external libmagickcore;
procedure UnregisterJP2Image; cdecl; external libmagickcore;
procedure UnregisterJSONImage; cdecl; external libmagickcore;
procedure UnregisterLABELImage; cdecl; external libmagickcore;
procedure UnregisterLOCALEImage; cdecl; external libmagickcore;
procedure UnregisterMACImage; cdecl; external libmagickcore;
procedure UnregisterMAGICKImage; cdecl; external libmagickcore;
procedure UnregisterMAPImage; cdecl; external libmagickcore;
procedure UnregisterMASKImage; cdecl; external libmagickcore;
procedure UnregisterMATImage; cdecl; external libmagickcore;
procedure UnregisterMATTEImage; cdecl; external libmagickcore;
procedure UnregisterMETAImage; cdecl; external libmagickcore;
procedure UnregisterMIFFImage; cdecl; external libmagickcore;
procedure UnregisterMNGImage; cdecl; external libmagickcore;
procedure UnregisterMONOImage; cdecl; external libmagickcore;
procedure UnregisterMPCImage; cdecl; external libmagickcore;
procedure UnregisterMPRImage; cdecl; external libmagickcore;
procedure UnregisterMSLImage; cdecl; external libmagickcore;
procedure UnregisterMTVImage; cdecl; external libmagickcore;
procedure UnregisterMVGImage; cdecl; external libmagickcore;
procedure UnregisterNETSCAPEImage; cdecl; external libmagickcore;
procedure UnregisterNULLImage; cdecl; external libmagickcore;
procedure UnregisterP7Image; cdecl; external libmagickcore;
procedure UnregisterPBMImage; cdecl; external libmagickcore;
procedure UnregisterOTBImage; cdecl; external libmagickcore;
procedure UnregisterPALMImage; cdecl; external libmagickcore;
procedure UnregisterPANGOImage; cdecl; external libmagickcore;
procedure UnregisterPATTERNImage; cdecl; external libmagickcore;
procedure UnregisterPCDImage; cdecl; external libmagickcore;
procedure UnregisterPCDSImage; cdecl; external libmagickcore;
procedure UnregisterPCLImage; cdecl; external libmagickcore;
procedure UnregisterPCTImage; cdecl; external libmagickcore;
procedure UnregisterPCXImage; cdecl; external libmagickcore;
procedure UnregisterPDBImage; cdecl; external libmagickcore;
procedure UnregisterPDFImage; cdecl; external libmagickcore;
procedure UnregisterPESImage; cdecl; external libmagickcore;
procedure UnregisterPGXImage; cdecl; external libmagickcore;
procedure UnregisterPICImage; cdecl; external libmagickcore;
procedure UnregisterPICTImage; cdecl; external libmagickcore;
procedure UnregisterPIXImage; cdecl; external libmagickcore;
procedure UnregisterPLASMAImage; cdecl; external libmagickcore;
procedure UnregisterPGMImage; cdecl; external libmagickcore;
procedure UnregisterPMImage; cdecl; external libmagickcore;
procedure UnregisterPNGImage; cdecl; external libmagickcore;
procedure UnregisterPNMImage; cdecl; external libmagickcore;
procedure UnregisterPPMImage; cdecl; external libmagickcore;
procedure UnregisterPREVIEWImage; cdecl; external libmagickcore;
procedure UnregisterPSImage; cdecl; external libmagickcore;
procedure UnregisterPS2Image; cdecl; external libmagickcore;
procedure UnregisterPS3Image; cdecl; external libmagickcore;
procedure UnregisterPSDImage; cdecl; external libmagickcore;
procedure UnregisterPTIFImage; cdecl; external libmagickcore;
procedure UnregisterPWPImage; cdecl; external libmagickcore;
procedure UnregisterRASImage; cdecl; external libmagickcore;
procedure UnregisterRAWImage; cdecl; external libmagickcore;
procedure UnregisterRGBImage; cdecl; external libmagickcore;
procedure UnregisterRGBAImage; cdecl; external libmagickcore;
procedure UnregisterRGFImage; cdecl; external libmagickcore;
procedure UnregisterRLAImage; cdecl; external libmagickcore;
procedure UnregisterRLEImage; cdecl; external libmagickcore;
procedure UnregisterSCRImage; cdecl; external libmagickcore;
procedure UnregisterSCREENSHOTImage; cdecl; external libmagickcore;
procedure UnregisterSCTImage; cdecl; external libmagickcore;
procedure UnregisterSFWImage; cdecl; external libmagickcore;
procedure UnregisterSGIImage; cdecl; external libmagickcore;
procedure UnregisterSHTMLImage; cdecl; external libmagickcore;
procedure UnregisterSIXELImage; cdecl; external libmagickcore;
procedure UnregisterSTEGANOImage; cdecl; external libmagickcore;
procedure UnregisterSUNImage; cdecl; external libmagickcore;
procedure UnregisterSVGImage; cdecl; external libmagickcore;
procedure UnregisterTEXTImage; cdecl; external libmagickcore;
procedure UnregisterTGAImage; cdecl; external libmagickcore;
procedure UnregisterTHUMBNAILImage; cdecl; external libmagickcore;
procedure UnregisterTIFImage; cdecl; external libmagickcore;
procedure UnregisterTIFFImage; cdecl; external libmagickcore;
procedure UnregisterTILEImage; cdecl; external libmagickcore;
procedure UnregisterTIMImage; cdecl; external libmagickcore;
procedure UnregisterTTFImage; cdecl; external libmagickcore;
procedure UnregisterTXTImage; cdecl; external libmagickcore;
procedure UnregisterUILImage; cdecl; external libmagickcore;
procedure UnregisterURLImage; cdecl; external libmagickcore;
procedure UnregisterUYVYImage; cdecl; external libmagickcore;
procedure UnregisterVDAImage; cdecl; external libmagickcore;
procedure UnregisterVICARImage; cdecl; external libmagickcore;
procedure UnregisterVIDImage; cdecl; external libmagickcore;
procedure UnregisterVIDEOImage; cdecl; external libmagickcore;
procedure UnregisterVIFFImage; cdecl; external libmagickcore;
procedure UnregisterVIPSImage; cdecl; external libmagickcore;
procedure UnregisterVSTImage; cdecl; external libmagickcore;
procedure UnregisterWBMPImage; cdecl; external libmagickcore;
procedure UnregisterWEBPImage; cdecl; external libmagickcore;
procedure UnregisterWMFImage; cdecl; external libmagickcore;
procedure UnregisterWPGImage; cdecl; external libmagickcore;
procedure UnregisterXImage; cdecl; external libmagickcore;
procedure UnregisterXBMImage; cdecl; external libmagickcore;
procedure UnregisterXCImage; cdecl; external libmagickcore;
procedure UnregisterXCFImage; cdecl; external libmagickcore;
procedure UnregisterXPMImage; cdecl; external libmagickcore;
procedure UnregisterXPSImage; cdecl; external libmagickcore;
procedure UnregisterXVImage; cdecl; external libmagickcore;
procedure UnregisterXWDImage; cdecl; external libmagickcore;
procedure UnregisterYCBCRImage; cdecl; external libmagickcore;
procedure UnregisterYUVImage; cdecl; external libmagickcore;
procedure RegisterStaticModules; cdecl; external libmagickcore;
procedure UnregisterStaticModules; cdecl; external libmagickcore;

// === Konventiert am: 6-1-26 14:01:03 ===


implementation



end.
