
unit xmlunicode;
interface

{
  Automatically converted by H2Pas 1.0.0 from xmlunicode.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    xmlunicode.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

Type
Pchar  = ^char;
{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{
 * Summary: Unicode character APIs
 * Description: API for the Unicode character APIs
 *
 * This file is automatically generated from the
 * UCS description files of the Unicode Character Database
 * http://www.unicode.org/Public/4.0-Update1/UCD-4.0.1.html
 * using the genUnicode.py Python script.
 *
 * Generation date: Mon Mar 27 11:09:52 2006
 * Sources: Blocks-4.0.1.txt UnicodeData-4.0.1.txt
 * Author: Daniel Veillard
  }
{$ifndef __XML_UNICODE_H__}
{$define __XML_UNICODE_H__}
{$include <libxml/xmlversion.h>}
{$ifdef LIBXML_UNICODE_ENABLED}
{ C++ extern C conditionnal removed }

function xmlUCSIsAegeanNumbers(code:longint):longint;cdecl;external;
function xmlUCSIsAlphabeticPresentationForms(code:longint):longint;cdecl;external;
function xmlUCSIsArabic(code:longint):longint;cdecl;external;
function xmlUCSIsArabicPresentationFormsA(code:longint):longint;cdecl;external;
function xmlUCSIsArabicPresentationFormsB(code:longint):longint;cdecl;external;
function xmlUCSIsArmenian(code:longint):longint;cdecl;external;
function xmlUCSIsArrows(code:longint):longint;cdecl;external;
function xmlUCSIsBasicLatin(code:longint):longint;cdecl;external;
function xmlUCSIsBengali(code:longint):longint;cdecl;external;
function xmlUCSIsBlockElements(code:longint):longint;cdecl;external;
function xmlUCSIsBopomofo(code:longint):longint;cdecl;external;
function xmlUCSIsBopomofoExtended(code:longint):longint;cdecl;external;
function xmlUCSIsBoxDrawing(code:longint):longint;cdecl;external;
function xmlUCSIsBraillePatterns(code:longint):longint;cdecl;external;
function xmlUCSIsBuhid(code:longint):longint;cdecl;external;
function xmlUCSIsByzantineMusicalSymbols(code:longint):longint;cdecl;external;
function xmlUCSIsCJKCompatibility(code:longint):longint;cdecl;external;
function xmlUCSIsCJKCompatibilityForms(code:longint):longint;cdecl;external;
function xmlUCSIsCJKCompatibilityIdeographs(code:longint):longint;cdecl;external;
function xmlUCSIsCJKCompatibilityIdeographsSupplement(code:longint):longint;cdecl;external;
function xmlUCSIsCJKRadicalsSupplement(code:longint):longint;cdecl;external;
function xmlUCSIsCJKSymbolsandPunctuation(code:longint):longint;cdecl;external;
function xmlUCSIsCJKUnifiedIdeographs(code:longint):longint;cdecl;external;
function xmlUCSIsCJKUnifiedIdeographsExtensionA(code:longint):longint;cdecl;external;
function xmlUCSIsCJKUnifiedIdeographsExtensionB(code:longint):longint;cdecl;external;
function xmlUCSIsCherokee(code:longint):longint;cdecl;external;
function xmlUCSIsCombiningDiacriticalMarks(code:longint):longint;cdecl;external;
function xmlUCSIsCombiningDiacriticalMarksforSymbols(code:longint):longint;cdecl;external;
function xmlUCSIsCombiningHalfMarks(code:longint):longint;cdecl;external;
function xmlUCSIsCombiningMarksforSymbols(code:longint):longint;cdecl;external;
function xmlUCSIsControlPictures(code:longint):longint;cdecl;external;
function xmlUCSIsCurrencySymbols(code:longint):longint;cdecl;external;
function xmlUCSIsCypriotSyllabary(code:longint):longint;cdecl;external;
function xmlUCSIsCyrillic(code:longint):longint;cdecl;external;
function xmlUCSIsCyrillicSupplement(code:longint):longint;cdecl;external;
function xmlUCSIsDeseret(code:longint):longint;cdecl;external;
function xmlUCSIsDevanagari(code:longint):longint;cdecl;external;
function xmlUCSIsDingbats(code:longint):longint;cdecl;external;
function xmlUCSIsEnclosedAlphanumerics(code:longint):longint;cdecl;external;
function xmlUCSIsEnclosedCJKLettersandMonths(code:longint):longint;cdecl;external;
function xmlUCSIsEthiopic(code:longint):longint;cdecl;external;
function xmlUCSIsGeneralPunctuation(code:longint):longint;cdecl;external;
function xmlUCSIsGeometricShapes(code:longint):longint;cdecl;external;
function xmlUCSIsGeorgian(code:longint):longint;cdecl;external;
function xmlUCSIsGothic(code:longint):longint;cdecl;external;
function xmlUCSIsGreek(code:longint):longint;cdecl;external;
function xmlUCSIsGreekExtended(code:longint):longint;cdecl;external;
function xmlUCSIsGreekandCoptic(code:longint):longint;cdecl;external;
function xmlUCSIsGujarati(code:longint):longint;cdecl;external;
function xmlUCSIsGurmukhi(code:longint):longint;cdecl;external;
function xmlUCSIsHalfwidthandFullwidthForms(code:longint):longint;cdecl;external;
function xmlUCSIsHangulCompatibilityJamo(code:longint):longint;cdecl;external;
function xmlUCSIsHangulJamo(code:longint):longint;cdecl;external;
function xmlUCSIsHangulSyllables(code:longint):longint;cdecl;external;
function xmlUCSIsHanunoo(code:longint):longint;cdecl;external;
function xmlUCSIsHebrew(code:longint):longint;cdecl;external;
function xmlUCSIsHighPrivateUseSurrogates(code:longint):longint;cdecl;external;
function xmlUCSIsHighSurrogates(code:longint):longint;cdecl;external;
function xmlUCSIsHiragana(code:longint):longint;cdecl;external;
function xmlUCSIsIPAExtensions(code:longint):longint;cdecl;external;
function xmlUCSIsIdeographicDescriptionCharacters(code:longint):longint;cdecl;external;
function xmlUCSIsKanbun(code:longint):longint;cdecl;external;
function xmlUCSIsKangxiRadicals(code:longint):longint;cdecl;external;
function xmlUCSIsKannada(code:longint):longint;cdecl;external;
function xmlUCSIsKatakana(code:longint):longint;cdecl;external;
function xmlUCSIsKatakanaPhoneticExtensions(code:longint):longint;cdecl;external;
function xmlUCSIsKhmer(code:longint):longint;cdecl;external;
function xmlUCSIsKhmerSymbols(code:longint):longint;cdecl;external;
function xmlUCSIsLao(code:longint):longint;cdecl;external;
function xmlUCSIsLatin1Supplement(code:longint):longint;cdecl;external;
function xmlUCSIsLatinExtendedA(code:longint):longint;cdecl;external;
function xmlUCSIsLatinExtendedB(code:longint):longint;cdecl;external;
function xmlUCSIsLatinExtendedAdditional(code:longint):longint;cdecl;external;
function xmlUCSIsLetterlikeSymbols(code:longint):longint;cdecl;external;
function xmlUCSIsLimbu(code:longint):longint;cdecl;external;
function xmlUCSIsLinearBIdeograms(code:longint):longint;cdecl;external;
function xmlUCSIsLinearBSyllabary(code:longint):longint;cdecl;external;
function xmlUCSIsLowSurrogates(code:longint):longint;cdecl;external;
function xmlUCSIsMalayalam(code:longint):longint;cdecl;external;
function xmlUCSIsMathematicalAlphanumericSymbols(code:longint):longint;cdecl;external;
function xmlUCSIsMathematicalOperators(code:longint):longint;cdecl;external;
function xmlUCSIsMiscellaneousMathematicalSymbolsA(code:longint):longint;cdecl;external;
function xmlUCSIsMiscellaneousMathematicalSymbolsB(code:longint):longint;cdecl;external;
function xmlUCSIsMiscellaneousSymbols(code:longint):longint;cdecl;external;
function xmlUCSIsMiscellaneousSymbolsandArrows(code:longint):longint;cdecl;external;
function xmlUCSIsMiscellaneousTechnical(code:longint):longint;cdecl;external;
function xmlUCSIsMongolian(code:longint):longint;cdecl;external;
function xmlUCSIsMusicalSymbols(code:longint):longint;cdecl;external;
function xmlUCSIsMyanmar(code:longint):longint;cdecl;external;
function xmlUCSIsNumberForms(code:longint):longint;cdecl;external;
function xmlUCSIsOgham(code:longint):longint;cdecl;external;
function xmlUCSIsOldItalic(code:longint):longint;cdecl;external;
function xmlUCSIsOpticalCharacterRecognition(code:longint):longint;cdecl;external;
function xmlUCSIsOriya(code:longint):longint;cdecl;external;
function xmlUCSIsOsmanya(code:longint):longint;cdecl;external;
function xmlUCSIsPhoneticExtensions(code:longint):longint;cdecl;external;
function xmlUCSIsPrivateUse(code:longint):longint;cdecl;external;
function xmlUCSIsPrivateUseArea(code:longint):longint;cdecl;external;
function xmlUCSIsRunic(code:longint):longint;cdecl;external;
function xmlUCSIsShavian(code:longint):longint;cdecl;external;
function xmlUCSIsSinhala(code:longint):longint;cdecl;external;
function xmlUCSIsSmallFormVariants(code:longint):longint;cdecl;external;
function xmlUCSIsSpacingModifierLetters(code:longint):longint;cdecl;external;
function xmlUCSIsSpecials(code:longint):longint;cdecl;external;
function xmlUCSIsSuperscriptsandSubscripts(code:longint):longint;cdecl;external;
function xmlUCSIsSupplementalArrowsA(code:longint):longint;cdecl;external;
function xmlUCSIsSupplementalArrowsB(code:longint):longint;cdecl;external;
function xmlUCSIsSupplementalMathematicalOperators(code:longint):longint;cdecl;external;
function xmlUCSIsSupplementaryPrivateUseAreaA(code:longint):longint;cdecl;external;
function xmlUCSIsSupplementaryPrivateUseAreaB(code:longint):longint;cdecl;external;
function xmlUCSIsSyriac(code:longint):longint;cdecl;external;
function xmlUCSIsTagalog(code:longint):longint;cdecl;external;
function xmlUCSIsTagbanwa(code:longint):longint;cdecl;external;
function xmlUCSIsTags(code:longint):longint;cdecl;external;
function xmlUCSIsTaiLe(code:longint):longint;cdecl;external;
function xmlUCSIsTaiXuanJingSymbols(code:longint):longint;cdecl;external;
function xmlUCSIsTamil(code:longint):longint;cdecl;external;
function xmlUCSIsTelugu(code:longint):longint;cdecl;external;
function xmlUCSIsThaana(code:longint):longint;cdecl;external;
function xmlUCSIsThai(code:longint):longint;cdecl;external;
function xmlUCSIsTibetan(code:longint):longint;cdecl;external;
function xmlUCSIsUgaritic(code:longint):longint;cdecl;external;
function xmlUCSIsUnifiedCanadianAboriginalSyllabics(code:longint):longint;cdecl;external;
function xmlUCSIsVariationSelectors(code:longint):longint;cdecl;external;
function xmlUCSIsVariationSelectorsSupplement(code:longint):longint;cdecl;external;
function xmlUCSIsYiRadicals(code:longint):longint;cdecl;external;
function xmlUCSIsYiSyllables(code:longint):longint;cdecl;external;
function xmlUCSIsYijingHexagramSymbols(code:longint):longint;cdecl;external;
(* Const before type ignored *)
function xmlUCSIsBlock(code:longint; block:Pchar):longint;cdecl;external;
function xmlUCSIsCatC(code:longint):longint;cdecl;external;
function xmlUCSIsCatCc(code:longint):longint;cdecl;external;
function xmlUCSIsCatCf(code:longint):longint;cdecl;external;
function xmlUCSIsCatCo(code:longint):longint;cdecl;external;
function xmlUCSIsCatCs(code:longint):longint;cdecl;external;
function xmlUCSIsCatL(code:longint):longint;cdecl;external;
function xmlUCSIsCatLl(code:longint):longint;cdecl;external;
function xmlUCSIsCatLm(code:longint):longint;cdecl;external;
function xmlUCSIsCatLo(code:longint):longint;cdecl;external;
function xmlUCSIsCatLt(code:longint):longint;cdecl;external;
function xmlUCSIsCatLu(code:longint):longint;cdecl;external;
function xmlUCSIsCatM(code:longint):longint;cdecl;external;
function xmlUCSIsCatMc(code:longint):longint;cdecl;external;
function xmlUCSIsCatMe(code:longint):longint;cdecl;external;
function xmlUCSIsCatMn(code:longint):longint;cdecl;external;
function xmlUCSIsCatN(code:longint):longint;cdecl;external;
function xmlUCSIsCatNd(code:longint):longint;cdecl;external;
function xmlUCSIsCatNl(code:longint):longint;cdecl;external;
function xmlUCSIsCatNo(code:longint):longint;cdecl;external;
function xmlUCSIsCatP(code:longint):longint;cdecl;external;
function xmlUCSIsCatPc(code:longint):longint;cdecl;external;
function xmlUCSIsCatPd(code:longint):longint;cdecl;external;
function xmlUCSIsCatPe(code:longint):longint;cdecl;external;
function xmlUCSIsCatPf(code:longint):longint;cdecl;external;
function xmlUCSIsCatPi(code:longint):longint;cdecl;external;
function xmlUCSIsCatPo(code:longint):longint;cdecl;external;
function xmlUCSIsCatPs(code:longint):longint;cdecl;external;
function xmlUCSIsCatS(code:longint):longint;cdecl;external;
function xmlUCSIsCatSc(code:longint):longint;cdecl;external;
function xmlUCSIsCatSk(code:longint):longint;cdecl;external;
function xmlUCSIsCatSm(code:longint):longint;cdecl;external;
function xmlUCSIsCatSo(code:longint):longint;cdecl;external;
function xmlUCSIsCatZ(code:longint):longint;cdecl;external;
function xmlUCSIsCatZl(code:longint):longint;cdecl;external;
function xmlUCSIsCatZp(code:longint):longint;cdecl;external;
function xmlUCSIsCatZs(code:longint):longint;cdecl;external;
(* Const before type ignored *)
function xmlUCSIsCat(code:longint; cat:Pchar):longint;cdecl;external;
{ C++ end of extern C conditionnal removed }
{$endif}
{ LIBXML_UNICODE_ENABLED  }
{$endif}
{ __XML_UNICODE_H__  }

implementation


end.
