/*
 * Summary: Unicode character APIs
 * Description: API for the Unicode character APIs
 *
 * This file is automatically generated from the
 * UCS description files of the Unicode Character Database
 * http://www.unicode.org/Public/4.0-Update1/UCD-4.0.1.html
 * using the genUnicode.py Python script.
 *
 * Generation date: Mon Mar 27 11:09:52 2006
 * Sources: Blocks-4.0.1.txt UnicodeData-4.0.1.txt
 * Author: Daniel Veillard
 */

#ifndef __XML_UNICODE_H__
#define __XML_UNICODE_H__

#include <libxml/xmlversion.h>

#ifdef LIBXML_UNICODE_ENABLED

#ifdef __cplusplus
extern "C" {
#endif

extern int  xmlUCSIsAegeanNumbers	(int code);
extern int  xmlUCSIsAlphabeticPresentationForms	(int code);
extern int  xmlUCSIsArabic	(int code);
extern int  xmlUCSIsArabicPresentationFormsA	(int code);
extern int  xmlUCSIsArabicPresentationFormsB	(int code);
extern int  xmlUCSIsArmenian	(int code);
extern int  xmlUCSIsArrows	(int code);
extern int  xmlUCSIsBasicLatin	(int code);
extern int  xmlUCSIsBengali	(int code);
extern int  xmlUCSIsBlockElements	(int code);
extern int  xmlUCSIsBopomofo	(int code);
extern int  xmlUCSIsBopomofoExtended	(int code);
extern int  xmlUCSIsBoxDrawing	(int code);
extern int  xmlUCSIsBraillePatterns	(int code);
extern int  xmlUCSIsBuhid	(int code);
extern int  xmlUCSIsByzantineMusicalSymbols	(int code);
extern int  xmlUCSIsCJKCompatibility	(int code);
extern int  xmlUCSIsCJKCompatibilityForms	(int code);
extern int  xmlUCSIsCJKCompatibilityIdeographs	(int code);
extern int  xmlUCSIsCJKCompatibilityIdeographsSupplement	(int code);
extern int  xmlUCSIsCJKRadicalsSupplement	(int code);
extern int  xmlUCSIsCJKSymbolsandPunctuation	(int code);
extern int  xmlUCSIsCJKUnifiedIdeographs	(int code);
extern int  xmlUCSIsCJKUnifiedIdeographsExtensionA	(int code);
extern int  xmlUCSIsCJKUnifiedIdeographsExtensionB	(int code);
extern int  xmlUCSIsCherokee	(int code);
extern int  xmlUCSIsCombiningDiacriticalMarks	(int code);
extern int  xmlUCSIsCombiningDiacriticalMarksforSymbols	(int code);
extern int  xmlUCSIsCombiningHalfMarks	(int code);
extern int  xmlUCSIsCombiningMarksforSymbols	(int code);
extern int  xmlUCSIsControlPictures	(int code);
extern int  xmlUCSIsCurrencySymbols	(int code);
extern int  xmlUCSIsCypriotSyllabary	(int code);
extern int  xmlUCSIsCyrillic	(int code);
extern int  xmlUCSIsCyrillicSupplement	(int code);
extern int  xmlUCSIsDeseret	(int code);
extern int  xmlUCSIsDevanagari	(int code);
extern int  xmlUCSIsDingbats	(int code);
extern int  xmlUCSIsEnclosedAlphanumerics	(int code);
extern int  xmlUCSIsEnclosedCJKLettersandMonths	(int code);
extern int  xmlUCSIsEthiopic	(int code);
extern int  xmlUCSIsGeneralPunctuation	(int code);
extern int  xmlUCSIsGeometricShapes	(int code);
extern int  xmlUCSIsGeorgian	(int code);
extern int  xmlUCSIsGothic	(int code);
extern int  xmlUCSIsGreek	(int code);
extern int  xmlUCSIsGreekExtended	(int code);
extern int  xmlUCSIsGreekandCoptic	(int code);
extern int  xmlUCSIsGujarati	(int code);
extern int  xmlUCSIsGurmukhi	(int code);
extern int  xmlUCSIsHalfwidthandFullwidthForms	(int code);
extern int  xmlUCSIsHangulCompatibilityJamo	(int code);
extern int  xmlUCSIsHangulJamo	(int code);
extern int  xmlUCSIsHangulSyllables	(int code);
extern int  xmlUCSIsHanunoo	(int code);
extern int  xmlUCSIsHebrew	(int code);
extern int  xmlUCSIsHighPrivateUseSurrogates	(int code);
extern int  xmlUCSIsHighSurrogates	(int code);
extern int  xmlUCSIsHiragana	(int code);
extern int  xmlUCSIsIPAExtensions	(int code);
extern int  xmlUCSIsIdeographicDescriptionCharacters	(int code);
extern int  xmlUCSIsKanbun	(int code);
extern int  xmlUCSIsKangxiRadicals	(int code);
extern int  xmlUCSIsKannada	(int code);
extern int  xmlUCSIsKatakana	(int code);
extern int  xmlUCSIsKatakanaPhoneticExtensions	(int code);
extern int  xmlUCSIsKhmer	(int code);
extern int  xmlUCSIsKhmerSymbols	(int code);
extern int  xmlUCSIsLao	(int code);
extern int  xmlUCSIsLatin1Supplement	(int code);
extern int  xmlUCSIsLatinExtendedA	(int code);
extern int  xmlUCSIsLatinExtendedB	(int code);
extern int  xmlUCSIsLatinExtendedAdditional	(int code);
extern int  xmlUCSIsLetterlikeSymbols	(int code);
extern int  xmlUCSIsLimbu	(int code);
extern int  xmlUCSIsLinearBIdeograms	(int code);
extern int  xmlUCSIsLinearBSyllabary	(int code);
extern int  xmlUCSIsLowSurrogates	(int code);
extern int  xmlUCSIsMalayalam	(int code);
extern int  xmlUCSIsMathematicalAlphanumericSymbols	(int code);
extern int  xmlUCSIsMathematicalOperators	(int code);
extern int  xmlUCSIsMiscellaneousMathematicalSymbolsA	(int code);
extern int  xmlUCSIsMiscellaneousMathematicalSymbolsB	(int code);
extern int  xmlUCSIsMiscellaneousSymbols	(int code);
extern int  xmlUCSIsMiscellaneousSymbolsandArrows	(int code);
extern int  xmlUCSIsMiscellaneousTechnical	(int code);
extern int  xmlUCSIsMongolian	(int code);
extern int  xmlUCSIsMusicalSymbols	(int code);
extern int  xmlUCSIsMyanmar	(int code);
extern int  xmlUCSIsNumberForms	(int code);
extern int  xmlUCSIsOgham	(int code);
extern int  xmlUCSIsOldItalic	(int code);
extern int  xmlUCSIsOpticalCharacterRecognition	(int code);
extern int  xmlUCSIsOriya	(int code);
extern int  xmlUCSIsOsmanya	(int code);
extern int  xmlUCSIsPhoneticExtensions	(int code);
extern int  xmlUCSIsPrivateUse	(int code);
extern int  xmlUCSIsPrivateUseArea	(int code);
extern int  xmlUCSIsRunic	(int code);
extern int  xmlUCSIsShavian	(int code);
extern int  xmlUCSIsSinhala	(int code);
extern int  xmlUCSIsSmallFormVariants	(int code);
extern int  xmlUCSIsSpacingModifierLetters	(int code);
extern int  xmlUCSIsSpecials	(int code);
extern int  xmlUCSIsSuperscriptsandSubscripts	(int code);
extern int  xmlUCSIsSupplementalArrowsA	(int code);
extern int  xmlUCSIsSupplementalArrowsB	(int code);
extern int  xmlUCSIsSupplementalMathematicalOperators	(int code);
extern int  xmlUCSIsSupplementaryPrivateUseAreaA	(int code);
extern int  xmlUCSIsSupplementaryPrivateUseAreaB	(int code);
extern int  xmlUCSIsSyriac	(int code);
extern int  xmlUCSIsTagalog	(int code);
extern int  xmlUCSIsTagbanwa	(int code);
extern int  xmlUCSIsTags	(int code);
extern int  xmlUCSIsTaiLe	(int code);
extern int  xmlUCSIsTaiXuanJingSymbols	(int code);
extern int  xmlUCSIsTamil	(int code);
extern int  xmlUCSIsTelugu	(int code);
extern int  xmlUCSIsThaana	(int code);
extern int  xmlUCSIsThai	(int code);
extern int  xmlUCSIsTibetan	(int code);
extern int  xmlUCSIsUgaritic	(int code);
extern int  xmlUCSIsUnifiedCanadianAboriginalSyllabics	(int code);
extern int  xmlUCSIsVariationSelectors	(int code);
extern int  xmlUCSIsVariationSelectorsSupplement	(int code);
extern int  xmlUCSIsYiRadicals	(int code);
extern int  xmlUCSIsYiSyllables	(int code);
extern int  xmlUCSIsYijingHexagramSymbols	(int code);

extern int  xmlUCSIsBlock	(int code, const char *block);

extern int  xmlUCSIsCatC	(int code);
extern int  xmlUCSIsCatCc	(int code);
extern int  xmlUCSIsCatCf	(int code);
extern int  xmlUCSIsCatCo	(int code);
extern int  xmlUCSIsCatCs	(int code);
extern int  xmlUCSIsCatL	(int code);
extern int  xmlUCSIsCatLl	(int code);
extern int  xmlUCSIsCatLm	(int code);
extern int  xmlUCSIsCatLo	(int code);
extern int  xmlUCSIsCatLt	(int code);
extern int  xmlUCSIsCatLu	(int code);
extern int  xmlUCSIsCatM	(int code);
extern int  xmlUCSIsCatMc	(int code);
extern int  xmlUCSIsCatMe	(int code);
extern int  xmlUCSIsCatMn	(int code);
extern int  xmlUCSIsCatN	(int code);
extern int  xmlUCSIsCatNd	(int code);
extern int  xmlUCSIsCatNl	(int code);
extern int  xmlUCSIsCatNo	(int code);
extern int  xmlUCSIsCatP	(int code);
extern int  xmlUCSIsCatPc	(int code);
extern int  xmlUCSIsCatPd	(int code);
extern int  xmlUCSIsCatPe	(int code);
extern int  xmlUCSIsCatPf	(int code);
extern int  xmlUCSIsCatPi	(int code);
extern int  xmlUCSIsCatPo	(int code);
extern int  xmlUCSIsCatPs	(int code);
extern int  xmlUCSIsCatS	(int code);
extern int  xmlUCSIsCatSc	(int code);
extern int  xmlUCSIsCatSk	(int code);
extern int  xmlUCSIsCatSm	(int code);
extern int  xmlUCSIsCatSo	(int code);
extern int  xmlUCSIsCatZ	(int code);
extern int  xmlUCSIsCatZl	(int code);
extern int  xmlUCSIsCatZp	(int code);
extern int  xmlUCSIsCatZs	(int code);

extern int  xmlUCSIsCat	(int code, const char *cat);

#ifdef __cplusplus
}
#endif

#endif /* LIBXML_UNICODE_ENABLED */

#endif /* __XML_UNICODE_H__ */
