

{$include apriltag/common/matd.inc}
{$include apriltag/common/zarray.inc}
{$include apriltag/common/time_util.inc}
{$include apriltag/common/timeprofile.inc}
{$include apriltag/common/g2d.inc}
{$include apriltag/common/getopt.inc}
{$include apriltag/common/homography.inc}
{$include apriltag/common/image_types.inc}
{$include apriltag/common/image_u8.inc}
{$include apriltag/common/image_u8x3.inc}
{$include apriltag/common/image_u8x4.inc}
{$include apriltag/common/pam.inc}
{$include apriltag/common/pjpeg.inc}
{$include apriltag/common/pnm.inc}
{$include apriltag/common/postscript_utils.inc}
{$include apriltag/common/pthreads_cross.inc}
{$include apriltag/common/svd22.inc}
{$include apriltag/common/workerpool.inc}
{$include apriltag/common/zmaxheap.inc}
{$include apriltag/common/string_util.inc}
{$include apriltag/common/unionfind.inc}
{$include apriltag/common/zhash.inc}
//doubles,
//doubles_floats_impl,
//floats,
//math_util,

{$include apriltag/apriltag.inc}
{$include apriltag/apriltag_pose.inc}
{$include apriltag/tag16h5.inc}
{$include apriltag/tag25h9.inc}
{$include apriltag/tag36h10.inc}
{$include apriltag/tag36h11.inc}
{$include apriltag/tagCircle21h7.inc}
{$include apriltag/tagCircle49h12.inc}
{$include apriltag/tagCustom48h12.inc}
{$include apriltag/tagStandard41h12.inc}
{$include apriltag/tagStandard52h13.inc}
{$include apriltag/apriltag_math.inc}


