


{$include chafa/chafa_common.inc}             // io.
{$include chafa/chafa_version_macros.inc}     // io.
{$include chafa/chafa_symbol_map.inc}         // io.
{$include chafa/chafa_canvas_config.inc}      // io. -> chafa_symbol_map
{$include chafa/chafa_term_info.inc}          // io.
{$include chafa/chafa_frame.inc}              // io.
{$include chafa/chafa_image.inc}              // io. -> chafa_frame
{$include chafa/chafa_placement.inc}          // io. -> chafa_image
{$include chafa/chafa_canvas.inc}             // io. -> chafa_canvas_config, chafa_placement, chafa_term_info
{$include chafa/chafa_features.inc}           // io.
{$include chafa/chafa_term_db.inc}            // io. -> chafa_term_info
{$include chafa/chafa_util.inc}               // io.

