
unit nm-enum-types;
interface

{
  Automatically converted by H2Pas 1.0.0 from nm-enum-types.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    nm-enum-types.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
{ Generated by glib-mkenums. Do not edit  }
{$ifndef __NM_ENUM_TYPES_H__}
{$define __NM_ENUM_TYPES_H__}
{$include "nm-core-enum-types.h"}
{$include <glib-object.h>}

function nm_client_instance_flags_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function NM_TYPE_CLIENT_INSTANCE_FLAGS : longint; { return type might be wrong }

function nm_client_error_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function NM_TYPE_CLIENT_ERROR : longint; { return type might be wrong }

{$endif}
{ __NM_ENUM_TYPES_H__  }
{ Generated data ends here  }

implementation

{ was #define dname def_expr }
function NM_TYPE_CLIENT_INSTANCE_FLAGS : longint; { return type might be wrong }
  begin
    NM_TYPE_CLIENT_INSTANCE_FLAGS:=nm_client_instance_flags_get_type;
  end;

{ was #define dname def_expr }
function NM_TYPE_CLIENT_ERROR : longint; { return type might be wrong }
  begin
    NM_TYPE_CLIENT_ERROR:=nm_client_error_get_type;
  end;


end.
