

{$include avahi-common/address.inc}
{$include avahi-common/alternative.inc}
{$include avahi-common/defs.inc}
{$include avahi-common/domain.inc}
{$include avahi-common/error.inc}
{$include avahi-common/malloc.inc}
{$include avahi-common/rlist.inc}
{$include avahi-common/strlst.inc}
{$include avahi-common/watch.inc}
{$include avahi-common/thread_watch.inc}    // watch
{$include avahi-common/simple_watch.inc}    // watch
{$include avahi-common/timeval.inc}

