
unit shumate_marshal;
interface

{
  Automatically converted by H2Pas 1.0.0 from shumate_marshal.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    shumate_marshal.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

Type
PGClosure  = ^GClosure;
PGValue  = ^GValue;
{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
(** unsupported pragma#pragma once*)
{$include <glib-object.h>}
{ VOID:DOUBLE,DOUBLE,BOXED (../shumate/shumate-marshal.list:1)  }
(* Const before type ignored *)

procedure _shumate_marshal_VOID__DOUBLE_DOUBLE_BOXED(closure:PGClosure; return_value:PGValue; n_param_values:Tguint; param_values:PGValue; invocation_hint:Tgpointer; 
            marshal_data:Tgpointer);cdecl;external;
{ VOID:UINT,UINT (../shumate/shumate-marshal.list:2)  }
(* Const before type ignored *)
procedure _shumate_marshal_VOID__UINT_UINT(closure:PGClosure; return_value:PGValue; n_param_values:Tguint; param_values:PGValue; invocation_hint:Tgpointer; 
            marshal_data:Tgpointer);cdecl;external;
{ VOID:OBJECT,OBJECT (../shumate/shumate-marshal.list:3)  }
(* Const before type ignored *)
procedure _shumate_marshal_VOID__OBJECT_OBJECT(closure:PGClosure; return_value:PGValue; n_param_values:Tguint; param_values:PGValue; invocation_hint:Tgpointer; 
            marshal_data:Tgpointer);cdecl;external;

implementation


end.
