
unit shumate_enum_types;
interface

{
  Automatically converted by H2Pas 1.0.0 from shumate_enum_types.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    shumate_enum_types.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
{$ifndef __SHUMATE_ENUM_TYPES_H__}
{$define __SHUMATE_ENUM_TYPES_H__}
{$include <glib-object.h>}
{ enumerations from "shumate-file-cache.h"  }

function shumate_file_cache_error_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function SHUMATE_TYPE_FILE_CACHE_ERROR : longint; { return type might be wrong }

{ enumerations from "shumate-map-source.h"  }
function shumate_map_projection_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function SHUMATE_TYPE_MAP_PROJECTION : longint; { return type might be wrong }

{ enumerations from "shumate-scale.h"  }
function shumate_unit_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function SHUMATE_TYPE_UNIT : longint; { return type might be wrong }

{ enumerations from "shumate-tile-downloader.h"  }
function shumate_tile_downloader_error_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function SHUMATE_TYPE_TILE_DOWNLOADER_ERROR : longint; { return type might be wrong }

{ enumerations from "shumate-tile.h"  }
function shumate_state_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function SHUMATE_TYPE_STATE : longint; { return type might be wrong }

{ enumerations from "shumate-vector-reader-iter.h"  }
function shumate_geometry_type_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function SHUMATE_TYPE_GEOMETRY_TYPE : longint; { return type might be wrong }

{ enumerations from "shumate-vector-renderer.h"  }
function shumate_style_error_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function SHUMATE_TYPE_STYLE_ERROR : longint; { return type might be wrong }

{$endif}
{ __SHUMATE_ENUM_TYPES_H__  }
{ Generated data ends here  }

implementation

{ was #define dname def_expr }
function SHUMATE_TYPE_FILE_CACHE_ERROR : longint; { return type might be wrong }
  begin
    SHUMATE_TYPE_FILE_CACHE_ERROR:=shumate_file_cache_error_get_type;
  end;

{ was #define dname def_expr }
function SHUMATE_TYPE_MAP_PROJECTION : longint; { return type might be wrong }
  begin
    SHUMATE_TYPE_MAP_PROJECTION:=shumate_map_projection_get_type;
  end;

{ was #define dname def_expr }
function SHUMATE_TYPE_UNIT : longint; { return type might be wrong }
  begin
    SHUMATE_TYPE_UNIT:=shumate_unit_get_type;
  end;

{ was #define dname def_expr }
function SHUMATE_TYPE_TILE_DOWNLOADER_ERROR : longint; { return type might be wrong }
  begin
    SHUMATE_TYPE_TILE_DOWNLOADER_ERROR:=shumate_tile_downloader_error_get_type;
  end;

{ was #define dname def_expr }
function SHUMATE_TYPE_STATE : longint; { return type might be wrong }
  begin
    SHUMATE_TYPE_STATE:=shumate_state_get_type;
  end;

{ was #define dname def_expr }
function SHUMATE_TYPE_GEOMETRY_TYPE : longint; { return type might be wrong }
  begin
    SHUMATE_TYPE_GEOMETRY_TYPE:=shumate_geometry_type_get_type;
  end;

{ was #define dname def_expr }
function SHUMATE_TYPE_STYLE_ERROR : longint; { return type might be wrong }
  begin
    SHUMATE_TYPE_STYLE_ERROR:=shumate_style_error_get_type;
  end;


end.
