


{$include gnutls/gnutls.inc}          // io.
{$include gnutls/x509.inc}            // io,
{$include gnutls/x509_ext.inc}        // io. x509
{$include gnutls/pkcs7.inc}           // io. x509
{$include gnutls/pkcs11.inc}          // io. x509
{$include gnutls/pkcs12.inc}          // io.
{$include gnutls/ocsp.inc}            // io. x509
{$include gnutls/tpm.inc}             // io.
{$include gnutls/socket.inc}          // io.
{$include gnutls/crypto.inc}          // io.
{$include gnutls/dane.inc}            // io.
{$include gnutls/dtls.inc}            // io.
{$include gnutls/openpgp.inc}         // io.           ( deprecated )
{$include gnutls/self_test.inc}       // io.
{$include gnutls/system_keys.inc}     // io.
{$include gnutls/urls.inc}            // io.
{$include gnutls/abstract.inc}        // io. x509, pkcs11, openpgp, tpm
{$include gnutls/openssl.inc}         // io.  ( Makros ausgeklammert )


