
unit app_enumtypes;
interface

{
  Automatically converted by H2Pas 1.0.0 from app_enumtypes.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    app_enumtypes.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
(** unsupported pragma#pragma once*)
{$include <glib-object.h>}
{$include <gst/app/app-prelude.h>}
{ enumerations from "gstappsrc.h"  }

function gst_app_stream_type_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GST_TYPE_APP_STREAM_TYPE : longint; { return type might be wrong }

function gst_app_leaky_type_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function GST_TYPE_APP_LEAKY_TYPE : longint; { return type might be wrong }

{ Generated data ends here  }

implementation

{ was #define dname def_expr }
function GST_TYPE_APP_STREAM_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_APP_STREAM_TYPE:=gst_app_stream_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_APP_LEAKY_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_APP_LEAKY_TYPE:=gst_app_leaky_type_get_type;
  end;


end.
