
unit eina_config;
interface

{
  Automatically converted by H2Pas 1.0.0 from eina_config.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    eina_config.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
  }
(** unsupported pragma#pragma once*)

const
  EINA_CONFIGURE_HAVE_DIRENT_H = 1;  
  EINA_ENABLE_LOG = 1;  
  EINA_HAVE_ALLOCA_H = 1;  
  EINA_HAVE_BYTESWAP_H = 1;  
  EINA_HAVE_POSIX_SPINLOCK = 1;  
  EINA_HAVE_PTHREAD_AFFINITY = 1;  
  EINA_HAVE_PTHREAD_BARRIER = 1;  
  EINA_HAVE_PTHREAD_SETNAME = 1;  
  EINA_HAVE_THREADS = 1;  
  EINA_MAGIC_DEBUG = 1;  
  EINA_SAFETY_CHECKS = 1;  
  EINA_SIZEOF_UINTPTR_T = 8;  
  EINA_SIZEOF_WCHAR_T = 4;  

implementation


end.
