{$IFDEF read_interface}


{$ifndef _EFL_UI_FLIP_LEGACY_EO_LEGACY_H_}
{$define _EFL_UI_FLIP_LEGACY_EO_LEGACY_H_}
{$ifndef _EFL_UI_FLIP_LEGACY_EO_CLASS_TYPE}
{$define _EFL_UI_FLIP_LEGACY_EO_CLASS_TYPE}
type
  PEfl_Ui_Flip_Legacy = ^TEfl_Ui_Flip_Legacy;
  TEfl_Ui_Flip_Legacy = TEo;
{$endif}
{$ifndef _EFL_UI_FLIP_LEGACY_EO_TYPES}
{$define _EFL_UI_FLIP_LEGACY_EO_TYPES}
{$endif}
{$endif}

// === Konventiert am: 28-5-25 19:37:17 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
