{$IFDEF read_interface}


procedure elm_photocam_gesture_enabled_set(obj: PEfl_Ui_Image_Zoomable; gesture: TEina_Bool); cdecl; external libelementary;
function elm_photocam_gesture_enabled_get(obj: PEfl_Ui_Image_Zoomable): TEina_Bool; cdecl; external libelementary;

// === Konventiert am: 31-5-25 15:27:19 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
