{$IFDEF read_interface}


function elm_index_add(parent: PEvas_Object): PEvas_Object; cdecl; external libelementary;
procedure elm_index_horizontal_set(obj: PEvas_Object; horizontal: TEina_Bool); cdecl; external libelementary;
function elm_index_horizontal_get(obj: PEvas_Object): TEina_Bool; cdecl; external libelementary;

// === Konventiert am: 28-5-25 13:40:21 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
