{$IFDEF read_interface}


type
  TElm_Web_Data = record
    obj: PEvas_Object;
  end;
  PElm_Web_Data = ^TElm_Web_Data;

  TElm_Web_Callback_Proxy_Context = record
    name: pchar;
    obj: PEvas_Object;
  end;
  PElm_Web_Callback_Proxy_Context = ^TElm_Web_Callback_Proxy_Context;


  // === Konventiert am: 1-6-25 15:54:15 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
