{$IFDEF read_interface}


function _elm_systray_watcher_status_notifier_item_register(obj: pchar): TEina_Bool; cdecl; external libelementary;
function _elm_systray_watcher_init: TEina_Bool; cdecl; external libelementary;
procedure _elm_systray_watcher_shutdown; cdecl; external libelementary;

// === Konventiert am: 1-6-25 15:10:34 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
