{$IFDEF read_interface}


function elm_code_diff_widget_add(parent: PEvas_Object; code: PElm_Code): PEvas_Object; cdecl; external libelementary;
procedure elm_code_diff_widget_font_set(widget: PEvas_Object; name: pchar; size: longint); cdecl; external libelementary;

// === Konventiert am: 26-5-25 16:41:32 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
