{$IFDEF read_interface}


{$ifndef _ELM_FILESELECTOR_BUTTON_EO_LEGACY_H_}
{$define _ELM_FILESELECTOR_BUTTON_EO_LEGACY_H_}
{$ifndef _ELM_FILESELECTOR_BUTTON_EO_CLASS_TYPE}
{$define _ELM_FILESELECTOR_BUTTON_EO_CLASS_TYPE}
type
  PElm_Fileselector_Button = ^TElm_Fileselector_Button;
  TElm_Fileselector_Button = TEo;
{$endif}
{$ifndef _ELM_FILESELECTOR_BUTTON_EO_TYPES}
{$define _ELM_FILESELECTOR_BUTTON_EO_TYPES}
{$endif}
{$endif}

// === Konventiert am: 27-5-25 17:01:43 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
