unit eina_config;

interface

uses
  ctypes, efl;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}



const
  EINA_CONFIGURE_HAVE_DIRENT_H = 1;  
  EINA_ENABLE_LOG = 1;  
  EINA_HAVE_ALLOCA_H = 1;  
  EINA_HAVE_BYTESWAP_H = 1;  
  EINA_HAVE_POSIX_SPINLOCK = 1;  
  EINA_HAVE_PTHREAD_AFFINITY = 1;  
  EINA_HAVE_PTHREAD_BARRIER = 1;  
  EINA_HAVE_PTHREAD_SETNAME = 1;  
  EINA_HAVE_THREADS = 1;  
  EINA_MAGIC_DEBUG = 1;  
  EINA_SAFETY_CHECKS = 1;  
  EINA_SIZEOF_UINTPTR_T = 8;  
  EINA_SIZEOF_WCHAR_T = 4;  

// === Konventiert am: 14-5-25 17:27:32 ===


implementation



end.
