unit audio_enumtypes;

interface

uses
  fp_glib2, fp_gst;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
(** unsupported pragma#pragma once*)
{$include <glib-object.h>}
{$include <gst/audio/audio-prelude.h>}
{ enumerations from "audio-channel-mixer.h"  }

function gst_audio_channel_mixer_flags_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_CHANNEL_MIXER_FLAGS : longint; { return type might be wrong }

{ enumerations from "audio-channels.h"  }
function gst_audio_channel_position_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_CHANNEL_POSITION : longint; { return type might be wrong }

{ enumerations from "audio-converter.h"  }
function gst_audio_converter_flags_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_CONVERTER_FLAGS : longint; { return type might be wrong }

{ enumerations from "audio-format.h"  }
function gst_audio_format_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_FORMAT : longint; { return type might be wrong }

function gst_audio_format_flags_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_FORMAT_FLAGS : longint; { return type might be wrong }

function gst_audio_pack_flags_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_PACK_FLAGS : longint; { return type might be wrong }

function gst_audio_layout_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_LAYOUT : longint; { return type might be wrong }

{ enumerations from "audio-info.h"  }
function gst_audio_flags_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_FLAGS : longint; { return type might be wrong }

{ enumerations from "audio-quantize.h"  }
function gst_audio_dither_method_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_DITHER_METHOD : longint; { return type might be wrong }

function gst_audio_noise_shaping_method_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_NOISE_SHAPING_METHOD : longint; { return type might be wrong }

function gst_audio_quantize_flags_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_QUANTIZE_FLAGS : longint; { return type might be wrong }

{ enumerations from "audio-resampler.h"  }
function gst_audio_resampler_filter_mode_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_RESAMPLER_FILTER_MODE : longint; { return type might be wrong }

function gst_audio_resampler_filter_interpolation_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_RESAMPLER_FILTER_INTERPOLATION : longint; { return type might be wrong }

function gst_audio_resampler_method_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_RESAMPLER_METHOD : longint; { return type might be wrong }

function gst_audio_resampler_flags_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_RESAMPLER_FLAGS : longint; { return type might be wrong }

{ enumerations from "gstaudiobasesink.h"  }
function gst_audio_base_sink_slave_method_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_BASE_SINK_SLAVE_METHOD : longint; { return type might be wrong }

function gst_audio_base_sink_discont_reason_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_BASE_SINK_DISCONT_REASON : longint; { return type might be wrong }

{ enumerations from "gstaudiobasesrc.h"  }
function gst_audio_base_src_slave_method_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_BASE_SRC_SLAVE_METHOD : longint; { return type might be wrong }

{ enumerations from "gstaudiocdsrc.h"  }
function gst_audio_cd_src_mode_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_CD_SRC_MODE : longint; { return type might be wrong }

{ enumerations from "gstaudioringbuffer.h"  }
function gst_audio_ring_buffer_state_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_RING_BUFFER_STATE : longint; { return type might be wrong }

function gst_audio_ring_buffer_format_type_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_AUDIO_RING_BUFFER_FORMAT_TYPE : longint; { return type might be wrong }

{ enumerations from "gstdsdformat.h"  }
function gst_dsd_format_get_type:TGType;cdecl;external libgstaudio;
{ was #define dname def_expr }
function GST_TYPE_DSD_FORMAT : longint; { return type might be wrong }

{ Generated data ends here  }

// === Konventiert am: 16-7-26 15:10:38 ===


implementation


{ was #define dname def_expr }
function GST_TYPE_AUDIO_CHANNEL_MIXER_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_CHANNEL_MIXER_FLAGS:=gst_audio_channel_mixer_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_CHANNEL_POSITION : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_CHANNEL_POSITION:=gst_audio_channel_position_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_CONVERTER_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_CONVERTER_FLAGS:=gst_audio_converter_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_FORMAT : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_FORMAT:=gst_audio_format_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_FORMAT_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_FORMAT_FLAGS:=gst_audio_format_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_PACK_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_PACK_FLAGS:=gst_audio_pack_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_LAYOUT : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_LAYOUT:=gst_audio_layout_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_FLAGS:=gst_audio_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_DITHER_METHOD : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_DITHER_METHOD:=gst_audio_dither_method_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_NOISE_SHAPING_METHOD : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_NOISE_SHAPING_METHOD:=gst_audio_noise_shaping_method_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_QUANTIZE_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_QUANTIZE_FLAGS:=gst_audio_quantize_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_RESAMPLER_FILTER_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_RESAMPLER_FILTER_MODE:=gst_audio_resampler_filter_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_RESAMPLER_FILTER_INTERPOLATION : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_RESAMPLER_FILTER_INTERPOLATION:=gst_audio_resampler_filter_interpolation_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_RESAMPLER_METHOD : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_RESAMPLER_METHOD:=gst_audio_resampler_method_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_RESAMPLER_FLAGS : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_RESAMPLER_FLAGS:=gst_audio_resampler_flags_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_BASE_SINK_SLAVE_METHOD : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_BASE_SINK_SLAVE_METHOD:=gst_audio_base_sink_slave_method_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_BASE_SINK_DISCONT_REASON : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_BASE_SINK_DISCONT_REASON:=gst_audio_base_sink_discont_reason_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_BASE_SRC_SLAVE_METHOD : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_BASE_SRC_SLAVE_METHOD:=gst_audio_base_src_slave_method_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_CD_SRC_MODE : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_CD_SRC_MODE:=gst_audio_cd_src_mode_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_RING_BUFFER_STATE : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_RING_BUFFER_STATE:=gst_audio_ring_buffer_state_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_AUDIO_RING_BUFFER_FORMAT_TYPE : longint; { return type might be wrong }
  begin
    GST_TYPE_AUDIO_RING_BUFFER_FORMAT_TYPE:=gst_audio_ring_buffer_format_type_get_type;
  end;

{ was #define dname def_expr }
function GST_TYPE_DSD_FORMAT : longint; { return type might be wrong }
  begin
    GST_TYPE_DSD_FORMAT:=gst_dsd_format_get_type;
  end;


end.
