unit WebKitContextMenuActions;

interface

uses
  fp_glib2, fp_GTK4, WebKit;

  {$IFDEF FPC}
  {$PACKRECORDS C}
  {$ENDIF}

type
  PWebKitContextMenuAction = ^TWebKitContextMenuAction;
  TWebKitContextMenuAction = longint;

const
  WEBKIT_CONTEXT_MENU_ACTION_NO_ACTION = 0;
  WEBKIT_CONTEXT_MENU_ACTION_OPEN_LINK = 1;
  WEBKIT_CONTEXT_MENU_ACTION_OPEN_LINK_IN_NEW_WINDOW = 2;
  WEBKIT_CONTEXT_MENU_ACTION_DOWNLOAD_LINK_TO_DISK = 3;
  WEBKIT_CONTEXT_MENU_ACTION_COPY_LINK_TO_CLIPBOARD = 4;
  WEBKIT_CONTEXT_MENU_ACTION_OPEN_IMAGE_IN_NEW_WINDOW = 5;
  WEBKIT_CONTEXT_MENU_ACTION_DOWNLOAD_IMAGE_TO_DISK = 6;
  WEBKIT_CONTEXT_MENU_ACTION_COPY_IMAGE_TO_CLIPBOARD = 7;
  WEBKIT_CONTEXT_MENU_ACTION_COPY_IMAGE_URL_TO_CLIPBOARD = 8;
  WEBKIT_CONTEXT_MENU_ACTION_OPEN_FRAME_IN_NEW_WINDOW = 9;
  WEBKIT_CONTEXT_MENU_ACTION_GO_BACK = 10;
  WEBKIT_CONTEXT_MENU_ACTION_GO_FORWARD = 11;
  WEBKIT_CONTEXT_MENU_ACTION_STOP = 12;
  WEBKIT_CONTEXT_MENU_ACTION_RELOAD = 13;
  WEBKIT_CONTEXT_MENU_ACTION_COPY = 14;
  WEBKIT_CONTEXT_MENU_ACTION_CUT = 15;
  WEBKIT_CONTEXT_MENU_ACTION_PASTE = 16;
  WEBKIT_CONTEXT_MENU_ACTION_DELETE = 17;
  WEBKIT_CONTEXT_MENU_ACTION_SELECT_ALL = 18;
  WEBKIT_CONTEXT_MENU_ACTION_INPUT_METHODS = 19;
  WEBKIT_CONTEXT_MENU_ACTION_UNICODE = 20;
  WEBKIT_CONTEXT_MENU_ACTION_SPELLING_GUESS = 21;
  WEBKIT_CONTEXT_MENU_ACTION_NO_GUESSES_FOUND = 22;
  WEBKIT_CONTEXT_MENU_ACTION_IGNORE_SPELLING = 23;
  WEBKIT_CONTEXT_MENU_ACTION_LEARN_SPELLING = 24;
  WEBKIT_CONTEXT_MENU_ACTION_IGNORE_GRAMMAR = 25;
  WEBKIT_CONTEXT_MENU_ACTION_FONT_MENU = 26;
  WEBKIT_CONTEXT_MENU_ACTION_BOLD = 27;
  WEBKIT_CONTEXT_MENU_ACTION_ITALIC = 28;
  WEBKIT_CONTEXT_MENU_ACTION_UNDERLINE = 29;
  WEBKIT_CONTEXT_MENU_ACTION_OUTLINE = 30;
  WEBKIT_CONTEXT_MENU_ACTION_INSPECT_ELEMENT = 31;
  WEBKIT_CONTEXT_MENU_ACTION_OPEN_VIDEO_IN_NEW_WINDOW = 32;
  WEBKIT_CONTEXT_MENU_ACTION_OPEN_AUDIO_IN_NEW_WINDOW = 33;
  WEBKIT_CONTEXT_MENU_ACTION_COPY_VIDEO_LINK_TO_CLIPBOARD = 34;
  WEBKIT_CONTEXT_MENU_ACTION_COPY_AUDIO_LINK_TO_CLIPBOARD = 35;
  WEBKIT_CONTEXT_MENU_ACTION_TOGGLE_MEDIA_CONTROLS = 36;
  WEBKIT_CONTEXT_MENU_ACTION_TOGGLE_MEDIA_LOOP = 37;
  WEBKIT_CONTEXT_MENU_ACTION_ENTER_VIDEO_FULLSCREEN = 38;
  WEBKIT_CONTEXT_MENU_ACTION_MEDIA_PLAY = 39;
  WEBKIT_CONTEXT_MENU_ACTION_MEDIA_PAUSE = 40;
  WEBKIT_CONTEXT_MENU_ACTION_MEDIA_MUTE = 41;
  WEBKIT_CONTEXT_MENU_ACTION_DOWNLOAD_VIDEO_TO_DISK = 42;
  WEBKIT_CONTEXT_MENU_ACTION_DOWNLOAD_AUDIO_TO_DISK = 43;
  WEBKIT_CONTEXT_MENU_ACTION_INSERT_EMOJI = 44;
  WEBKIT_CONTEXT_MENU_ACTION_PASTE_AS_PLAIN_TEXT = 45;
  WEBKIT_CONTEXT_MENU_ACTION_CUSTOM = 10000;

  // === Konventiert am: 3-1-25 15:47:42 ===


implementation



end.
