


{$include portal/types.inc}
{$include portal/portal_helpers.inc}
{$include portal/portal_enums.inc}
{$include portal/account.inc}
{$include portal/background.inc}
{$include portal/camera.inc}
{$include portal/dynamic_launcher.inc}
{$include portal/email.inc}
{$include portal/filechooser.inc}
{$include portal/inhibit.inc}
{$include portal/location.inc}
{$include portal/notification.inc}
{$include portal/openuri.inc}
{$include portal/parent.inc}
{$include portal/print.inc}
{$include portal/remote.inc}
{$include portal/screenshot.inc}
{$include portal/spawn.inc}
{$include portal/trash.inc}
{$include portal/updates.inc}
{$include portal/wallpaper.inc}


