
unit H5f90i_gen;
interface

{
  Automatically converted by H2Pas 1.0.0 from H5f90i_gen.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    H5f90i_gen.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

Type
Pc_int_16  = ^c_int_16;
Pdouble_f  = ^double_f;
Phaddr_t_f  = ^haddr_t_f;
Phid_t_f  = ^hid_t_f;
Phsize_t_f  = ^hsize_t_f;
Phssize_t_f  = ^hssize_t_f;
Pint_f  = ^int_f;
Poff_t_f  = ^off_t_f;
Preal_C_DOUBLE_f  = ^real_C_DOUBLE_f;
Preal_C_FLOAT128_f  = ^real_C_FLOAT128_f;
Preal_C_FLOAT_f  = ^real_C_FLOAT_f;
Preal_C_LONG_DOUBLE_f  = ^real_C_LONG_DOUBLE_f;
Preal_f  = ^real_f;
Psize_t_f  = ^size_t_f;
Ptime_t_f  = ^time_t_f;
{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the COPYING file, which can be found at the root of the source code       *
 * distribution tree, or in https://www.hdfgroup.org/licenses.               *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *  }
{$ifndef H5f90i_gen_H}
{$define H5f90i_gen_H}
{ This file is automatically generated by H5match_types.c at build time.  }
{$include "H5public.h"}

const
  c_int_1 = char;  
  c_int_2 = smallint;  
  c_int_4 = longint;  
  c_int_8 = int64;  
  c_size_t_8 = size_t;  
  c_time_t_8 = time_t;  
  c_hsize_t_8 = hsize_t;  
type
  Pc_int_16 = ^Tc_int_16;
  Tc_int_16 = record
      a : Tc_int_8;
      b : Tc_int_8;
    end;

const
  c_float_4 = single;  
  c_float_8 = double;  
  c_float_10 = long_double;  
  c_float_16 = __float128;  
type
  Phaddr_t_f = ^Thaddr_t_f;
  Thaddr_t_f = Tc_int_8;

  Phsize_t_f = ^Thsize_t_f;
  Thsize_t_f = Tc_hsize_t_8;

  Phssize_t_f = ^Thssize_t_f;
  Thssize_t_f = Tc_int_8;

  Poff_t_f = ^Toff_t_f;
  Toff_t_f = Tc_int_8;

  Psize_t_f = ^Tsize_t_f;
  Tsize_t_f = Tc_size_t_8;

  Ptime_t_f = ^Ttime_t_f;
  Ttime_t_f = Tc_time_t_8;

  Pint_f = ^Tint_f;
  Tint_f = Tc_int_4;

  Preal_C_FLOAT_f = ^Treal_C_FLOAT_f;
  Treal_C_FLOAT_f = Tc_float_4;

  Preal_C_DOUBLE_f = ^Treal_C_DOUBLE_f;
  Treal_C_DOUBLE_f = Tc_float_8;

  Preal_C_LONG_DOUBLE_f = ^Treal_C_LONG_DOUBLE_f;
  Treal_C_LONG_DOUBLE_f = Tc_float_10;

  Preal_C_FLOAT128_f = ^Treal_C_FLOAT128_f;
  Treal_C_FLOAT128_f = Tc_float_16;

  Phid_t_f = ^Thid_t_f;
  Thid_t_f = Tc_int_8;

  Preal_f = ^Treal_f;
  Treal_f = Tc_float_4;

  Pdouble_f = ^Tdouble_f;
  Tdouble_f = Tc_float_8;
{$endif}
{ _H5f90i_gen_H  }

implementation


end.
