unit igmp;

interface

uses
  clib, in_;

  {$IFDEF FPC}
  {$PACKRECORDS C}
  {$ENDIF}


type
  Tigmp = record
    igmp_type: Tuint8_t;
    igmp_code: Tuint8_t;
    igmp_cksum: Tuint16_t;
    igmp_group: Tin_addr;
  end;
  Pigmp = ^Tigmp;

const
  IGMP_MINLEN = 8;
  IGMP_MEMBERSHIP_QUERY = $11;
  IGMP_V1_MEMBERSHIP_REPORT = $12;
  IGMP_V2_MEMBERSHIP_REPORT = $16;
  IGMP_V2_LEAVE_GROUP = $17;
  IGMP_DVMRP = $13;
  IGMP_PIM = $14;
  IGMP_TRACE = $15;
  IGMP_MTRACE_RESP = $1e;
  IGMP_MTRACE = $1f;
  IGMP_MRDISC_ADV = $30;
  IGMP_MAX_HOST_REPORT_DELAY = 10;
  IGMP_TIMER_SCALE = 10;
  IGMP_DELAYING_MEMBER = 1;
  IGMP_IDLE_MEMBER = 2;
  IGMP_LAZY_MEMBER = 3;
  IGMP_SLEEPING_MEMBER = 4;
  IGMP_AWAKENING_MEMBER = 5;
  IGMP_v1_ROUTER = 1;
  IGMP_v2_ROUTER = 2;

  IGMP_HOST_MEMBERSHIP_QUERY = IGMP_MEMBERSHIP_QUERY;
  IGMP_HOST_MEMBERSHIP_REPORT = IGMP_V1_MEMBERSHIP_REPORT;
  IGMP_HOST_NEW_MEMBERSHIP_REPORT = IGMP_V2_MEMBERSHIP_REPORT;
  IGMP_HOST_LEAVE_MESSAGE = IGMP_V2_LEAVE_GROUP;

  // === Konventiert am: 10-8-25 17:28:09 ===


implementation



end.
