{$IFDEF read_interface}



{$ifdef EFL_BETA_API_SUPPORT}
var
  EFL_NET_HTTP_ERROR_BAD_CONTENT_ENCODING: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_BAD_DOWNLOAD_RESUME: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_BAD_FUNCTION_ARGUMENT: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_CHUNK_FAILED: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_CONV_FAILED: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_CONV_REQD: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_FAILED_INIT: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_FILE_COULDNT_READ_FILE: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_FILESIZE_EXCEEDED: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_FUNCTION_NOT_FOUND: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_GOT_NOTHING: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_HTTP2: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_HTTP2_STREAM: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_HTTP_POST_ERROR: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_HTTP_RETURNED_ERROR: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_INTERFACE_FAILED: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_LOGIN_DENIED: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_NO_CONNECTION_AVAILABLE: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_NOT_BUILT_IN: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_OPERATION_TIMEDOUT: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_PARTIAL_FILE: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_PEER_FAILED_VERIFICATION: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_RANGE_ERROR: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_READ_ERROR: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_RECV_ERROR: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_REMOTE_ACCESS_DENIED: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_REMOTE_DISK_FULL: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_REMOTE_FILE_EXISTS: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_REMOTE_FILE_NOT_FOUND: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SEND_ERROR: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SEND_FAIL_REWIND: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SSL_CACERT: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SSL_CACERT_BADFILE: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SSL_CERTPROBLEM: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SSL_CIPHER: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SSL_CONNECT_ERROR: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SSL_CRL_BADFILE: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SSL_ENGINE_INITFAILED: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SSL_ENGINE_NOTFOUND: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SSL_ENGINE_SETFAILED: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SSL_INVALIDCERTSTATUS: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SSL_ISSUER_ERROR: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SSL_PINNEDPUBKEYNOTMATCH: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_SSL_SHUTDOWN_FAILED: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_TOO_MANY_REDIRECTS: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_UNKNOWN_OPTION: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_UNSUPPORTED_PROTOCOL: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_UPLOAD_FAILED: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_URL_MALFORMAT: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_USE_SSL_FAILED: TEina_Error; cvar;external libecore_con;
  EFL_NET_HTTP_ERROR_WRITE_ERROR: TEina_Error; cvar;external libecore_con;
  {$endif}

  // === Konventiert am: 9-6-25 17:03:07 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
