

{$include xraylib/xraylib_lines.inc}
{$include xraylib/xraylib_error.inc}
{$include xraylib/xraylib_defs.inc}
{$include xraylib/xraylib.inc}
{$include xraylib/xraylib_auger.inc}
{$include xraylib/xraylib_aux.inc}
{$include xraylib/xraylib_crystal_diffraction.inc}
{$include xraylib/xraylib_deprecated.inc}
{$include xraylib/xraylib_nist_compounds.inc}
{$include xraylib/xraylib_parser.inc}
{$include xraylib/xraylib_radionuclides.inc}
{$include xraylib/xraylib_shells.inc}

