
unit WebKitWebProcessEnumTypes;
interface

{
  Automatically converted by H2Pas 1.0.0 from WebKitWebProcessEnumTypes.h
  The following command line parameters were used:
    -p
    -T
    -d
    -c
    -e
    WebKitWebProcessEnumTypes.h
}

{ Pointers to basic pascal types, inserted by h2pas conversion program.}
Type
  PLongint  = ^Longint;
  PSmallInt = ^SmallInt;
  PByte     = ^Byte;
  PWord     = ^Word;
  PDWord    = ^DWord;
  PDouble   = ^Double;

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses.  }
{
 * Copyright (C) 2017 Igalia S.L.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
  }
{$if !defined(__WEBKIT_WEB_PROCESS_EXTENSION_H_INSIDE__) && !defined(BUILDING_WEBKIT)}
{$error "Only <webkit${WEBKITGTK_API_INFIX}/webkit-web-process-extension.h> can be included directly."}
{$endif}
{$ifndef WEBKIT_WEB_PROCESS_ENUM_TYPES_H}
{$define WEBKIT_WEB_PROCESS_ENUM_TYPES_H}
{$include <glib-object.h>}
{$include <webkit/WebKitDefines.h>}
{ Enumerations from WebKitConsoleMessage.h.  }

{ was #define dname def_expr }
function WEBKIT_TYPE_CONSOLE_MESSAGE_SOURCE : longint; { return type might be wrong }

function webkit_console_message_source_get_type:TGType;cdecl;external;
{ was #define dname def_expr }
function WEBKIT_TYPE_CONSOLE_MESSAGE_LEVEL : longint; { return type might be wrong }

function webkit_console_message_level_get_type:TGType;cdecl;external;
{$endif}
{ Generated data ends here  }

implementation

{ was #define dname def_expr }
function WEBKIT_TYPE_CONSOLE_MESSAGE_SOURCE : longint; { return type might be wrong }
  begin
    WEBKIT_TYPE_CONSOLE_MESSAGE_SOURCE:=webkit_console_message_source_get_type;
  end;

{ was #define dname def_expr }
function WEBKIT_TYPE_CONSOLE_MESSAGE_LEVEL : longint; { return type might be wrong }
  begin
    WEBKIT_TYPE_CONSOLE_MESSAGE_LEVEL:=webkit_console_message_level_get_type;
  end;


end.
